CREATE TABLE `kphis_log`.`ipt_log` (
  `ipt_log_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ipt_log_type` VARCHAR(1) NOT NULL,
  `an` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `vn` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
  `hn` VARCHAR(9) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
  `ward` VARCHAR(4) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
  `create_datetime` DATETIME NOT NULL,
	PRIMARY KEY (`ipt_log_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;