use super::{
    doc::{MRA_MISSING, MRA_NA, MRA_NO, MraDoc},
    ipd_mra, ipd_mra_psy,
};
use kphis_model::{image::file_path::DocumentType, report::SystemReport};

pub enum Report {
    Template(SystemReport),
    Document(DocumentType),
}

#[derive(Clone, PartialEq)]
pub enum MraRow {
    Sd(MraCol),
    So(MraCol),
    Ic(MraCol),
    Hx(MraCol),
    Pe(MraCol),
    Pn(MraCol),
    Cr(MraCol),
    Ar(MraCol),
    On(MraCol),
    Lr(MraCol),
    Rr(MraCol),
    Nn(MraCol),
}

impl MraRow {
    pub fn label(&self, mra: Mra) -> &'static str {
        match mra {
            Mra::Ipd => match self {
                Self::Sd(_) => "1. D/C:Dx,Op",
                Self::So(_) => "2. D/C:Other",
                Self::Ic(_) => "3. Consent",
                Self::Hx(_) => "4. History",
                Self::Pe(_) => "5. PE",
                Self::Pn(_) => "6. Order/Note",
                Self::Cr(_) => "7. Consult",
                Self::Ar(_) => "8. Anes",
                Self::On(_) => "9. Operation",
                Self::Lr(_) => "10. Labour",
                Self::Rr(_) => "11. Rehab",
                Self::Nn(_) => "12. Nurse Note",
            },
            Mra::IpdPsy => match self {
                Self::Sd(_) => "1. D/C:Dx,Op",
                Self::So(_) => "2. D/C:Other",
                Self::Ic(_) => "3. Consent",
                Self::Hx(_) => "4. History",
                Self::Pe(_) => "5. PE",
                Self::Pn(_) => "6. Order/Note",
                Self::Cr(_) => "7. Consult",
                Self::Ar(_) => "8. Anes",
                Self::On(_) => "9. Operation",
                Self::Lr(_) => "",
                Self::Rr(_) => "10. Rehab",
                Self::Nn(_) => "11. Nurse Note",
            },
        }
    }

    pub fn is_na(&self) -> bool {
        match self {
            Self::Sd(col) => matches!(col, MraCol::NA),
            Self::So(col) => matches!(col, MraCol::NA),
            Self::Ic(col) => matches!(col, MraCol::NA),
            Self::Hx(col) => matches!(col, MraCol::NA),
            Self::Pe(col) => matches!(col, MraCol::NA),
            Self::Pn(col) => matches!(col, MraCol::NA),
            Self::Cr(col) => matches!(col, MraCol::NA),
            Self::Ar(col) => matches!(col, MraCol::NA),
            Self::On(col) => matches!(col, MraCol::NA),
            Self::Lr(col) => matches!(col, MraCol::NA),
            Self::Rr(col) => matches!(col, MraCol::NA),
            Self::Nn(col) => matches!(col, MraCol::NA),
        }
    }

    pub fn can_na(&self, mra: Mra) -> bool {
        match mra {
            // allow NA in SD_2, SD_3, SD_4, SD_7, PE_4, AR_7, LR_3
            Mra::Ipd => match self {
                Self::Sd(col) => matches!(col, MraCol::P2 | MraCol::P3 | MraCol::P4 | MraCol::P7),
                Self::Pe(col) => matches!(col, MraCol::P4),
                Self::Ar(col) => matches!(col, MraCol::P7),
                Self::Lr(col) => matches!(col, MraCol::P3),
                _ => false,
            },
            // allow NA in SD_2, SD_3, SD_4, SD_7, IC_5, AR_7, ON_4
            Mra::IpdPsy => match self {
                Self::Sd(col) => matches!(col, MraCol::P2 | MraCol::P3 | MraCol::P4 | MraCol::P7),
                Self::Ic(col) => matches!(col, MraCol::P5),
                Self::Ar(col) => matches!(col, MraCol::P7),
                Self::On(col) => matches!(col, MraCol::P4),
                _ => false,
            },
        }
    }

    pub fn report(&self) -> Report {
        match self {
            Self::Sd(_) => Report::Template(SystemReport::IpdSummary),
            Self::So(_) => Report::Template(SystemReport::IpdSummary),
            Self::Ic(_) => Report::Document(DocumentType::InformedConsent),
            Self::Hx(_) => Report::Template(SystemReport::IpdAdmissionNoteDr),
            Self::Pe(_) => Report::Template(SystemReport::IpdAdmissionNoteDr),
            Self::Pn(_) => Report::Template(SystemReport::IpdOrder),
            Self::Cr(_) => Report::Template(SystemReport::IpdConsult),
            Self::Ar(_) => Report::Document(DocumentType::Anesthesia),
            Self::On(_) => Report::Document(DocumentType::Operation),
            Self::Lr(_) => Report::Template(SystemReport::IpdPartographWho),
            Self::Rr(_) => Report::Document(DocumentType::Physiotherapy),
            Self::Nn(col) => match col {
                MraCol::La | MraCol::P1 => Report::Template(SystemReport::IpdAdmissionNoteNurse),
                _ => Report::Template(SystemReport::IpdFocusNote),
            },
        }
    }

    pub fn doc(&self, mra: Mra) -> Option<MraDoc> {
        match mra {
            Mra::Ipd => match self {
                Self::Sd(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_SD.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_SD_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_SD_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_SD_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_SD_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_SD_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_SD_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_SD_7.clone()),
                    MraCol::P8 => Some(ipd_mra::IPD_MRA_SD_8.clone()),
                    MraCol::P9 => Some(ipd_mra::IPD_MRA_SD_9.clone()),
                    MraCol::NA | MraCol::S => None,
                },
                Self::So(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_SO.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_SO_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_SO_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_SO_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_SO_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_SO_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_SO_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_SO_7.clone()),
                    MraCol::P8 | MraCol::P9 | MraCol::NA | MraCol::S => None,
                },
                Self::Ic(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_IC.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_IC_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_IC_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_IC_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_IC_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_IC_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_IC_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_IC_7.clone()),
                    MraCol::P8 => Some(ipd_mra::IPD_MRA_IC_8.clone()),
                    MraCol::P9 => Some(ipd_mra::IPD_MRA_IC_9.clone()),
                    MraCol::NA | MraCol::S => None,
                },
                Self::Hx(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_HX.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_HX_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_HX_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_HX_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_HX_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_HX_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_HX_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_HX_7.clone()),
                    MraCol::P8 => Some(ipd_mra::IPD_MRA_HX_8.clone()),
                    MraCol::P9 => Some(ipd_mra::IPD_MRA_HX_9.clone()),
                    MraCol::NA | MraCol::S => None,
                },
                Self::Pe(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_PE.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_PE_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_PE_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_PE_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_PE_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_PE_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_PE_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_PE_7.clone()),
                    MraCol::P8 => Some(ipd_mra::IPD_MRA_PE_8.clone()),
                    MraCol::P9 => Some(ipd_mra::IPD_MRA_PE_9.clone()),
                    MraCol::NA | MraCol::S => None,
                },
                Self::Pn(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_PN.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_PN_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_PN_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_PN_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_PN_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_PN_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_PN_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_PN_7.clone()),
                    MraCol::P8 => Some(ipd_mra::IPD_MRA_PN_8.clone()),
                    MraCol::P9 => Some(ipd_mra::IPD_MRA_PN_9.clone()),
                    MraCol::NA | MraCol::S => None,
                },
                Self::Cr(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_CR.clone()),
                    MraCol::NA => Some(MRA_NA.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_CR_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_CR_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_CR_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_CR_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_CR_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_CR_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_CR_7.clone()),
                    MraCol::P8 => Some(ipd_mra::IPD_MRA_CR_8.clone()),
                    MraCol::P9 => Some(ipd_mra::IPD_MRA_CR_9.clone()),
                    MraCol::S => None,
                },
                Self::Ar(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_AR.clone()),
                    MraCol::NA => Some(MRA_NA.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_AR_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_AR_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_AR_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_AR_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_AR_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_AR_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_AR_7.clone()),
                    MraCol::P8 => Some(ipd_mra::IPD_MRA_AR_8.clone()),
                    MraCol::P9 => Some(ipd_mra::IPD_MRA_AR_9.clone()),
                    MraCol::S => None,
                },
                Self::On(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_ON.clone()),
                    MraCol::NA => Some(MRA_NA.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_ON_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_ON_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_ON_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_ON_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_ON_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_ON_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_ON_7.clone()),
                    MraCol::P8 => Some(ipd_mra::IPD_MRA_ON_8.clone()),
                    MraCol::P9 => Some(ipd_mra::IPD_MRA_ON_9.clone()),
                    MraCol::S => None,
                },
                Self::Lr(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_LR.clone()),
                    MraCol::NA => Some(MRA_NA.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_LR_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_LR_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_LR_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_LR_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_LR_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_LR_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_LR_7.clone()),
                    MraCol::P8 => Some(ipd_mra::IPD_MRA_LR_8.clone()),
                    MraCol::P9 => Some(ipd_mra::IPD_MRA_LR_9.clone()),
                    MraCol::S => None,
                },
                Self::Rr(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_RR.clone()),
                    MraCol::NA => Some(MRA_NA.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_RR_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_RR_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_RR_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_RR_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_RR_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_RR_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_RR_7.clone()),
                    MraCol::P8 => Some(ipd_mra::IPD_MRA_RR_8.clone()),
                    MraCol::P9 => Some(ipd_mra::IPD_MRA_RR_9.clone()),
                    MraCol::S => None,
                },
                Self::Nn(col) => match col {
                    MraCol::La => Some(ipd_mra::IPD_MRA_NN.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra::IPD_MRA_NN_1.clone()),
                    MraCol::P2 => Some(ipd_mra::IPD_MRA_NN_2.clone()),
                    MraCol::P3 => Some(ipd_mra::IPD_MRA_NN_3.clone()),
                    MraCol::P4 => Some(ipd_mra::IPD_MRA_NN_4.clone()),
                    MraCol::P5 => Some(ipd_mra::IPD_MRA_NN_5.clone()),
                    MraCol::P6 => Some(ipd_mra::IPD_MRA_NN_6.clone()),
                    MraCol::P7 => Some(ipd_mra::IPD_MRA_NN_7.clone()),
                    MraCol::P8 => Some(ipd_mra::IPD_MRA_NN_8.clone()),
                    MraCol::P9 => Some(ipd_mra::IPD_MRA_NN_9.clone()),
                    MraCol::S => Some(ipd_mra::IPD_MRA_NN_S.clone()),
                    MraCol::NA => None,
                },
            },
            Mra::IpdPsy => match self {
                Self::Sd(col) => match col {
                    MraCol::La => Some(ipd_mra_psy::IPD_MRA_PSY_SD.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra_psy::IPD_MRA_PSY_SD_1.clone()),
                    MraCol::P2 => Some(ipd_mra_psy::IPD_MRA_PSY_SD_2.clone()),
                    MraCol::P3 => Some(ipd_mra_psy::IPD_MRA_PSY_SD_3.clone()),
                    MraCol::P4 => Some(ipd_mra_psy::IPD_MRA_PSY_SD_4.clone()),
                    MraCol::P5 => Some(ipd_mra_psy::IPD_MRA_PSY_SD_5.clone()),
                    MraCol::P6 => Some(ipd_mra_psy::IPD_MRA_PSY_SD_6.clone()),
                    MraCol::P7 => Some(ipd_mra_psy::IPD_MRA_PSY_SD_7.clone()),
                    MraCol::P8 => Some(ipd_mra_psy::IPD_MRA_PSY_SD_8.clone()),
                    MraCol::P9 => Some(ipd_mra_psy::IPD_MRA_PSY_SD_9.clone()),
                    MraCol::NA | MraCol::S => None,
                },
                Self::So(col) => match col {
                    MraCol::La => Some(ipd_mra_psy::IPD_MRA_PSY_SO.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra_psy::IPD_MRA_PSY_SO_1.clone()),
                    MraCol::P2 => Some(ipd_mra_psy::IPD_MRA_PSY_SO_2.clone()),
                    MraCol::P3 => Some(ipd_mra_psy::IPD_MRA_PSY_SO_3.clone()),
                    MraCol::P4 => Some(ipd_mra_psy::IPD_MRA_PSY_SO_4.clone()),
                    MraCol::P5 => Some(ipd_mra_psy::IPD_MRA_PSY_SO_5.clone()),
                    MraCol::P6 => Some(ipd_mra_psy::IPD_MRA_PSY_SO_6.clone()),
                    MraCol::P7 => Some(ipd_mra_psy::IPD_MRA_PSY_SO_7.clone()),
                    MraCol::P8 | MraCol::P9 | MraCol::NA | MraCol::S => None,
                },
                Self::Ic(col) => match col {
                    MraCol::La => Some(ipd_mra_psy::IPD_MRA_PSY_IC.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra_psy::IPD_MRA_PSY_IC_1.clone()),
                    MraCol::P2 => Some(ipd_mra_psy::IPD_MRA_PSY_IC_2.clone()),
                    MraCol::P3 => Some(ipd_mra_psy::IPD_MRA_PSY_IC_3.clone()),
                    MraCol::P4 => Some(ipd_mra_psy::IPD_MRA_PSY_IC_4.clone()),
                    MraCol::P5 => Some(ipd_mra_psy::IPD_MRA_PSY_IC_5.clone()),
                    MraCol::P6 => Some(ipd_mra_psy::IPD_MRA_PSY_IC_6.clone()),
                    MraCol::P7 => Some(ipd_mra_psy::IPD_MRA_PSY_IC_7.clone()),
                    MraCol::P8 => Some(ipd_mra_psy::IPD_MRA_PSY_IC_8.clone()),
                    MraCol::P9 => Some(ipd_mra_psy::IPD_MRA_PSY_IC_9.clone()),
                    MraCol::NA | MraCol::S => None,
                },
                Self::Hx(col) => match col {
                    MraCol::La => Some(ipd_mra_psy::IPD_MRA_PSY_HX.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra_psy::IPD_MRA_PSY_HX_1.clone()),
                    MraCol::P2 => Some(ipd_mra_psy::IPD_MRA_PSY_HX_2.clone()),
                    MraCol::P3 => Some(ipd_mra_psy::IPD_MRA_PSY_HX_3.clone()),
                    MraCol::P4 => Some(ipd_mra_psy::IPD_MRA_PSY_HX_4.clone()),
                    MraCol::P5 => Some(ipd_mra_psy::IPD_MRA_PSY_HX_5.clone()),
                    MraCol::P6 => Some(ipd_mra_psy::IPD_MRA_PSY_HX_6.clone()),
                    MraCol::P7 => Some(ipd_mra_psy::IPD_MRA_PSY_HX_7.clone()),
                    MraCol::P8 => Some(ipd_mra_psy::IPD_MRA_PSY_HX_8.clone()),
                    MraCol::P9 => Some(ipd_mra_psy::IPD_MRA_PSY_HX_9.clone()),
                    MraCol::NA | MraCol::S => None,
                },
                Self::Pe(col) => match col {
                    MraCol::La => Some(ipd_mra_psy::IPD_MRA_PSY_PE.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra_psy::IPD_MRA_PSY_PE_1.clone()),
                    MraCol::P2 => Some(ipd_mra_psy::IPD_MRA_PSY_PE_2.clone()),
                    MraCol::P3 => Some(ipd_mra_psy::IPD_MRA_PSY_PE_3.clone()),
                    MraCol::P4 => Some(ipd_mra_psy::IPD_MRA_PSY_PE_4.clone()),
                    MraCol::P5 => Some(ipd_mra_psy::IPD_MRA_PSY_PE_5.clone()),
                    MraCol::P6 => Some(ipd_mra_psy::IPD_MRA_PSY_PE_6.clone()),
                    MraCol::P7 => Some(ipd_mra_psy::IPD_MRA_PSY_PE_7.clone()),
                    MraCol::P8 => Some(ipd_mra_psy::IPD_MRA_PSY_PE_8.clone()),
                    MraCol::P9 => Some(ipd_mra_psy::IPD_MRA_PSY_PE_9.clone()),
                    MraCol::NA | MraCol::S => None,
                },
                Self::Pn(col) => match col {
                    MraCol::La => Some(ipd_mra_psy::IPD_MRA_PSY_PN.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra_psy::IPD_MRA_PSY_PN_1.clone()),
                    MraCol::P2 => Some(ipd_mra_psy::IPD_MRA_PSY_PN_2.clone()),
                    MraCol::P3 => Some(ipd_mra_psy::IPD_MRA_PSY_PN_3.clone()),
                    MraCol::P4 => Some(ipd_mra_psy::IPD_MRA_PSY_PN_4.clone()),
                    MraCol::P5 => Some(ipd_mra_psy::IPD_MRA_PSY_PN_5.clone()),
                    MraCol::P6 => Some(ipd_mra_psy::IPD_MRA_PSY_PN_6.clone()),
                    MraCol::P7 => Some(ipd_mra_psy::IPD_MRA_PSY_PN_7.clone()),
                    MraCol::P8 => Some(ipd_mra_psy::IPD_MRA_PSY_PN_8.clone()),
                    MraCol::P9 => Some(ipd_mra_psy::IPD_MRA_PSY_PN_9.clone()),
                    MraCol::NA | MraCol::S => None,
                },
                Self::Cr(col) => match col {
                    MraCol::La => Some(ipd_mra_psy::IPD_MRA_PSY_CR.clone()),
                    MraCol::NA => Some(MRA_NA.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra_psy::IPD_MRA_PSY_CR_1.clone()),
                    MraCol::P2 => Some(ipd_mra_psy::IPD_MRA_PSY_CR_2.clone()),
                    MraCol::P3 => Some(ipd_mra_psy::IPD_MRA_PSY_CR_3.clone()),
                    MraCol::P4 => Some(ipd_mra_psy::IPD_MRA_PSY_CR_4.clone()),
                    MraCol::P5 => Some(ipd_mra_psy::IPD_MRA_PSY_CR_5.clone()),
                    MraCol::P6 => Some(ipd_mra_psy::IPD_MRA_PSY_CR_6.clone()),
                    MraCol::P7 => Some(ipd_mra_psy::IPD_MRA_PSY_CR_7.clone()),
                    MraCol::P8 => Some(ipd_mra_psy::IPD_MRA_PSY_CR_8.clone()),
                    MraCol::P9 => Some(ipd_mra_psy::IPD_MRA_PSY_CR_9.clone()),
                    MraCol::S => None,
                },
                Self::Ar(col) => match col {
                    MraCol::La => Some(ipd_mra_psy::IPD_MRA_PSY_AR.clone()),
                    MraCol::NA => Some(MRA_NA.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra_psy::IPD_MRA_PSY_AR_1.clone()),
                    MraCol::P2 => Some(ipd_mra_psy::IPD_MRA_PSY_AR_2.clone()),
                    MraCol::P3 => Some(ipd_mra_psy::IPD_MRA_PSY_AR_3.clone()),
                    MraCol::P4 => Some(ipd_mra_psy::IPD_MRA_PSY_AR_4.clone()),
                    MraCol::P5 => Some(ipd_mra_psy::IPD_MRA_PSY_AR_5.clone()),
                    MraCol::P6 => Some(ipd_mra_psy::IPD_MRA_PSY_AR_6.clone()),
                    MraCol::P7 => Some(ipd_mra_psy::IPD_MRA_PSY_AR_7.clone()),
                    MraCol::P8 => Some(ipd_mra_psy::IPD_MRA_PSY_AR_8.clone()),
                    MraCol::P9 => Some(ipd_mra_psy::IPD_MRA_PSY_AR_9.clone()),
                    MraCol::S => None,
                },
                Self::On(col) => match col {
                    MraCol::La => Some(ipd_mra_psy::IPD_MRA_PSY_ON.clone()),
                    MraCol::NA => Some(MRA_NA.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra_psy::IPD_MRA_PSY_ON_1.clone()),
                    MraCol::P2 => Some(ipd_mra_psy::IPD_MRA_PSY_ON_2.clone()),
                    MraCol::P3 => Some(ipd_mra_psy::IPD_MRA_PSY_ON_3.clone()),
                    MraCol::P4 => Some(ipd_mra_psy::IPD_MRA_PSY_ON_4.clone()),
                    MraCol::P5 => Some(ipd_mra_psy::IPD_MRA_PSY_ON_5.clone()),
                    MraCol::P6 => Some(ipd_mra_psy::IPD_MRA_PSY_ON_6.clone()),
                    MraCol::P7 => Some(ipd_mra_psy::IPD_MRA_PSY_ON_7.clone()),
                    MraCol::P8 => Some(ipd_mra_psy::IPD_MRA_PSY_ON_8.clone()),
                    MraCol::P9 => Some(ipd_mra_psy::IPD_MRA_PSY_ON_9.clone()),
                    MraCol::S => None,
                },
                Self::Lr(_) => None,
                Self::Rr(col) => match col {
                    MraCol::La => Some(ipd_mra_psy::IPD_MRA_PSY_RR.clone()),
                    MraCol::NA => Some(MRA_NA.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra_psy::IPD_MRA_PSY_RR_1.clone()),
                    MraCol::P2 => Some(ipd_mra_psy::IPD_MRA_PSY_RR_2.clone()),
                    MraCol::P3 => Some(ipd_mra_psy::IPD_MRA_PSY_RR_3.clone()),
                    MraCol::P4 => Some(ipd_mra_psy::IPD_MRA_PSY_RR_4.clone()),
                    MraCol::P5 => Some(ipd_mra_psy::IPD_MRA_PSY_RR_5.clone()),
                    MraCol::P6 => Some(ipd_mra_psy::IPD_MRA_PSY_RR_6.clone()),
                    MraCol::P7 => Some(ipd_mra_psy::IPD_MRA_PSY_RR_7.clone()),
                    MraCol::P8 => Some(ipd_mra_psy::IPD_MRA_PSY_RR_8.clone()),
                    MraCol::P9 => Some(ipd_mra_psy::IPD_MRA_PSY_RR_9.clone()),
                    MraCol::S => None,
                },
                Self::Nn(col) => match col {
                    MraCol::La => Some(ipd_mra_psy::IPD_MRA_PSY_NN.clone()),
                    MraCol::M => Some(MRA_MISSING.clone()),
                    MraCol::N => Some(MRA_NO.clone()),
                    MraCol::P1 => Some(ipd_mra_psy::IPD_MRA_PSY_NN_1.clone()),
                    MraCol::P2 => Some(ipd_mra_psy::IPD_MRA_PSY_NN_2.clone()),
                    MraCol::P3 => Some(ipd_mra_psy::IPD_MRA_PSY_NN_3.clone()),
                    MraCol::P4 => Some(ipd_mra_psy::IPD_MRA_PSY_NN_4.clone()),
                    MraCol::P5 => Some(ipd_mra_psy::IPD_MRA_PSY_NN_5.clone()),
                    MraCol::P6 => Some(ipd_mra_psy::IPD_MRA_PSY_NN_6.clone()),
                    MraCol::P7 => Some(ipd_mra_psy::IPD_MRA_PSY_NN_7.clone()),
                    MraCol::P8 => Some(ipd_mra_psy::IPD_MRA_PSY_NN_8.clone()),
                    MraCol::P9 => Some(ipd_mra_psy::IPD_MRA_PSY_NN_9.clone()),
                    MraCol::S => Some(ipd_mra_psy::IPD_MRA_PSY_NN_S.clone()),
                    MraCol::NA => None,
                },
            },
        }
    }
}

#[derive(Clone, PartialEq)]
pub enum MraCol {
    La,
    NA,
    M,
    N,
    P1,
    P2,
    P3,
    P4,
    P5,
    P6,
    P7,
    P8,
    P9,
    S,
}

pub enum Mra {
    Ipd,
    IpdPsy,
}
