CREATE TABLE `kphis`.`ipd_dr_consult` (
  `consult_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `consult_type` INT(11) UNSIGNED DEFAULT NULL,
  `consult_ward` VARCHAR(2) DEFAULT NULL,
  `consult_emergency` VARCHAR(1) DEFAULT NULL,
  `consult_spclty` VARCHAR(2) DEFAULT NULL,
  `consult_doctorcode_mention` VARCHAR(7) DEFAULT NULL,
  `consult_date` DATE DEFAULT NULL,
  `consult_time` TIME DEFAULT NULL,
  `consult_data` TEXT DEFAULT NULL,
  `consult_datetime_create_reply` DATETIME DEFAULT NULL,
  `consult_datetime_update_reply` DATETIME DEFAULT NULL,
  `consult_finding` TEXT DEFAULT NULL,
  `consult_diagnosis` TEXT DEFAULT NULL,
  `consult_recommendation` TEXT DEFAULT NULL,
  `consult_status` VARCHAR(1) DEFAULT NULL,
  `an` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `update_datetime` DATETIME DEFAULT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`consult_id`) USING BTREE,
  INDEX `an` (`an`) USING BTREE,
  INDEX `consult_date` (`consult_date`) USING BTREE,
  INDEX `consult_spclty` (`consult_spclty`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;