CREATE TABLE `kphis`.`ipd_vs_cha` (
  `cha_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cha_name` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`cha_id`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;