CREATE TABLE `kphis`.`ipd_summary_2` (
  `summary_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `principal_diagnosis` TEXT DEFAULT NULL,
  `principal_diagnosis_icd10` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `operating_room` TEXT DEFAULT NULL,
  `tracheostomy` VARCHAR(1) DEFAULT NULL,
  `mechanical_ventilation` VARCHAR(1) DEFAULT NULL,
  `packed_redcells` VARCHAR(1) DEFAULT NULL,
  `fresh_frozen_plasma` VARCHAR(1) DEFAULT NULL,
  `platelets` VARCHAR(1) DEFAULT NULL,
  `cryoprecipitate` VARCHAR(1) DEFAULT NULL,
  `whole_blood` VARCHAR(1) DEFAULT NULL,
  `computer_tomography` VARCHAR(1) DEFAULT NULL,
  `computer_tomography_text` TEXT DEFAULT NULL,
  `chemotherapy` VARCHAR(1) DEFAULT NULL,
  `mri` VARCHAR(1) DEFAULT NULL,
  `mri_text` TEXT DEFAULT NULL,
  `hemodialysis` VARCHAR(1) DEFAULT NULL,
  `non_or_other` VARCHAR(1) DEFAULT NULL,
  `non_or_other_text` TEXT DEFAULT NULL,
  `special_other` VARCHAR(1) DEFAULT NULL,
  `special_other_text` TEXT DEFAULT NULL,
  `discharge_status` VARCHAR(2) DEFAULT NULL,
  `discharge_type` VARCHAR(2) DEFAULT NULL,
  `hospital_refer` VARCHAR(9) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `coder_name` VARCHAR(50) DEFAULT NULL,
  `principal_diagnosis_code` VARCHAR(7) DEFAULT NULL,
  `pre_admission_comorbidity_codes` TEXT DEFAULT NULL,
  `post_admission_comorbidity_codes` TEXT DEFAULT NULL,
  `other_diagnosis_codes` TEXT DEFAULT NULL,
  `external_cause_codes` TEXT DEFAULT NULL,
  `main_procedure_code` VARCHAR(7) DEFAULT NULL,
  `other_procedure_codes` TEXT DEFAULT NULL,
  `status` VARCHAR(7) DEFAULT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `update_datetime` DATETIME NOT NULL,
  `version` INT(11) NOT NULL,
  `summary_doctor_code` VARCHAR(7) DEFAULT NULL,
  PRIMARY KEY (`summary_id`) USING BTREE,
  UNIQUE INDEX `an` (`an`) USING BTREE,
  INDEX `status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;