CREATE TABLE `kphis`.`ipd_focus_note` (
  `fcnote_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `general_symptoms` TEXT DEFAULT NULL,
  `fclist_id` INT(11) UNSIGNED DEFAULT NULL,
  `assessment` TEXT DEFAULT NULL,
  `intvt_id` TEXT DEFAULT NULL,
  `intvt_text` TEXT DEFAULT NULL,
  `evalution` TEXT DEFAULT NULL,
  `dlc_id` TEXT DEFAULT NULL,
  `dlc_text` TEXT DEFAULT NULL,
  `other` TEXT DEFAULT NULL,
  `an` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `hn` VARCHAR(10) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `fcnote_date` DATE DEFAULT NULL,
  `fcnote_time` TIME DEFAULT NULL,
  `fcnote_patient_type` VARCHAR(2) DEFAULT NULL,
  `ward` VARCHAR(4) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `create_datetime` DATETIME DEFAULT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `update_datetime` DATETIME DEFAULT NULL,
  `version` INT(11) DEFAULT NULL,
  PRIMARY KEY (`fcnote_id`) USING BTREE,
  INDEX `an` (`an`) USING BTREE,
  INDEX `fclist_id` (`fclist_id`) USING BTREE,
  INDEX `fcnote_date` (`fcnote_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;