CREATE TABLE `kphis`.`ipd_io` (
  `io_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `io_date` DATE NOT NULL,
  `io_time` TIME NOT NULL,
  `io_parenteral_type` VARCHAR(50) DEFAULT NULL,
  `io_parenteral_name` VARCHAR(200) DEFAULT NULL,
  `io_parenteral_amount` DECIMAL(6,1) DEFAULT NULL,
  `io_parenteral_absorb` DECIMAL(6,1) DEFAULT NULL,
  `io_parenteral_carry_forward` DECIMAL(6,1) DEFAULT NULL,
  `io_parenteral_remark` TEXT DEFAULT NULL,
  `io_oral_name` VARCHAR(200) DEFAULT NULL,
  `io_oral_amount` INT(11) DEFAULT NULL,
  `io_oral_absorb` INT(11) DEFAULT NULL,
  `io_oral_carry_forward` INT(11) DEFAULT NULL,
  `io_oral_remark` TEXT DEFAULT NULL,
  `io_output_type` VARCHAR(50) DEFAULT NULL,
  `io_output_amount` INT(11) DEFAULT NULL,
  `io_output_remark` TEXT DEFAULT NULL,
  `an` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `update_datetime` DATETIME DEFAULT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`io_id`) USING BTREE,
  INDEX `an` (`an`) USING BTREE,
  INDEX `io_date` (`io_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;