CREATE TABLE `kphis`.`ipd_vs_lr_mem` (
  `lr_mem_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `lr_mem_name` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`lr_mem_id`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;