CREATE TABLE `kphis`.`ipd_progress_note` (
  `progress_note_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `an` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `progress_note_date` DATE NOT NULL,
  `progress_note_time` TIME NOT NULL,
  `progress_note_owner_type` VARCHAR(20) NOT NULL COMMENT 'doctor, nurse, pharmacist',
  `progress_note_doctor` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `progress_note_enter_datetime` DATETIME DEFAULT NULL,
  `pre_order_progress_note_id` INT(11) UNSIGNED DEFAULT NULL,
  `pre_order_progress_note_date` DATE DEFAULT NULL,
  `pre_order_progress_note_time` TIME DEFAULT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `update_datetime` DATETIME NOT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`progress_note_id`) USING BTREE,
  INDEX `an` (`an`) USING BTREE,
  INDEX `progress_note_date` (`progress_note_date`) USING BTREE,
  INDEX `an_progress_note_date` (`an`,`progress_note_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;