CREATE TABLE `kphis`.`ipd_dr_admission_note` (
  `admission_note_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `hn` VARCHAR(9) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `an` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `receiver_medication_date` DATE DEFAULT NULL,
  `receiver_medication_time` TIME DEFAULT NULL,
  `take_medication_by` VARCHAR(40) DEFAULT NULL,
  `arrive_by` VARCHAR(40) DEFAULT NULL,
  `taken_by_relative` VARCHAR(10) DEFAULT NULL,
  `taken_by_nurse` VARCHAR(10) DEFAULT NULL,
  `taken_by_crib` VARCHAR(10) DEFAULT NULL,
  `taken_by_etc` VARCHAR(40) DEFAULT NULL,
  `taken_by` VARCHAR(40) DEFAULT NULL,
  `informant_patient` VARCHAR(40) DEFAULT NULL,
  `informant_relatives` VARCHAR(40) DEFAULT NULL,
  `informant_deliverer` VARCHAR(40) DEFAULT NULL,
  `informant_etc` VARCHAR(40) DEFAULT NULL,
  `chief_complaints` TEXT DEFAULT NULL,
  `medical_history` TEXT DEFAULT NULL,
  `bp` VARCHAR(10) DEFAULT NULL,
  `t` DECIMAL(3,1) UNSIGNED DEFAULT NULL,
  `pr` INT(5) UNSIGNED DEFAULT NULL,
  `rr` INT(5) DEFAULT NULL,
  `gcs` INT(5) DEFAULT NULL,
  `e` VARCHAR(1) DEFAULT NULL,
  `v` VARCHAR(1) DEFAULT NULL,
  `m` VARCHAR(1) DEFAULT NULL,
  `braden_scale` TEXT DEFAULT NULL,
  `disease` VARCHAR(20) DEFAULT NULL,
  `disease_detail` TEXT DEFAULT NULL,
  `disease_etc` TEXT DEFAULT NULL,
  `last_dose_taken_time` DATETIME DEFAULT NULL,
  `last_dose_taken_remark` TEXT DEFAULT NULL,
  `operation_history` TEXT DEFAULT NULL,
  `allergy_history` VARCHAR(20) DEFAULT NULL,
  `allergy_drug_history` TEXT DEFAULT NULL,
  `allergy_drug_history_hosxp` TEXT DEFAULT NULL,
  `allergy_drug_pharmacy_check_person` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `allergy_drug_pharmacy_check_datetime` DATETIME DEFAULT NULL,
  `allergy_food_history` TEXT DEFAULT NULL,
  `allergy_etc_history` TEXT DEFAULT NULL,
  `allergy_detail` TEXT DEFAULT NULL,
  `family_medical_history` TEXT DEFAULT NULL,
  `family_medical_history_detail` TEXT DEFAULT NULL,
  `receives_immunisation_history_kid` VARCHAR(40) DEFAULT NULL,
  `developmentally_kid` VARCHAR(40) DEFAULT NULL,
  `g` INT(2) DEFAULT NULL,
  `p` VARCHAR(50) DEFAULT NULL,
  `anc` VARCHAR(200) DEFAULT NULL,
  `tt` INT(2) DEFAULT NULL,
  `gestational_age` VARCHAR(10) DEFAULT NULL,
  `gestational_day` VARCHAR(10) DEFAULT NULL,
  `last_child` INT(2) DEFAULT NULL,
  `last_abort` VARCHAR(50) DEFAULT NULL,
  `curette` VARCHAR(1) DEFAULT NULL,
  `lmp` DATE DEFAULT NULL,
  `edc` DATE DEFAULT NULL,
  `pb_no` VARCHAR(1) DEFAULT NULL,
  `giant_baby` VARCHAR(1) DEFAULT NULL,
  `distocia` VARCHAR(1) DEFAULT NULL,
  `extraction` VARCHAR(200) DEFAULT NULL,
  `pph` VARCHAR(1) DEFAULT NULL,
  `pb_etc` VARCHAR(200) DEFAULT NULL,
  `hf` INT(2) DEFAULT NULL,
  `hf_position` VARCHAR(200) DEFAULT NULL,
  `hiv` VARCHAR(10) DEFAULT NULL,
  `vdrl` VARCHAR(20) DEFAULT NULL,
  `hbs_ag` VARCHAR(20) DEFAULT NULL,
  `hct` DECIMAL(3,1) DEFAULT NULL,
  `hiv2` VARCHAR(10) DEFAULT NULL,
  `vdrl2` VARCHAR(20) DEFAULT NULL,
  `hbs_ag2` VARCHAR(20) DEFAULT NULL,
  `hct2` DECIMAL(3,1) DEFAULT NULL,
  `gr` VARCHAR(200) DEFAULT NULL,
  `thalassemia` VARCHAR(200) DEFAULT NULL,
  `husband` VARCHAR(200) DEFAULT NULL,
  `condition_pregnant` TEXT DEFAULT NULL,
  `deliver_anomalies` VARCHAR(40) DEFAULT NULL,
  `deliver_anomalies_means` VARCHAR(50) DEFAULT NULL,
  `deliver_location` VARCHAR(50) DEFAULT NULL,
  `deliver_first_weight` DECIMAL(5,0) DEFAULT NULL,
  `deliver_first_health` VARCHAR(40) DEFAULT NULL,
  `fant_breast_feeding_end_age_month` INT(3) DEFAULT NULL,
  `fant_artificial_feeding_start_age_month` INT(3) DEFAULT NULL,
  `fant_feeding_etc` VARCHAR(40) DEFAULT NULL,
  `supplementary_feeding` VARCHAR(20) DEFAULT NULL,
  `supplementary_feeding_start_age_month` INT(3) DEFAULT NULL,
  `disease_operation_allergy` TEXT DEFAULT NULL,
  `inpatient_history` VARCHAR(10) DEFAULT NULL,
  `inpatient_last_date` VARCHAR(40) DEFAULT NULL,
  `inpatient_location` VARCHAR(200) DEFAULT NULL,
  `inpatient_because` VARCHAR(200) DEFAULT NULL,
  `pe_general` VARCHAR(200) DEFAULT NULL,
  `pe_skin` VARCHAR(200) DEFAULT NULL,
  `pe_heent` VARCHAR(200) DEFAULT NULL,
  `pe_neck` VARCHAR(200) DEFAULT NULL,
  `pe_breastthorax` VARCHAR(200) DEFAULT NULL,
  `pe_heart` VARCHAR(200) DEFAULT NULL,
  `pe_lungs` VARCHAR(200) DEFAULT NULL,
  `pe_abdomen` VARCHAR(200) DEFAULT NULL,
  `pe_rectalgenitalia` VARCHAR(200) DEFAULT NULL,
  `pe_extremities` VARCHAR(200) DEFAULT NULL,
  `pe_neurological` VARCHAR(200) DEFAULT NULL,
  `pe_ob_gynexam` VARCHAR(200) DEFAULT NULL,
  `pe_other` VARCHAR(200) DEFAULT NULL,
  `pe_text` TEXT DEFAULT NULL,
  `svg_tag` TEXT DEFAULT NULL,
  `impression` VARCHAR(150) DEFAULT NULL,
  `diff_dx` VARCHAR(150) DEFAULT NULL,
  `plan_management` VARCHAR(150) DEFAULT NULL,
  `nurse_name` VARCHAR(150) DEFAULT NULL,
  `nurse_pos` VARCHAR(150) DEFAULT NULL,
  `nurse_licenseno` VARCHAR(150) DEFAULT NULL,
  `doc_name` VARCHAR(150) DEFAULT NULL,
  `doc_pos` VARCHAR(150) DEFAULT NULL,
  `mem_ruptured_hours` SMALLINT(5) UNSIGNED DEFAULT NULL,
  `lr_back_fetus` VARCHAR(20) DEFAULT NULL,
  `lr_presentation` VARCHAR(20) DEFAULT NULL,
  `lr_engagement` VARCHAR(1) DEFAULT NULL,
  `lr_prominence` VARCHAR(20) DEFAULT NULL,
  `lr_attitude` VARCHAR(20) DEFAULT NULL,
  `lr_fhr` SMALLINT(5) UNSIGNED DEFAULT NULL,
  `lr_fhr_irrigular` VARCHAR(1) DEFAULT NULL,
  `lr_efw` SMALLINT(5) UNSIGNED DEFAULT NULL,
  `lr_interval` VARCHAR(20) DEFAULT NULL,
  `lr_duration` TINYINT(3) UNSIGNED DEFAULT NULL,
  `lr_intensity` VARCHAR(20) DEFAULT NULL,
  `lr_pelvic_diagonal` Decimal(3,1) DEFAULT NULL,
  `lr_pelvic_interspinous` Decimal(3,1) DEFAULT NULL,
  `lr_pelvic_sidewall` VARCHAR(20) DEFAULT NULL,
  `lr_ischeal_spine` VARCHAR(20) DEFAULT NULL,
  `lr_sacral_curve` VARCHAR(20) DEFAULT NULL,
  `lr_pubic_angle` TINYINT(3) UNSIGNED DEFAULT NULL,
  `lr_pelvic_ok` VARCHAR(1) DEFAULT NULL,
  `lr_cx_dilate` TINYINT(3) UNSIGNED DEFAULT NULL,
  `lr_cx_efface` TINYINT(3) UNSIGNED DEFAULT NULL,
  `lr_cx_station` TINYINT(3) DEFAULT NULL,
  `lr_cx_position` VARCHAR(20) DEFAULT NULL,
  `lr_cx_consistency` VARCHAR(20) DEFAULT NULL,
  `lr_cx_bishop` TINYINT(3) UNSIGNED DEFAULT NULL,
  `lr_cx_ok` VARCHAR(1) DEFAULT NULL,
  `lr_membrane` VARCHAR(20) DEFAULT NULL,
  `lr_amniotic_color` VARCHAR(10) DEFAULT NULL,
  `lr_amniotic_smell` VARCHAR(10) DEFAULT NULL,
  `ros_eent` VARCHAR(200) DEFAULT NULL,
  `ros_neuro` VARCHAR(200) DEFAULT NULL,
  `ros_lung` VARCHAR(200) DEFAULT NULL,
  `ros_tb` VARCHAR(200) DEFAULT NULL,
  `ros_ht` VARCHAR(200) DEFAULT NULL,
  `ros_heart` VARCHAR(200) DEFAULT NULL,
  `ros_liver` VARCHAR(200) DEFAULT NULL,
  `ros_gi` VARCHAR(200) DEFAULT NULL,
  `ros_endocrine` VARCHAR(200) DEFAULT NULL,
  `ros_kidney` VARCHAR(200) DEFAULT NULL,
  `ros_tumour` VARCHAR(200) DEFAULT NULL,
  `ros_hemato` VARCHAR(200) DEFAULT NULL,
  `ros_rheumato` VARCHAR(200) DEFAULT NULL,
  `ros_psychia` VARCHAR(200) DEFAULT NULL,
  `ros_other` VARCHAR(200) DEFAULT NULL,
  `addict` VARCHAR(20) DEFAULT NULL,
  `addict_assist` TEXT DEFAULT NULL,
  `addict_inj` VARCHAR(1) DEFAULT NULL,
  `addict_inj_often` VARCHAR(1) DEFAULT NULL,
  `amphetamine_awq` TEXT DEFAULT NULL,
  `aggression_oas` TEXT DEFAULT NULL,
  `motivation_scale` TINYINT(2) UNSIGNED DEFAULT NULL,
  `craving_scale` TINYINT(2) UNSIGNED DEFAULT NULL,
  `stage_of_change_id` INT(11) UNSIGNED DEFAULT NULL,
  `alcohol_audit` TEXT DEFAULT NULL,
  `alcohol_aws` TEXT DEFAULT NULL,
  `alcohol_ciwa` TEXT DEFAULT NULL,
  `depress_2q` TEXT DEFAULT NULL,
  `depress_9q` TEXT DEFAULT NULL,
  `depress_cdi` TEXT DEFAULT NULL,
  `depress_cesd` TEXT DEFAULT NULL,
  `depress_phqa` TEXT DEFAULT NULL,
  `nicotin_ftnd` TEXT DEFAULT NULL,
  `ptsd_screen` TEXT DEFAULT NULL,
  `ptsd_pisces` TEXT DEFAULT NULL,
  `ptsd_cries` TEXT DEFAULT NULL,
  `suicide_8q` TEXT DEFAULT NULL,
  `stress_st5` TEXT DEFAULT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `update_datetime` DATETIME NOT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`admission_note_id`) USING BTREE,
  UNIQUE INDEX `in_an` (`an`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;