CREATE TABLE `kphis`.`ipd_summary` (
  `summary_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `summary_plan_date` DATE NOT NULL,
  `summary_plan_time` TIME NOT NULL,
  `principal_diagnosis` TEXT DEFAULT NULL,
  `pre_admission_comorbidity` TEXT DEFAULT NULL,
  `post_admission_comorbidity` TEXT DEFAULT NULL,
  `other_diagnosis` TEXT DEFAULT NULL,
  `external_cause` TEXT DEFAULT NULL,
  `operating_room` TEXT DEFAULT NULL,
  `tracheostomy` VARCHAR(1) DEFAULT NULL,
  `mechanical_ventilation` VARCHAR(1) DEFAULT NULL,
  `mechanical_ventilation1` VARCHAR(1) DEFAULT NULL,
  `mechanical_ventilation2` VARCHAR(1) DEFAULT NULL,
  `packed_redcells` VARCHAR(1) DEFAULT NULL,
  `fresh_frozen_plasma` VARCHAR(1) DEFAULT NULL,
  `platelets` VARCHAR(1) DEFAULT NULL,
  `cryoprecipitate` VARCHAR(1) DEFAULT NULL,
  `whole_blood` VARCHAR(1) DEFAULT NULL,
  `computer_tomography` VARCHAR(1) DEFAULT NULL,
  `computer_tomography_text` VARCHAR(255) DEFAULT NULL,
  `chemotherapy` VARCHAR(1) DEFAULT NULL,
  `mri` VARCHAR(1) DEFAULT NULL,
  `hemodialysis` VARCHAR(1) DEFAULT NULL,
  `non_or_other` VARCHAR(1) DEFAULT NULL,
  `non_or_other_text` VARCHAR(255) DEFAULT NULL,
  `discharge_status` VARCHAR(2) DEFAULT NULL,
  `discharge_type` VARCHAR(2) DEFAULT NULL,
  `hospital_refer` VARCHAR(500) DEFAULT NULL,
  `hn` VARCHAR(9) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `an` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `update_datetime` DATETIME NOT NULL,
  `version` INT(11) NOT NULL,
  `summary_doctor_code` VARCHAR(7) DEFAULT NULL,
  PRIMARY KEY (`summary_id`) USING BTREE,
  UNIQUE INDEX `an` (`an`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;