CREATE TABLE `kphis`.`kphis_drug_use_duration` (
  `icode` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `usage` TEXT DEFAULT NULL,
  `duration1` SMALLINT(6) DEFAULT NULL,
  `exceed_duration1_color` VARCHAR(20) DEFAULT NULL,
  `duration2` SMALLINT(6) DEFAULT NULL,
  `exceed_duration2_color` VARCHAR(20) DEFAULT NULL,
  `duration3` SMALLINT(6) DEFAULT NULL,
  `exceed_duration3_color` VARCHAR(20) DEFAULT NULL,
  `status` VARCHAR(1) DEFAULT NULL,
  `monitor` TEXT DEFAULT NULL,
  `monitor_count` TINYINT(3) UNSIGNED DEFAULT NULL,
  `monitor_duration` INT(11) UNSIGNED DEFAULT NULL,
  `monitor_status` VARCHAR(1) DEFAULT NULL,
  `info` TEXT DEFAULT NULL,
  `info_status` VARCHAR(1) DEFAULT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `update_datetime` DATETIME NOT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`icode`) USING BTREE,
  INDEX `status` (`status`) USING BTREE,
  INDEX `monitor_status` (`monitor_status`) USING BTREE,
  INDEX `info_status` (`info_status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;