CREATE TABLE `kphis`.`opd_er_order_item` (
  `order_item_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `opd_er_order_master_id` INT(11) UNSIGNED NOT NULL,
  `order_id` INT(11) UNSIGNED DEFAULT NULL,
  `order_item_type` VARCHAR(20) DEFAULT NULL,
  `order_item_detail` TEXT DEFAULT NULL,
  `stat` VARCHAR(1) DEFAULT NULL,
  `off_order_item_id` INT(11) UNSIGNED DEFAULT NULL,
  `icode` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `med_reconciliation_item_id` INT(11) UNSIGNED DEFAULT NULL,
  `nurse_assign` VARCHAR(20) DEFAULT NULL,
	`first_qty` INT(11) NULL DEFAULT NULL,
	`qty` INT(11) NULL DEFAULT NULL,
  `due_doctor` VARCHAR(1) DEFAULT NULL,
  `due_doctor_note` TEXT DEFAULT NULL,
  `due_pharm` VARCHAR(1) DEFAULT NULL,
  `due_pharm_note` TEXT DEFAULT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `update_datetime` DATETIME NOT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`order_item_id`) USING BTREE,
  INDEX `order_id` (`order_id`) USING BTREE,
  INDEX `opd_er_order_master_id` (`opd_er_order_master_id`) USING BTREE,
  INDEX `off_order_item_id` (`off_order_item_id`) USING BTREE,
  INDEX `order_id_order_item_type` (`order_id`,`order_item_type`) USING BTREE,
  INDEX `stat` (`stat`) USING BTREE,
  INDEX `opd_er_order_master_id_off_order_item_id` (`opd_er_order_master_id`,`off_order_item_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;