CREATE TABLE `kphis`.`opd_er_order` (
  `order_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `opd_er_order_master_id` INT(11) UNSIGNED NOT NULL,
  `order_date` DATE NOT NULL,
  `order_time` TIME NOT NULL,
  `order_doctor` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `order_type` VARCHAR(20) NOT NULL COMMENT 'oneday, continuous',
  `order_owner_type` VARCHAR(20) NOT NULL COMMENT 'doctor, nurse, pharmacist',
  `order_confirm` VARCHAR(1) NOT NULL,
  `nurse_order_as` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `doctor_confirm_time` DATETIME DEFAULT NULL,
  `nurse_accept` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `nurse_accept_time` DATETIME DEFAULT NULL,
  `pharmacist_accept` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `pharmacist_accept_time` DATETIME DEFAULT NULL,
  `pharmacist_check` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `pharmacist_check_time` DATETIME DEFAULT NULL,
  `pharmacist_done` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `pharmacist_done_time` DATETIME DEFAULT NULL,
  `pharmacist_order_status` VARCHAR(20) DEFAULT NULL,
  `pre_order_id` INT(11) UNSIGNED DEFAULT NULL,
  `pre_order_date` DATE DEFAULT NULL,
  `pre_order_time` TIME DEFAULT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `update_datetime` DATETIME NOT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`order_id`) USING BTREE,
  INDEX `order_date` (`order_date`) USING BTREE,
  INDEX `opd_er_order_master_id` (`opd_er_order_master_id`) USING BTREE,
  INDEX `opd_er_order_master_id_order_date` (`opd_er_order_master_id`,`order_date`) USING BTREE,
  INDEX `order_confirm` (`order_confirm`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;