CREATE TABLE `kphis`.`opd_er_nurse_index_action` (
  `action_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `plan_id` INT(11) UNSIGNED DEFAULT NULL,
  `opd_er_order_master_id` INT(11) UNSIGNED NOT NULL,
  `check_datetime` DATETIME DEFAULT NULL,
  `check_person` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `action_result` TEXT DEFAULT NULL,
  `action_remark` TEXT DEFAULT NULL,
  `action_date` DATE DEFAULT NULL,
  `action_time` TIME DEFAULT NULL,
  `action_report_back` VARCHAR(1) DEFAULT NULL,
  `action_blood_had` VARCHAR(1) DEFAULT NULL,
  `action_person_1` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `action_person_2` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `update_datetime` DATETIME NOT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`action_id`) USING BTREE,
  INDEX `plan_id` (`plan_id`) USING BTREE,
  INDEX `plan_id_action_date` (`plan_id`,`action_date`) USING BTREE,
  INDEX `opd_er_order_master_id_action_date` (`opd_er_order_master_id`,`action_date`) USING BTREE,
  INDEX `action_date_time` (`action_date`,`action_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;