CREATE TABLE `kphis`.`opd_er_dr_pe` (
  `opd_er_pe_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `opd_er_order_master_id` INT(11) UNSIGNED NOT NULL,
  `arc` VARCHAR(1) DEFAULT NULL,
  `arc_npc_text` VARCHAR(200) DEFAULT NULL,
  `breathing_chest_wall` VARCHAR(200) DEFAULT NULL,
  `breathing_lung` VARCHAR(200) DEFAULT NULL,
  `circulation_shock` VARCHAR(1) DEFAULT NULL,
  `circulation_shock_text` VARCHAR(200) DEFAULT NULL,
  `circulation_other` VARCHAR(1) DEFAULT NULL,
  `circulation_other_text` VARCHAR(200) DEFAULT NULL,
  `circulation_efast_date` DATE DEFAULT NULL,
  `circulation_efast_time` TIME DEFAULT NULL,
  `circulation_doctor` VARCHAR(7) DEFAULT NULL,
  `circulation` VARCHAR(1) DEFAULT NULL,
  `circulation_positive_text` VARCHAR(200) DEFAULT NULL,
  `disability_e` INT(1) DEFAULT NULL,
  `disability_v` VARCHAR(1) DEFAULT NULL,
  `disability_m` INT(1) DEFAULT NULL,
  `disability_pupil_rt` DECIMAL(2,1) DEFAULT NULL,
  `disability_pupil_lt` DECIMAL(2,1) DEFAULT NULL,
  `disability_other` VARCHAR(200) DEFAULT NULL,
  `exposure` VARCHAR(200) DEFAULT NULL,
  `doctor_pe` VARCHAR(7) DEFAULT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `create_datetime` DATETIME DEFAULT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `update_datetime` DATETIME DEFAULT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`opd_er_pe_id`) USING BTREE,
  UNIQUE INDEX `opd_er_order_master_id` (`opd_er_order_master_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;