CREATE TABLE `kphis`.`opd_er_io` (
  `opd_er_io_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `opd_er_order_master_id` INT(11) UNSIGNED NOT NULL,
  `opd_er_io_date` DATE NOT NULL,
  `opd_er_io_time` TIME NOT NULL,
  `opd_er_io_parenteral_type` VARCHAR(50) DEFAULT NULL,
  `opd_er_io_parenteral_name` VARCHAR(200) DEFAULT NULL,
  `opd_er_io_parenteral_amount` DECIMAL(6,1) DEFAULT NULL,
  `opd_er_io_parenteral_absorb` DECIMAL(6,1) DEFAULT NULL,
  `opd_er_io_parenteral_carry_forward` DECIMAL(6,1) DEFAULT NULL,
  `opd_er_io_parenteral_remark` TEXT DEFAULT NULL,
  `opd_er_io_oral_name` VARCHAR(200) DEFAULT NULL,
  `opd_er_io_oral_amount` INT(11) DEFAULT NULL,
  `opd_er_io_oral_absorb` INT(11) DEFAULT NULL,
  `opd_er_io_oral_carry_forward` INT(11) DEFAULT NULL,
  `opd_er_io_oral_remark` TEXT DEFAULT NULL,
  `opd_er_io_output_type` VARCHAR(50) DEFAULT NULL,
  `opd_er_io_output_amount` INT(11) DEFAULT NULL,
  `opd_er_io_output_remark` TEXT DEFAULT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `update_datetime` DATETIME DEFAULT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`opd_er_io_id`) USING BTREE,
  INDEX `opd_er_order_master_id` (`opd_er_order_master_id`) USING BTREE,
  INDEX `opd_er_io_date` (`opd_er_io_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;