CREATE TABLE `kphis`.`opd_er_order_master` (
  `opd_er_order_master_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_date` DATE DEFAULT NULL,
  `order_time` TIME DEFAULT NULL,
  `order_doctor` VARCHAR(7) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `note` TEXT DEFAULT NULL,
  `vn` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `bedno` INT(11) UNSIGNED DEFAULT NULL,
  `er_patient_status_id` INT(11) UNSIGNED DEFAULT NULL,
  `er_dch_type_id` INT(11) UNSIGNED DEFAULT NULL,
  `discharge_date` DATE DEFAULT NULL,
  `discharge_time` TIME DEFAULT NULL,
  `delete_flag` VARCHAR(1) DEFAULT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `update_datetime` DATETIME NOT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`opd_er_order_master_id`) USING BTREE,
  INDEX `order_date` (`order_date`) USING BTREE,
  INDEX `vn` (`vn`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;