CREATE TABLE `kphis`.`system_patient_lock` (
  `patient_lock_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cid` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `hn` VARCHAR(9) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `vn` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `an` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `lock_host` VARCHAR(100) DEFAULT NULL,
  `lock_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' DEFAULT NULL,
  `lock_program` VARCHAR(255) DEFAULT NULL,
  `lock_datetime` DATETIME DEFAULT NULL,
  PRIMARY KEY (`patient_lock_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;