CREATE TABLE `kphis_extra`.`ipd_summary_audit` (
  `summary_audit_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `summary_id` INT(11) UNSIGNED NOT NULL,
  `payer` VARCHAR(3) NULL DEFAULT NULL,
  `audit_type` CHAR(1) NOT NULL DEFAULT 'I',
  `doctor_auth` VARCHAR(1) NULL DEFAULT NULL,
  `com_hn` VARCHAR(9) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
  `com_an` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
  `com_adm_datetime` DATETIME NULL DEFAULT NULL,
  `com_dch_datetime` DATETIME NOT NULL,
  `com_leaveday` INT(11) NULL DEFAULT NULL,
  `com_sex` CHAR(1) NULL DEFAULT NULL,
  `com_birthday` DATE NULL DEFAULT NULL,
  `com_bw` INT(11) NULL DEFAULT NULL,
  `com_dchstts` VARCHAR(2) NULL DEFAULT NULL,
  `com_dchtype` VARCHAR(2) NULL DEFAULT NULL,
  `com_pid` VARCHAR(13) NULL DEFAULT NULL,
  `com_drg` VARCHAR(5) NULL DEFAULT NULL,
  `com_rw` DOUBLE(15,5) NULL DEFAULT NULL,
  `com_adjrw` DOUBLE(15,5) NULL DEFAULT NULL,
  `rev_hn` VARCHAR(9) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
  `rev_an` VARCHAR(13) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
  `rev_adm_datetime` DATETIME NULL DEFAULT NULL,
  `rev_dch_datetime` DATETIME NULL DEFAULT NULL,
  `rev_leaveday` INT(11) NULL DEFAULT NULL,
  `rev_sex` CHAR(1) NULL DEFAULT NULL,
  `rev_birthday` DATE NULL DEFAULT NULL,
  `rev_bw` INT(11) NULL DEFAULT NULL,
  `rev_dchstts` VARCHAR(2) NULL DEFAULT NULL,
  `rev_dchtype` VARCHAR(2) NULL DEFAULT NULL,
  `rev_pid` VARCHAR(13) NULL DEFAULT NULL,
  `rev_drg` VARCHAR(5) NULL DEFAULT NULL,
  `rev_rw` DOUBLE(15,5) NULL DEFAULT NULL,
  `rev_adjrw` DOUBLE(15,5) NULL DEFAULT NULL,
  `sa` VARCHAR(2) NOT NULL,
  `ca` VARCHAR(2) NOT NULL,
  `create_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `create_datetime` DATETIME NOT NULL,
  `update_user` VARCHAR(250) CHARACTER SET tis620 COLLATE 'tis620_thai_ci' NOT NULL,
  `update_datetime` DATETIME NOT NULL,
  `version` INT(11) NOT NULL,
  PRIMARY KEY (`summary_audit_id`) USING BTREE,
  INDEX `summary_id` (`summary_id`) USING BTREE,
  INDEX `com_dch_datetime` (`com_dch_datetime`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;