CREATE TABLE `kphis_extra`.`prescription_screen` (
	`vn` VARCHAR(13) COLLATE 'tis620_thai_ci' NOT NULL,
	`pharmacist_accept` VARCHAR(7) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pharmacist_accept_time` DATETIME NULL DEFAULT NULL,
	`pharmacist_check` VARCHAR(7) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pharmacist_check_time` DATETIME NULL DEFAULT NULL,
	`pharmacist_done` VARCHAR(7) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pharmacist_done_time` DATETIME NULL DEFAULT NULL,
	`postal_status` VARCHAR(1) NULL DEFAULT NULL,
	`postal_doctor` VARCHAR(7) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`postal_time` DATETIME NULL DEFAULT NULL,
	`telemed_add` TEXT NULL DEFAULT NULL,
	`telemed_dose_up` TEXT NULL DEFAULT NULL,
	`telemed_dose_down` TEXT NULL DEFAULT NULL,
	`telemed_off` TEXT NULL DEFAULT NULL,
	`telemed_other` TEXT NULL DEFAULT NULL,
	`telemed_doctor` VARCHAR(7) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`telemed_time` DATETIME NULL DEFAULT NULL,
	`pharmacy_care` TEXT NULL DEFAULT NULL,
	`pharmacy_care_doctor` VARCHAR(7) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pharmacy_care_time` DATETIME NULL DEFAULT NULL,
	`create_user` VARCHAR(250) COLLATE 'tis620_thai_ci' NOT NULL,
	`create_datetime` DATETIME NOT NULL,
	`update_user` VARCHAR(250) COLLATE 'tis620_thai_ci' NOT NULL,
	`update_datetime` DATETIME NOT NULL,
	`version` INT(11) NOT NULL,
	PRIMARY KEY (`vn`) USING BTREE,
	INDEX `postal_status` (`postal_status`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;