CREATE TABLE `kphis_extra`.`refer_note` (
	`refernote_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`vn` VARCHAR(13) COLLATE 'tis620_thai_ci' NOT NULL,
	`hn` VARCHAR(9) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_hospcode` VARCHAR(9) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_date` DATE NULL DEFAULT NULL,
	`refer_time` TIME NULL DEFAULT NULL,
	`docno` TEXT NULL DEFAULT NULL,
	`pmh` TEXT NULL DEFAULT NULL,
	`hpi` TEXT NULL DEFAULT NULL,
	`lab_text` TEXT NULL DEFAULT NULL,
	`treatment_text` TEXT NULL DEFAULT NULL,
	`other_text` TEXT NULL DEFAULT NULL,
	`diagnosis_text` TEXT NULL DEFAULT NULL,
	`request_text` TEXT NULL DEFAULT NULL,
	`doctor` VARCHAR(7) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`cc` TEXT NULL DEFAULT NULL,
	`pe` TEXT NULL DEFAULT NULL,
	`create_user` VARCHAR(250) COLLATE 'tis620_thai_ci' NOT NULL,
	`create_datetime` DATETIME NOT NULL,
	`update_user` VARCHAR(250) COLLATE 'tis620_thai_ci' NOT NULL,
	`update_datetime` DATETIME NOT NULL,
	`version` INT(11) NOT NULL,
	PRIMARY KEY (`refernote_id`) USING BTREE,
	INDEX `ix_refer_date` (`refer_date`) USING BTREE,
	INDEX `ix_vn` (`vn`) USING BTREE,
	INDEX `ix_hn` (`hn`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;
