use derive_demo::Demo;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

// Some `print` not exists in KPHIS's system_ac_permission table.. we not implement too
// AdmissionNotePrint
// IpdDischargeSummaryPrint
// IpdNurseAdmissionNotePrint
// IpdNurseFocusListPrint
// IpdNurseFocusNotePrint
// IpdNurseIndexPrint
// LabPrint
// MedReconciliationPrint
// OpdErDocumentPrint
// VitalSignPrint
/// Permission
#[derive(Clone, Debug, Default, Demo, Deserialize, Hash, Ord, PartialOrd, Eq, PartialEq, Serialize, ToSchema)]
#[schema(example = json!(Permission::demo_lab_view()))]
pub enum Permission {
    AdmissionNoteAdd,
    AdmissionNoteDrugAllergyCheck,
    AdmissionNoteEdit,
    AdmissionNoteRemove,
    AdmissionNoteView,
    DataTypeAuditorUse,
    DataTypeDoctorUse,
    DataTypeNurseUse,
    DataTypeOtherUse,
    DataTypePharmacyUse,
    DataTypePhysiologistUse,
    DataTypeXrayUse,
    EmrView,
    FoodOrderAccess,
    IoAdd,
    IoEdit,
    IoPrint,
    IoRemove,
    IoView,
    IpdDischargeSummaryAdd,
    IpdDischargeSummaryEdit,
    IpdDischargeSummaryRemove,
    IpdDischargeSummaryView,
    IpdDoctorConsultAdd,
    IpdDoctorConsultEdit,
    IpdDoctorConsultPrint,
    IpdDoctorConsultRemove,
    IpdDoctorConsultView,
    IpdDoctorInchargeAdd,
    IpdDoctorInchargeEdit,
    IpdDoctorInchargeRemove,
    IpdDoctorInchargeView,
    IpdDoctorMainProgramAccess,
    IpdDocumentPrint,
    IpdLabReadAdd,
    IpdLabReadEdit,
    IpdLabReadRemove,
    IpdLabReadView,
    IpdNurseAdmissionNoteAdd,
    IpdNurseAdmissionNoteEdit,
    IpdNurseAdmissionNoteRemove,
    IpdNurseAdmissionNoteView,
    IpdNurseIndexAdd,
    IpdNurseIndexEdit,
    IpdNurseIndexNoteAdd,
    IpdNurseIndexNoteEdit,
    IpdNurseIndexNoteRemove,
    IpdNurseIndexNoteView,
    IpdNurseIndexRemove,
    IpdNurseIndexView,
    IpdNurseMainProgramAccess,
    IpdNurseNoteAdd,
    IpdNurseNoteEdit,
    IpdNurseNoteRemove,
    IpdNurseNoteView,
    IpdOrderAccept,
    IpdOrderAdd,
    IpdOrderCheck,
    IpdOrderConfirm,
    IpdOrderDone,
    IpdOrderEdit,
    IpdOrderOff,
    IpdOrderPrint,
    IpdOrderRemove,
    IpdOrderTemplateShare,
    IpdOrderView,
    IpdOtherOrderMainProgramAccess,
    IpdPharmacyOrderMainProgramAccess,
    LabView,
    MedReconciliationAdd,
    MedReconciliationComfirm,
    MedReconciliationConsider,
    MedReconciliationEdit,
    MedReconciliationRemove,
    MedReconciliationView,
    NursingProgressnoteTemplateAdd,
    NursingProgressnoteTemplateEdit,
    NursingProgressnoteTemplateRemove,
    NursingProgressnoteTemplateView,
    OpdErDoctorProgramAccess,
    OpdErDocumentPrint,
    OpdErIoAdd,
    OpdErIoEdit,
    OpdErIoPrint,
    OpdErIoRemove,
    OpdErIoView,
    OpdErMedicalHistoryPrint,
    OpdErNurseFocusListPrint,
    OpdErNurseFocusNotePrint,
    OpdErNurseIndexAdd,
    OpdErNurseIndexEdit,
    OpdErNurseIndexNoteAdd,
    OpdErNurseIndexNoteEdit,
    OpdErNurseIndexNoteRemove,
    OpdErNurseIndexNoteView,
    OpdErNurseIndexPrint,
    OpdErNurseIndexRemove,
    OpdErNurseIndexView,
    OpdErNurseNoteAdd,
    OpdErNurseNoteEdit,
    OpdErNurseNoteRemove,
    OpdErNurseNoteView,
    OpdErNurseProgramAccess,
    OpdErOrderAccept,
    OpdErOrderAdd,
    OpdErOrderCheck,
    OpdErOrderConfirm,
    OpdErOrderDone,
    OpdErOrderEdit,
    OpdErOrderOff,
    OpdErOrderPrint,
    OpdErOrderRemove,
    OpdErOrderView,
    OpdErOtherOrderProgramAccess,
    OpdErPharmacyOrderProgramAccess,
    OpdErProgressNoteAdd,
    OpdErProgressNoteEdit,
    OpdErProgressNoteRemove,
    OpdErProgressNoteView,
    OpdErVitalSignAdd,
    OpdErVitalSignEdit,
    OpdErVitalSignPrint,
    OpdErVitalSignRemove,
    OpdErVitalSignView,
    OperationView,
    ProgressNoteAdd,
    ProgressNoteEdit,
    ProgressNoteRemove,
    ProgressNoteView,
    ScanDocumentAccess,
    SystemAcOpdUserView,
    SystemAcPermissionView,
    SystemAcReportAdd,
    SystemAcReportEdit,
    SystemAcReportRemove,
    SystemAcReportView,
    SystemAcRoleAdd,
    SystemAcRoleEdit,
    SystemAcRolePermissionAdd,
    SystemAcRolePermissionEdit,
    SystemAcRolePermissionRemove,
    SystemAcRolePermissionView,
    SystemAcRoleRemove,
    SystemAcRoleUserAdd,
    SystemAcRoleUserEdit,
    SystemAcRoleUserView,
    SystemAcRoleView,
    VitalSignAdd,
    VitalSignEdit,
    VitalSignRemove,
    VitalSignView,
    XrayView,
    #[default]
    Unknown,
}

impl Permission {
    pub fn new(s: &str) -> Self {
        match s {
            "ADMISSION_NOTE_ADD" => Self::AdmissionNoteAdd,
            "ADMISSION_NOTE_DRUG_ALLERGY_CHECK" => Self::AdmissionNoteDrugAllergyCheck,
            "ADMISSION_NOTE_EDIT" => Self::AdmissionNoteEdit,
            "ADMISSION_NOTE_REMOVE" => Self::AdmissionNoteRemove,
            "ADMISSION_NOTE_VIEW" => Self::AdmissionNoteView,
            "DATA_TYPE_AUDITOR_USE" => Self::DataTypeAuditorUse,
            "DATA_TYPE_DOCTOR_USE" => Self::DataTypeDoctorUse,
            "DATA_TYPE_NURSE_USE" => Self::DataTypeNurseUse,
            "DATA_TYPE_OTHER_USE" => Self::DataTypeOtherUse,
            "DATA_TYPE_PHARMACY_USE" => Self::DataTypePharmacyUse,
            "DATA_TYPE_PHYSIOLOGIST_USE" => Self::DataTypePhysiologistUse,
            "DATA_TYPE_XRAY_USE" => Self::DataTypeXrayUse,
            "EMR_VIEW" => Self::EmrView,
            "FOOD_ORDER_ACCESS" => Self::FoodOrderAccess,
            "IO_ADD" => Self::IoAdd,
            "IO_EDIT" => Self::IoEdit,
            "IO_PRINT" => Self::IoPrint,
            "IO_REMOVE" => Self::IoRemove,
            "IO_VIEW" => Self::IoView,
            "IPD_DISCHARGE_SUMMARY_ADD" => Self::IpdDischargeSummaryAdd,
            "IPD_DISCHARGE_SUMMARY_EDIT" => Self::IpdDischargeSummaryEdit,
            "IPD_DISCHARGE_SUMMARY_REMOVE" => Self::IpdDischargeSummaryRemove,
            "IPD_DISCHARGE_SUMMARY_VIEW" => Self::IpdDischargeSummaryView,
            "IPD_DOCTOR_CONSULT_ADD" => Self::IpdDoctorConsultAdd,
            "IPD_DOCTOR_CONSULT_EDIT" => Self::IpdDoctorConsultEdit,
            "IPD_DOCTOR_CONSULT_PRINT" => Self::IpdDoctorConsultPrint,
            "IPD_DOCTOR_CONSULT_REMOVE" => Self::IpdDoctorConsultRemove,
            "IPD_DOCTOR_CONSULT_VIEW" => Self::IpdDoctorConsultView,
            "IPD_DOCTOR_INCHARGE_ADD" => Self::IpdDoctorInchargeAdd,
            "IPD_DOCTOR_INCHARGE_EDIT" => Self::IpdDoctorInchargeEdit,
            "IPD_DOCTOR_INCHARGE_REMOVE" => Self::IpdDoctorInchargeRemove,
            "IPD_DOCTOR_INCHARGE_VIEW" => Self::IpdDoctorInchargeView,
            "IPD_DOCTOR_MAIN_PROGRAM_ACCESS" => Self::IpdDoctorMainProgramAccess,
            "IPD_DOCUMENT_PRINT" => Self::IpdDocumentPrint,
            "IPD_LAB_READ_ADD" => Self::IpdLabReadAdd,
            "IPD_LAB_READ_EDIT" => Self::IpdLabReadEdit,
            "IPD_LAB_READ_REMOVE" => Self::IpdLabReadRemove,
            "IPD_LAB_READ_VIEW" => Self::IpdLabReadView,
            "IPD_NURSE_ADDMISSION_NOTE_ADD" => Self::IpdNurseAdmissionNoteAdd,
            "IPD_NURSE_ADDMISSION_NOTE_EDIT" => Self::IpdNurseAdmissionNoteEdit,
            "IPD_NURSE_ADDMISSION_NOTE_REMOVE" => Self::IpdNurseAdmissionNoteRemove,
            "IPD_NURSE_ADDMISSION_NOTE_VIEW" => Self::IpdNurseAdmissionNoteView,
            "IPD_NURSE_INDEX_ADD" => Self::IpdNurseIndexAdd,
            "IPD_NURSE_INDEX_EDIT" => Self::IpdNurseIndexEdit,
            "IPD_NURSE_INDEX_NOTE_ADD" => Self::IpdNurseIndexNoteAdd,
            "IPD_NURSE_INDEX_NOTE_EDIT" => Self::IpdNurseIndexNoteEdit,
            "IPD_NURSE_INDEX_NOTE_REMOVE" => Self::IpdNurseIndexNoteRemove,
            "IPD_NURSE_INDEX_NOTE_VIEW" => Self::IpdNurseIndexNoteView,
            "IPD_NURSE_INDEX_REMOVE" => Self::IpdNurseIndexRemove,
            "IPD_NURSE_INDEX_VIEW" => Self::IpdNurseIndexView,
            "IPD_NURSE_MAIN_PROGRAM_ACCESS" => Self::IpdNurseMainProgramAccess,
            "IPD_NURSE_NOTE_ADD" => Self::IpdNurseNoteAdd,
            "IPD_NURSE_NOTE_EDIT" => Self::IpdNurseNoteEdit,
            "IPD_NURSE_NOTE_REMOVE" => Self::IpdNurseNoteRemove,
            "IPD_NURSE_NOTE_VIEW" => Self::IpdNurseNoteView,
            "IPD_ORDER_ACCEPT" => Self::IpdOrderAccept,
            "IPD_ORDER_ADD" => Self::IpdOrderAdd,
            "IPD_ORDER_CHECK" => Self::IpdOrderCheck,
            "IPD_ORDER_CONFIRM" => Self::IpdOrderConfirm,
            "IPD_ORDER_DONE" => Self::IpdOrderDone,
            "IPD_ORDER_EDIT" => Self::IpdOrderEdit,
            "IPD_ORDER_OFF" => Self::IpdOrderOff,
            "IPD_ORDER_PRINT" => Self::IpdOrderPrint,
            "IPD_ORDER_REMOVE" => Self::IpdOrderRemove,
            "IPD_ORDER_TEMPLATE_SHARE" => Self::IpdOrderTemplateShare,
            "IPD_ORDER_VIEW" => Self::IpdOrderView,
            "IPD_OTHER_ORDER_MAIN_PROGRAM_ACCESS" => Self::IpdOtherOrderMainProgramAccess,
            "IPD_PHARMACY_ORDER_MAIN_PROGRAM_ACCESS" => Self::IpdPharmacyOrderMainProgramAccess,
            "LAB_VIEW" => Self::LabView,
            "MED_RECONCILIATION_ADD" => Self::MedReconciliationAdd,
            "MED_RECONCILIATION_COMFIRM" => Self::MedReconciliationComfirm,
            "MED_RECONCILIATION_CONSIDER" => Self::MedReconciliationConsider,
            "MED_RECONCILIATION_EDIT" => Self::MedReconciliationEdit,
            "MED_RECONCILIATION_REMOVE" => Self::MedReconciliationRemove,
            "MED_RECONCILIATION_VIEW" => Self::MedReconciliationView,
            "NURSING_PROGRESSNOTE_TEMPLATE_ADD" => Self::NursingProgressnoteTemplateAdd,
            "NURSING_PROGRESSNOTE_TEMPLATE_EDIT" => Self::NursingProgressnoteTemplateEdit,
            "NURSING_PROGRESSNOTE_TEMPLATE_REMOVE" => Self::NursingProgressnoteTemplateRemove,
            "NURSING_PROGRESSNOTE_TEMPLATE_VIEW" => Self::NursingProgressnoteTemplateView,
            "OPD_ER_DOCTOR_PROGRAM_ACCESS" => Self::OpdErDoctorProgramAccess,
            "OPD_ER_DOCUMENT_PRINT" => Self::OpdErDocumentPrint,
            "OPD_ER_IO_ADD" => Self::OpdErIoAdd,
            "OPD_ER_IO_EDIT" => Self::OpdErIoEdit,
            "OPD_ER_IO_PRINT" => Self::OpdErIoPrint,
            "OPD_ER_IO_REMOVE" => Self::OpdErIoRemove,
            "OPD_ER_IO_VIEW" => Self::OpdErIoView,
            "OPD_ER_MEDICAL_HISTORY_PRINT" => Self::OpdErMedicalHistoryPrint,
            "OPD_ER_NURSE_FOCUS_LIST_PRINT" => Self::OpdErNurseFocusListPrint,
            "OPD_ER_NURSE_FOCUS_NOTE_PRINT" => Self::OpdErNurseFocusNotePrint,
            "OPD_ER_NURSE_INDEX_ADD" => Self::OpdErNurseIndexAdd,
            "OPD_ER_NURSE_INDEX_EDIT" => Self::OpdErNurseIndexEdit,
            "OPD_ER_NURSE_INDEX_NOTE_ADD" => Self::OpdErNurseIndexNoteAdd,
            "OPD_ER_NURSE_INDEX_NOTE_EDIT" => Self::OpdErNurseIndexNoteEdit,
            "OPD_ER_NURSE_INDEX_NOTE_REMOVE" => Self::OpdErNurseIndexNoteRemove,
            "OPD_ER_NURSE_INDEX_NOTE_VIEW" => Self::OpdErNurseIndexNoteView,
            "OPD_ER_NURSE_INDEX_PRINT" => Self::OpdErNurseIndexPrint,
            "OPD_ER_NURSE_INDEX_REMOVE" => Self::OpdErNurseIndexRemove,
            "OPD_ER_NURSE_INDEX_VIEW" => Self::OpdErNurseIndexView,
            "OPD_ER_NURSE_NOTE_ADD" => Self::OpdErNurseNoteAdd,
            "OPD_ER_NURSE_NOTE_EDIT" => Self::OpdErNurseNoteEdit,
            "OPD_ER_NURSE_NOTE_REMOVE" => Self::OpdErNurseNoteRemove,
            "OPD_ER_NURSE_NOTE_VIEW" => Self::OpdErNurseNoteView,
            "OPD_ER_NURSE_PROGRAM_ACCESS" => Self::OpdErNurseProgramAccess,
            "OPD_ER_ORDER_ACCEPT" => Self::OpdErOrderAccept,
            "OPD_ER_ORDER_ADD" => Self::OpdErOrderAdd,
            "OPD_ER_ORDER_CHECK" => Self::OpdErOrderCheck,
            "OPD_ER_ORDER_CONFIRM" => Self::OpdErOrderConfirm,
            "OPD_ER_ORDER_DONE" => Self::OpdErOrderDone,
            "OPD_ER_ORDER_EDIT" => Self::OpdErOrderEdit,
            "OPD_ER_ORDER_OFF" => Self::OpdErOrderOff,
            "OPD_ER_ORDER_PRINT" => Self::OpdErOrderPrint,
            "OPD_ER_ORDER_REMOVE" => Self::OpdErOrderRemove,
            "OPD_ER_ORDER_VIEW" => Self::OpdErOrderView,
            "OPD_ER_OTHER_ORDER_PROGRAM_ACCESS" => Self::OpdErOtherOrderProgramAccess,
            "OPD_ER_PHARMACY_ORDER_PROGRAM_ACCESS" => Self::OpdErPharmacyOrderProgramAccess,
            "OPD_ER_PROGRESS_NOTE_ADD" => Self::OpdErProgressNoteAdd,
            "OPD_ER_PROGRESS_NOTE_EDIT" => Self::OpdErProgressNoteEdit,
            "OPD_ER_PROGRESS_NOTE_REMOVE" => Self::OpdErProgressNoteRemove,
            "OPD_ER_PROGRESS_NOTE_VIEW" => Self::OpdErProgressNoteView,
            "OPD_ER_VITAL_SIGN_ADD" => Self::OpdErVitalSignAdd,
            "OPD_ER_VITAL_SIGN_EDIT" => Self::OpdErVitalSignEdit,
            "OPD_ER_VITAL_SIGN_PRINT" => Self::OpdErVitalSignPrint,
            "OPD_ER_VITAL_SIGN_REMOVE" => Self::OpdErVitalSignRemove,
            "OPD_ER_VITAL_SIGN_VIEW" => Self::OpdErVitalSignView,
            "OPERATION_VIEW" => Self::OperationView,
            "PROGRESS_NOTE_ADD" => Self::ProgressNoteAdd,
            "PROGRESS_NOTE_EDIT" => Self::ProgressNoteEdit,
            "PROGRESS_NOTE_REMOVE" => Self::ProgressNoteRemove,
            "PROGRESS_NOTE_VIEW" => Self::ProgressNoteView,
            "SCAN_DOCUMENT_ACCESS" => Self::ScanDocumentAccess,
            "SYSTEM_AC_OPD_USER_VIEW" => Self::SystemAcOpdUserView,
            "SYSTEM_AC_PERMISSION_VIEW" => Self::SystemAcPermissionView,
            "SYSTEM_AC_REPORT_ADD" => Self::SystemAcReportAdd,
            "SYSTEM_AC_REPORT_EDIT" => Self::SystemAcReportEdit,
            "SYSTEM_AC_REPORT_REMOVE" => Self::SystemAcReportRemove,
            "SYSTEM_AC_REPORT_VIEW" => Self::SystemAcReportView,
            "SYSTEM_AC_ROLE_ADD" => Self::SystemAcRoleAdd,
            "SYSTEM_AC_ROLE_EDIT" => Self::SystemAcRoleEdit,
            "SYSTEM_AC_ROLE_PERMISSION_ADD" => Self::SystemAcRolePermissionAdd,
            "SYSTEM_AC_ROLE_PERMISSION_EDIT" => Self::SystemAcRolePermissionEdit,
            "SYSTEM_AC_ROLE_PERMISSION_REMOVE" => Self::SystemAcRolePermissionRemove,
            "SYSTEM_AC_ROLE_PERMISSION_VIEW" => Self::SystemAcRolePermissionView,
            "SYSTEM_AC_ROLE_REMOVE" => Self::SystemAcRoleRemove,
            "SYSTEM_AC_ROLE_USER_ADD" => Self::SystemAcRoleUserAdd,
            "SYSTEM_AC_ROLE_USER_EDIT" => Self::SystemAcRoleUserEdit,
            "SYSTEM_AC_ROLE_USER_VIEW" => Self::SystemAcRoleUserView,
            "SYSTEM_AC_ROLE_VIEW" => Self::SystemAcRoleView,
            "VITAL_SIGN_ADD" => Self::VitalSignAdd,
            "VITAL_SIGN_EDIT" => Self::VitalSignEdit,
            "VITAL_SIGN_REMOVE" => Self::VitalSignRemove,
            "VITAL_SIGN_VIEW" => Self::VitalSignView,
            "XRAY_VIEW" => Self::XrayView,
            _ => Self::Unknown,
        }
    }

    pub fn str(&self) -> &'static str {
        match self {
            Self::AdmissionNoteAdd => "ADMISSION_NOTE_ADD",
            Self::AdmissionNoteDrugAllergyCheck => "ADMISSION_NOTE_DRUG_ALLERGY_CHECK",
            Self::AdmissionNoteEdit => "ADMISSION_NOTE_EDIT",
            Self::AdmissionNoteRemove => "ADMISSION_NOTE_REMOVE",
            Self::AdmissionNoteView => "ADMISSION_NOTE_VIEW",
            Self::DataTypeAuditorUse => "DATA_TYPE_AUDITOR_USE",
            Self::DataTypeDoctorUse => "DATA_TYPE_DOCTOR_USE",
            Self::DataTypeNurseUse => "DATA_TYPE_NURSE_USE",
            Self::DataTypeOtherUse => "DATA_TYPE_OTHER_USE",
            Self::DataTypePharmacyUse => "DATA_TYPE_PHARMACY_USE",
            Self::DataTypePhysiologistUse => "DATA_TYPE_PHYSIOLOGIST_USE",
            Self::DataTypeXrayUse => "DATA_TYPE_XRAY_USE",
            Self::EmrView => "EMR_VIEW",
            Self::FoodOrderAccess => "FOOD_ORDER_ACCESS",
            Self::IoAdd => "IO_ADD",
            Self::IoEdit => "IO_EDIT",
            Self::IoPrint => "IO_PRINT",
            Self::IoRemove => "IO_REMOVE",
            Self::IoView => "IO_VIEW",
            Self::IpdDischargeSummaryAdd => "IPD_DISCHARGE_SUMMARY_ADD",
            Self::IpdDischargeSummaryEdit => "IPD_DISCHARGE_SUMMARY_EDIT",
            Self::IpdDischargeSummaryRemove => "IPD_DISCHARGE_SUMMARY_REMOVE",
            Self::IpdDischargeSummaryView => "IPD_DISCHARGE_SUMMARY_VIEW",
            Self::IpdDoctorConsultAdd => "IPD_DOCTOR_CONSULT_ADD",
            Self::IpdDoctorConsultEdit => "IPD_DOCTOR_CONSULT_EDIT",
            Self::IpdDoctorConsultPrint => "IPD_DOCTOR_CONSULT_PRINT",
            Self::IpdDoctorConsultRemove => "IPD_DOCTOR_CONSULT_REMOVE",
            Self::IpdDoctorConsultView => "IPD_DOCTOR_CONSULT_VIEW",
            Self::IpdDoctorInchargeAdd => "IPD_DOCTOR_INCHARGE_ADD",
            Self::IpdDoctorInchargeEdit => "IPD_DOCTOR_INCHARGE_EDIT",
            Self::IpdDoctorInchargeRemove => "IPD_DOCTOR_INCHARGE_REMOVE",
            Self::IpdDoctorInchargeView => "IPD_DOCTOR_INCHARGE_VIEW",
            Self::IpdDoctorMainProgramAccess => "IPD_DOCTOR_MAIN_PROGRAM_ACCESS",
            Self::IpdDocumentPrint => "IPD_DOCUMENT_PRINT",
            Self::IpdLabReadAdd => "IPD_LAB_READ_ADD",
            Self::IpdLabReadEdit => "IPD_LAB_READ_EDIT",
            Self::IpdLabReadRemove => "IPD_LAB_READ_REMOVE",
            Self::IpdLabReadView => "IPD_LAB_READ_VIEW",
            Self::IpdNurseAdmissionNoteAdd => "IPD_NURSE_ADDMISSION_NOTE_ADD",
            Self::IpdNurseAdmissionNoteEdit => "IPD_NURSE_ADDMISSION_NOTE_EDIT",
            Self::IpdNurseAdmissionNoteRemove => "IPD_NURSE_ADDMISSION_NOTE_REMOVE",
            Self::IpdNurseAdmissionNoteView => "IPD_NURSE_ADDMISSION_NOTE_VIEW",
            Self::IpdNurseIndexAdd => "IPD_NURSE_INDEX_ADD",
            Self::IpdNurseIndexEdit => "IPD_NURSE_INDEX_EDIT",
            Self::IpdNurseIndexNoteAdd => "IPD_NURSE_INDEX_NOTE_ADD",
            Self::IpdNurseIndexNoteEdit => "IPD_NURSE_INDEX_NOTE_EDIT",
            Self::IpdNurseIndexNoteRemove => "IPD_NURSE_INDEX_NOTE_REMOVE",
            Self::IpdNurseIndexNoteView => "IPD_NURSE_INDEX_NOTE_VIEW",
            Self::IpdNurseIndexRemove => "IPD_NURSE_INDEX_REMOVE",
            Self::IpdNurseIndexView => "IPD_NURSE_INDEX_VIEW",
            Self::IpdNurseMainProgramAccess => "IPD_NURSE_MAIN_PROGRAM_ACCESS",
            Self::IpdNurseNoteAdd => "IPD_NURSE_NOTE_ADD",
            Self::IpdNurseNoteEdit => "IPD_NURSE_NOTE_EDIT",
            Self::IpdNurseNoteRemove => "IPD_NURSE_NOTE_REMOVE",
            Self::IpdNurseNoteView => "IPD_NURSE_NOTE_VIEW",
            Self::IpdOrderAccept => "IPD_ORDER_ACCEPT",
            Self::IpdOrderAdd => "IPD_ORDER_ADD",
            Self::IpdOrderCheck => "IPD_ORDER_CHECK",
            Self::IpdOrderConfirm => "IPD_ORDER_CONFIRM",
            Self::IpdOrderDone => "IPD_ORDER_DONE",
            Self::IpdOrderEdit => "IPD_ORDER_EDIT",
            Self::IpdOrderOff => "IPD_ORDER_OFF",
            Self::IpdOrderPrint => "IPD_ORDER_PRINT",
            Self::IpdOrderRemove => "IPD_ORDER_REMOVE",
            Self::IpdOrderTemplateShare => "IPD_ORDER_TEMPLATE_SHARE",
            Self::IpdOrderView => "IPD_ORDER_VIEW",
            Self::IpdOtherOrderMainProgramAccess => "IPD_OTHER_ORDER_MAIN_PROGRAM_ACCESS",
            Self::IpdPharmacyOrderMainProgramAccess => "IPD_PHARMACY_ORDER_MAIN_PROGRAM_ACCESS",
            Self::LabView => "LAB_VIEW",
            Self::MedReconciliationAdd => "MED_RECONCILIATION_ADD",
            Self::MedReconciliationComfirm => "MED_RECONCILIATION_COMFIRM",
            Self::MedReconciliationConsider => "MED_RECONCILIATION_CONSIDER",
            Self::MedReconciliationEdit => "MED_RECONCILIATION_EDIT",
            Self::MedReconciliationRemove => "MED_RECONCILIATION_REMOVE",
            Self::MedReconciliationView => "MED_RECONCILIATION_VIEW",
            Self::NursingProgressnoteTemplateAdd => "NURSING_PROGRESSNOTE_TEMPLATE_ADD",
            Self::NursingProgressnoteTemplateEdit => "NURSING_PROGRESSNOTE_TEMPLATE_EDIT",
            Self::NursingProgressnoteTemplateRemove => "NURSING_PROGRESSNOTE_TEMPLATE_REMOVE",
            Self::NursingProgressnoteTemplateView => "NURSING_PROGRESSNOTE_TEMPLATE_VIEW",
            Self::OpdErDoctorProgramAccess => "OPD_ER_DOCTOR_PROGRAM_ACCESS",
            Self::OpdErDocumentPrint => "OPD_ER_DOCUMENT_PRINT",
            Self::OpdErIoAdd => "OPD_ER_IO_ADD",
            Self::OpdErIoEdit => "OPD_ER_IO_EDIT",
            Self::OpdErIoPrint => "OPD_ER_IO_PRINT",
            Self::OpdErIoRemove => "OPD_ER_IO_REMOVE",
            Self::OpdErIoView => "OPD_ER_IO_VIEW",
            Self::OpdErMedicalHistoryPrint => "OPD_ER_MEDICAL_HISTORY_PRINT",
            Self::OpdErNurseFocusListPrint => "OPD_ER_NURSE_FOCUS_LIST_PRINT",
            Self::OpdErNurseFocusNotePrint => "OPD_ER_NURSE_FOCUS_NOTE_PRINT",
            Self::OpdErNurseIndexAdd => "OPD_ER_NURSE_INDEX_ADD",
            Self::OpdErNurseIndexEdit => "OPD_ER_NURSE_INDEX_EDIT",
            Self::OpdErNurseIndexNoteAdd => "OPD_ER_NURSE_INDEX_NOTE_ADD",
            Self::OpdErNurseIndexNoteEdit => "OPD_ER_NURSE_INDEX_NOTE_EDIT",
            Self::OpdErNurseIndexNoteRemove => "OPD_ER_NURSE_INDEX_NOTE_REMOVE",
            Self::OpdErNurseIndexNoteView => "OPD_ER_NURSE_INDEX_NOTE_VIEW",
            Self::OpdErNurseIndexPrint => "OPD_ER_NURSE_INDEX_PRINT",
            Self::OpdErNurseIndexRemove => "OPD_ER_NURSE_INDEX_REMOVE",
            Self::OpdErNurseIndexView => "OPD_ER_NURSE_INDEX_VIEW",
            Self::OpdErNurseNoteAdd => "OPD_ER_NURSE_NOTE_ADD",
            Self::OpdErNurseNoteEdit => "OPD_ER_NURSE_NOTE_EDIT",
            Self::OpdErNurseNoteRemove => "OPD_ER_NURSE_NOTE_REMOVE",
            Self::OpdErNurseNoteView => "OPD_ER_NURSE_NOTE_VIEW",
            Self::OpdErNurseProgramAccess => "OPD_ER_NURSE_PROGRAM_ACCESS",
            Self::OpdErOrderAccept => "OPD_ER_ORDER_ACCEPT",
            Self::OpdErOrderAdd => "OPD_ER_ORDER_ADD",
            Self::OpdErOrderCheck => "OPD_ER_ORDER_CHECK",
            Self::OpdErOrderConfirm => "OPD_ER_ORDER_CONFIRM",
            Self::OpdErOrderDone => "OPD_ER_ORDER_DONE",
            Self::OpdErOrderEdit => "OPD_ER_ORDER_EDIT",
            Self::OpdErOrderOff => "OPD_ER_ORDER_OFF",
            Self::OpdErOrderPrint => "OPD_ER_ORDER_PRINT",
            Self::OpdErOrderRemove => "OPD_ER_ORDER_REMOVE",
            Self::OpdErOrderView => "OPD_ER_ORDER_VIEW",
            Self::OpdErOtherOrderProgramAccess => "OPD_ER_OTHER_ORDER_PROGRAM_ACCESS",
            Self::OpdErPharmacyOrderProgramAccess => "OPD_ER_PHARMACY_ORDER_PROGRAM_ACCESS",
            Self::OpdErProgressNoteAdd => "OPD_ER_PROGRESS_NOTE_ADD",
            Self::OpdErProgressNoteEdit => "OPD_ER_PROGRESS_NOTE_EDIT",
            Self::OpdErProgressNoteRemove => "OPD_ER_PROGRESS_NOTE_REMOVE",
            Self::OpdErProgressNoteView => "OPD_ER_PROGRESS_NOTE_VIEW",
            Self::OpdErVitalSignAdd => "OPD_ER_VITAL_SIGN_ADD",
            Self::OpdErVitalSignEdit => "OPD_ER_VITAL_SIGN_EDIT",
            Self::OpdErVitalSignPrint => "OPD_ER_VITAL_SIGN_PRINT",
            Self::OpdErVitalSignRemove => "OPD_ER_VITAL_SIGN_REMOVE",
            Self::OpdErVitalSignView => "OPD_ER_VITAL_SIGN_VIEW",
            Self::OperationView => "OPERATION_VIEW",
            Self::ProgressNoteAdd => "PROGRESS_NOTE_ADD",
            Self::ProgressNoteEdit => "PROGRESS_NOTE_EDIT",
            Self::ProgressNoteRemove => "PROGRESS_NOTE_REMOVE",
            Self::ProgressNoteView => "PROGRESS_NOTE_VIEW",
            Self::ScanDocumentAccess => "SCAN_DOCUMENT_ACCESS",
            Self::SystemAcOpdUserView => "SYSTEM_AC_OPD_USER_VIEW",
            Self::SystemAcPermissionView => "SYSTEM_AC_PERMISSION_VIEW",
            Self::SystemAcReportAdd => "SYSTEM_AC_REPORT_ADD",
            Self::SystemAcReportEdit => "SYSTEM_AC_REPORT_EDIT",
            Self::SystemAcReportRemove => "SYSTEM_AC_REPORT_REMOVE",
            Self::SystemAcReportView => "SYSTEM_AC_REPORT_VIEW",
            Self::SystemAcRoleAdd => "SYSTEM_AC_ROLE_ADD",
            Self::SystemAcRoleEdit => "SYSTEM_AC_ROLE_EDIT",
            Self::SystemAcRolePermissionAdd => "SYSTEM_AC_ROLE_PERMISSION_ADD",
            Self::SystemAcRolePermissionEdit => "SYSTEM_AC_ROLE_PERMISSION_EDIT",
            Self::SystemAcRolePermissionRemove => "SYSTEM_AC_ROLE_PERMISSION_REMOVE",
            Self::SystemAcRolePermissionView => "SYSTEM_AC_ROLE_PERMISSION_VIEW",
            Self::SystemAcRoleRemove => "SYSTEM_AC_ROLE_REMOVE",
            Self::SystemAcRoleUserAdd => "SYSTEM_AC_ROLE_USER_ADD",
            Self::SystemAcRoleUserEdit => "SYSTEM_AC_ROLE_USER_EDIT",
            Self::SystemAcRoleUserView => "SYSTEM_AC_ROLE_USER_VIEW",
            Self::SystemAcRoleView => "SYSTEM_AC_ROLE_VIEW",
            Self::VitalSignAdd => "VITAL_SIGN_ADD",
            Self::VitalSignEdit => "VITAL_SIGN_EDIT",
            Self::VitalSignRemove => "VITAL_SIGN_REMOVE",
            Self::VitalSignView => "VITAL_SIGN_VIEW",
            Self::XrayView => "XRAY_VIEW",
            Self::Unknown => "",
        }
    }

    pub fn read_only(&self) -> bool {
        matches!(
            self,
            Self::AdmissionNoteView
                | Self::DataTypeAuditorUse
                | Self::DataTypeDoctorUse
                | Self::DataTypeNurseUse
                | Self::DataTypeOtherUse
                | Self::DataTypePharmacyUse
                | Self::DataTypePhysiologistUse
                | Self::DataTypeXrayUse
                | Self::EmrView
                | Self::FoodOrderAccess
                | Self::IoPrint
                | Self::IoView
                | Self::IpdDischargeSummaryView
                | Self::IpdDoctorConsultPrint
                | Self::IpdDoctorConsultView
                | Self::IpdDoctorInchargeView
                | Self::IpdDoctorMainProgramAccess
                | Self::IpdDocumentPrint
                | Self::IpdLabReadView
                | Self::IpdNurseAdmissionNoteView
                | Self::IpdNurseIndexNoteView
                | Self::IpdNurseIndexView
                | Self::IpdNurseMainProgramAccess
                | Self::IpdNurseNoteView
                | Self::IpdOrderPrint
                | Self::IpdOrderView
                | Self::IpdOtherOrderMainProgramAccess
                | Self::IpdPharmacyOrderMainProgramAccess
                | Self::LabView
                | Self::MedReconciliationView
                | Self::NursingProgressnoteTemplateView
                | Self::OpdErDoctorProgramAccess
                | Self::OpdErDocumentPrint
                | Self::OpdErIoPrint
                | Self::OpdErIoView
                | Self::OpdErMedicalHistoryPrint
                | Self::OpdErNurseFocusListPrint
                | Self::OpdErNurseFocusNotePrint
                | Self::OpdErNurseIndexNoteView
                | Self::OpdErNurseIndexPrint
                | Self::OpdErNurseIndexView
                | Self::OpdErNurseNoteView
                | Self::OpdErNurseProgramAccess
                | Self::OpdErOrderPrint
                | Self::OpdErOrderView
                | Self::OpdErOtherOrderProgramAccess
                | Self::OpdErPharmacyOrderProgramAccess
                | Self::OpdErProgressNoteView
                | Self::OpdErVitalSignPrint
                | Self::OpdErVitalSignView
                | Self::OperationView
                | Self::ProgressNoteView
                | Self::ScanDocumentAccess
                | Self::SystemAcOpdUserView
                | Self::SystemAcPermissionView
                | Self::SystemAcReportView
                | Self::SystemAcRolePermissionView
                | Self::SystemAcRoleUserView
                | Self::SystemAcRoleView
                | Self::VitalSignView
                | Self::XrayView
        )
    }
}
