CREATE TABLE `hos`.`doctor` (
	`code` VARCHAR(15) NOT NULL DEFAULT '',
	`name` VARCHAR(150) NULL DEFAULT NULL,
	`shortname` VARCHAR(50) NULL DEFAULT NULL,
	`licenseno` VARCHAR(50) NULL DEFAULT NULL,
	`department` VARCHAR(250) NULL DEFAULT NULL,
	`jobposition` VARCHAR(50) NULL DEFAULT NULL,
	`active` CHAR(1) NULL DEFAULT NULL,
	`force_diagnosis` CHAR(1) NULL DEFAULT NULL,
	`oldcode` VARCHAR(25) NULL DEFAULT NULL,
	`search_keyword` VARCHAR(25) NULL DEFAULT NULL,
	`cid` VARCHAR(17) NULL DEFAULT NULL,
	`position_id` INT(11) NULL DEFAULT NULL,
	`addrpart` VARCHAR(20) NULL DEFAULT NULL,
	`moopart` VARCHAR(20) NULL DEFAULT NULL,
	`zoipart` VARCHAR(20) NULL DEFAULT NULL,
	`roadpart` VARCHAR(20) NULL DEFAULT NULL,
	`tmbpart` VARCHAR(20) NULL DEFAULT NULL,
	`amppart` VARCHAR(20) NULL DEFAULT NULL,
	`chwpart` VARCHAR(20) NULL DEFAULT NULL,
	`nationality` VARCHAR(20) NULL DEFAULT NULL,
	`doctor_guid` VARCHAR(38) NULL DEFAULT NULL,
	`allow_df_edit` CHAR(1) NULL DEFAULT NULL,
	`force_icd_diagnosis` CHAR(1) NULL DEFAULT NULL,
	`ename` VARCHAR(200) NULL DEFAULT NULL,
	`spclty` CHAR(2) NULL DEFAULT NULL,
	`clinic` CHAR(3) NULL DEFAULT NULL,
	`doctor_department_id` INT(11) NULL DEFAULT NULL,
	`name_soundex` VARCHAR(150) NULL DEFAULT NULL,
	`chronic_staff` CHAR(1) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`provider_type_code` VARCHAR(3) NULL DEFAULT NULL,
	`sex` CHAR(1) NULL DEFAULT NULL,
	`council_code` VARCHAR(2) NULL DEFAULT NULL,
	`birth_date` DATE NULL DEFAULT NULL,
	`start_date` DATE NULL DEFAULT NULL,
	`finish_date` DATE NULL DEFAULT NULL,
	`move_from_hospcode` CHAR(5) NULL DEFAULT NULL,
	`move_to_hospcode` CHAR(5) NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`pname` VARCHAR(50) NULL DEFAULT NULL,
	`lname` VARCHAR(50) NULL DEFAULT NULL,
	`fname` VARCHAR(100) NULL DEFAULT NULL,
	`emp_id` INT(11) NULL DEFAULT NULL,
	`sub_spclty_id` INT(11) NULL DEFAULT NULL,
	`doctor_type_id` INT(11) NULL DEFAULT NULL,
	`hospital_list` VARCHAR(200) NULL DEFAULT NULL,
	`license_issue_date` DATE NULL DEFAULT NULL,
	`license_expire_date` DATE NULL DEFAULT NULL,
	`use_app_slot` CHAR(1) NULL DEFAULT NULL,
	`allow_online_appointment` CHAR(1) NULL DEFAULT NULL,
	`queue_prefix` VARCHAR(5) NULL DEFAULT NULL,
	`enable_qs_call` CHAR(1) NULL DEFAULT NULL,
	`no_require_qs_slot` CHAR(1) NULL DEFAULT NULL,
	`regist_no` VARCHAR(50) NULL DEFAULT NULL,
	`use_week_slot` CHAR(1) NULL DEFAULT NULL,
	`can_approve_ipd_order` CHAR(1) NULL DEFAULT NULL,
	`allow_appointment_over_slot` CHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`code`),
	INDEX `department` (`department`),
	INDEX `name` (`name`),
	INDEX `shortname` (`shortname`),
	INDEX `ix_search_keyword` (`search_keyword`),
	INDEX `ix_licenseno` (`licenseno`),
	INDEX `ix_active` (`active`),
	INDEX `ix_position_id` (`position_id`),
	INDEX `ix_name_soundex` (`name_soundex`),
	INDEX `ix_doctor_guid` (`doctor_guid`),
	INDEX `ix_emp_id` (`emp_id`),
	INDEX `ix_enable_qs_call` (`enable_qs_call`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;
