CREATE TABLE `hos`.`drugusage` (
	`drugusage` VARCHAR(7) NOT NULL DEFAULT '',
	`code` VARCHAR(200) NULL DEFAULT NULL,
	`name1` VARCHAR(150) NULL DEFAULT NULL,
	`name2` VARCHAR(150) NULL DEFAULT NULL,
	`name3` VARCHAR(150) NULL DEFAULT NULL,
	`shortlist` VARCHAR(250) NULL DEFAULT NULL,
	`idrlink` VARCHAR(100) NULL DEFAULT NULL,
	`status` CHAR(1) NULL DEFAULT NULL,
	`interval1` CHAR(1) NULL DEFAULT NULL,
	`interval2` CHAR(1) NULL DEFAULT NULL,
	`interval3` CHAR(1) NULL DEFAULT NULL,
	`interval4` CHAR(1) NULL DEFAULT NULL,
	`interval5` CHAR(1) NULL DEFAULT NULL,
	`interval6` CHAR(1) NULL DEFAULT NULL,
	`iperday` INT(11) NULL DEFAULT NULL,
	`dosageform` VARCHAR(250) NULL DEFAULT NULL,
	`ename1` VARCHAR(150) NULL DEFAULT NULL,
	`ename2` VARCHAR(150) NULL DEFAULT NULL,
	`ename3` VARCHAR(150) NULL DEFAULT NULL,
	`iperdose` DOUBLE(15,3) NULL DEFAULT NULL,
	`drugusage_guid` VARCHAR(38) NULL DEFAULT NULL,
	`divide_amount` INT(11) NULL DEFAULT NULL,
	`common_name` VARCHAR(250) NULL DEFAULT NULL,
	`drugusage_active` CHAR(1) NULL DEFAULT NULL,
	`opi_acpc_id` INT(11) NULL DEFAULT NULL,
	`opi_usage_code` VARCHAR(10) NULL DEFAULT NULL,
	`opi_dose` DOUBLE(15,3) NULL DEFAULT NULL,
	`opi_unit_name` VARCHAR(25) NULL DEFAULT NULL,
	`opi_frequency_code` VARCHAR(10) NULL DEFAULT NULL,
	`opi_usage_unit_code` VARCHAR(10) NULL DEFAULT NULL,
	`opi_time_code` VARCHAR(10) NULL DEFAULT NULL,
	`ipt_injection_sticker_count` INT(11) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`no_disp_machine` CHAR(1) NULL DEFAULT NULL,
	`use_opi_mode2` CHAR(1) NULL DEFAULT NULL,
	`display_order` INT(11) NULL DEFAULT NULL,
	`doctor_use` CHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`drugusage`),
	INDEX `code` (`code`),
	INDEX `status` (`status`),
	INDEX `ix_shortlist` (`shortlist`),
	INDEX `ix_idrlink` (`idrlink`),
	INDEX `ix_drugusage_guid` (`drugusage_guid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`),
	INDEX `ix_search1` (`code`, `name1`, `name2`, `name3`),
	INDEX `ix_search1_index` (`name2`, `name3`, `name1`, `code`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;