CREATE TABLE `hos`.`drugitems` (
	`icode` VARCHAR(7) NOT NULL DEFAULT '',
	`name` VARCHAR(100) NULL DEFAULT NULL,
	`strength` VARCHAR(50) NULL DEFAULT NULL,
	`units` VARCHAR(50) NULL DEFAULT NULL,
	`unitprice` DOUBLE(22,3) NULL DEFAULT NULL,
	`dosageform` VARCHAR(100) NULL DEFAULT NULL,
	`criticalpriority` INT(11) NULL DEFAULT NULL,
	`drugaccount` VARCHAR(2) NULL DEFAULT NULL,
	`drugcategory` VARCHAR(150) NULL DEFAULT NULL,
	`drugnote` VARCHAR(150) NULL DEFAULT NULL,
	`hintcode` VARCHAR(4) NULL DEFAULT NULL,
	`istatus` CHAR(1) NULL DEFAULT NULL,
	`lastupdatestdprice` DATETIME NULL DEFAULT NULL,
	`lockprice` CHAR(1) NULL DEFAULT NULL,
	`lockprint` CHAR(1) NULL DEFAULT NULL,
	`maxlevel` INT(11) NULL DEFAULT NULL,
	`minlevel` INT(11) NULL DEFAULT NULL,
	`maxunitperdose` INT(11) NULL DEFAULT NULL,
	`packqty` INT(11) NULL DEFAULT NULL,
	`reorderqty` INT(11) NULL DEFAULT NULL,
	`stdprice` DOUBLE(22,3) NULL DEFAULT NULL,
	`stdtaken` VARCHAR(30) NULL DEFAULT NULL,
	`therapeutic` VARCHAR(150) NULL DEFAULT NULL,
	`therapeuticgroup` VARCHAR(150) NULL DEFAULT NULL,
	`default_qty` INT(11) NULL DEFAULT NULL,
	`gpo_code` VARCHAR(7) NULL DEFAULT NULL,
	`use_right` CHAR(1) NULL DEFAULT NULL,
	`i_type` CHAR(1) NULL DEFAULT NULL,
	`drugusage` VARCHAR(30) NULL DEFAULT NULL,
	`high_cost` VARCHAR(1) NULL DEFAULT 'N',
	`must_paid` CHAR(1) NULL DEFAULT NULL,
	`alert_level` TINYINT(4) NULL DEFAULT NULL,
	`access_level` TINYINT(4) NULL DEFAULT NULL,
	`sticker_short_name` VARCHAR(150) NULL DEFAULT NULL,
	`paidst` CHAR(2) NULL DEFAULT NULL,
	`antibiotic` CHAR(1) NULL DEFAULT NULL,
	`displaycolor` INT(11) NULL DEFAULT NULL,
	`empty` CHAR(1) NULL DEFAULT NULL,
	`empty_text` TEXT NULL DEFAULT NULL,
	`unitcost` DOUBLE(15,3) NULL DEFAULT NULL,
	`gfmiscode` VARCHAR(14) NULL DEFAULT NULL,
	`ipd_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`oldcode` VARCHAR(25) NULL DEFAULT NULL,
	`habit_forming` CHAR(1) NULL DEFAULT NULL,
	`did` VARCHAR(30) NULL DEFAULT NULL,
	`stock_type` VARCHAR(4) NULL DEFAULT NULL,
	`price2` DOUBLE(15,3) NULL DEFAULT NULL,
	`price3` DOUBLE(15,3) NULL DEFAULT NULL,
	`ipd_price2` DOUBLE(15,3) NULL DEFAULT NULL,
	`ipd_price3` DOUBLE(15,3) NULL DEFAULT NULL,
	`price_lock` CHAR(1) NULL DEFAULT NULL,
	`pregnancy` VARCHAR(10) NULL DEFAULT NULL,
	`pharmacology_group1` INT(11) NULL DEFAULT NULL,
	`pharmacology_group2` INT(11) NULL DEFAULT NULL,
	`pharmacology_group3` INT(11) NULL DEFAULT NULL,
	`generic_name` VARCHAR(250) NULL DEFAULT NULL,
	`show_pregnancy_alert` CHAR(1) NULL DEFAULT NULL,
	`icode_guid` VARCHAR(38) NULL DEFAULT NULL,
	`na` CHAR(1) NULL DEFAULT NULL,
	`invcode` VARCHAR(10) NULL DEFAULT NULL,
	`check_user_group` CHAR(1) NULL DEFAULT NULL,
	`check_user_name` CHAR(1) NULL DEFAULT NULL,
	`show_notify` CHAR(1) NULL DEFAULT NULL,
	`show_notify_text` TEXT NULL DEFAULT NULL,
	`income` VARCHAR(2) NULL DEFAULT NULL,
	`print_sticker_pq` CHAR(1) NULL DEFAULT NULL,
	`charge_service_opd` CHAR(1) NULL DEFAULT NULL,
	`charge_service_ipd` CHAR(1) NULL DEFAULT NULL,
	`ename` VARCHAR(150) NULL DEFAULT NULL,
	`dose_type` CHAR(3) NULL DEFAULT NULL,
	`habit_forming_type` INT(11) NULL DEFAULT NULL,
	`no_discount` CHAR(1) NULL DEFAULT NULL,
	`therapeutic_eng` VARCHAR(200) NULL DEFAULT NULL,
	`hintcode_eng` VARCHAR(200) NULL DEFAULT NULL,
	`limit_drugusage` CHAR(1) NULL DEFAULT NULL,
	`print_sticker_header` CHAR(1) NULL DEFAULT NULL,
	`calc_idr_qty` CHAR(1) NULL DEFAULT NULL,
	`item_in_hospital` CHAR(1) NULL DEFAULT NULL,
	`no_substock` CHAR(1) NULL DEFAULT NULL,
	`volume_cc` INT(11) NULL DEFAULT NULL,
	`usage_code` VARCHAR(10) NULL DEFAULT NULL,
	`frequency_code` VARCHAR(10) NULL DEFAULT NULL,
	`time_code` VARCHAR(10) NULL DEFAULT NULL,
	`dispense_dose` DOUBLE(15,3) NULL DEFAULT NULL,
	`usage_unit_code` VARCHAR(10) NULL DEFAULT NULL,
	`dose_per_units` DOUBLE(15,3) NULL DEFAULT NULL,
	`ipd_default_pay` INT(11) NULL DEFAULT NULL,
	`billcode` VARCHAR(10) NULL DEFAULT NULL,
	`billnumber` VARCHAR(15) NULL DEFAULT NULL,
	`lockprint_ipd` CHAR(1) NULL DEFAULT NULL,
	`pregnancy_notify_text` TEXT NULL DEFAULT NULL,
	`show_breast_feeding_alert` CHAR(1) NULL DEFAULT NULL,
	`breast_feeding_alert_text` TEXT NULL DEFAULT NULL,
	`show_child_notify` CHAR(1) NULL DEFAULT NULL,
	`child_notify_text` TEXT NULL DEFAULT NULL,
	`child_notify_min_age` INT(11) NULL DEFAULT NULL,
	`child_notify_max_age` INT(11) NULL DEFAULT NULL,
	`continuous` CHAR(1) NULL DEFAULT NULL,
	`substitute_icode` CHAR(7) NULL DEFAULT NULL,
	`trade_name` VARCHAR(200) NULL DEFAULT NULL,
	`use_right_allow` CHAR(1) NULL DEFAULT NULL,
	`medication_machine_id` INT(11) NULL DEFAULT NULL,
	`ipd_medication_machine_id` INT(11) NULL DEFAULT NULL,
	`check_remed_qty` CHAR(1) NULL DEFAULT NULL,
	`addict` CHAR(1) NULL DEFAULT NULL,
	`addict_type_id` INT(11) NULL DEFAULT NULL,
	`medication_machine_opd_no` INT(11) NULL DEFAULT NULL,
	`medication_machine_ipd_no` INT(11) NULL DEFAULT NULL,
	`fp_drug` CHAR(1) NULL DEFAULT NULL,
	`usage_code_ipd` VARCHAR(10) NULL DEFAULT NULL,
	`dispense_dose_ipd` DOUBLE(15,3) NULL DEFAULT NULL,
	`usage_unit_code_ipd` VARCHAR(10) NULL DEFAULT NULL,
	`frequency_code_ipd` VARCHAR(10) NULL DEFAULT NULL,
	`time_code_ipd` VARCHAR(10) NULL DEFAULT NULL,
	`print_ipd_injection_sticker` CHAR(1) NULL DEFAULT NULL,
	`provis_medication_unit_code` VARCHAR(10) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`sks_product_category_id` INT(11) NULL DEFAULT NULL,
	`sks_clain_control_type_id` INT(11) NULL DEFAULT NULL,
	`sks_drug_code` VARCHAR(25) NULL DEFAULT NULL,
	`sks_dfs_code` VARCHAR(50) NULL DEFAULT NULL,
	`sks_dfs_text` VARCHAR(150) NULL DEFAULT NULL,
	`sks_reimb_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`check_druginteraction_history` CHAR(1) NULL DEFAULT NULL,
	`check_druginteraction_history_day` INT(11) NULL DEFAULT NULL,
	`nhso_adp_type_id` INT(11) NULL DEFAULT NULL,
	`nhso_adp_code` VARCHAR(15) NULL DEFAULT NULL,
	`sks_claim_control_type_id` INT(11) NULL DEFAULT NULL,
	`begin_date` DATE NULL DEFAULT NULL,
	`finish_date` DATE NULL DEFAULT NULL,
	`name_pr` VARCHAR(100) NULL DEFAULT NULL,
	`name_eng` VARCHAR(100) NULL DEFAULT NULL,
	`capacity_name` VARCHAR(100) NULL DEFAULT NULL,
	`finish_reason` VARCHAR(100) NULL DEFAULT NULL,
	`extra_unitcost` DOUBLE(15,3) NULL DEFAULT NULL,
	`drug_control_type_id` INT(11) NULL DEFAULT NULL,
	`name_print` VARCHAR(100) NULL DEFAULT NULL,
	`active_ingredient_mg` DOUBLE(15,3) NULL DEFAULT NULL,
	`no_order_g6pd` CHAR(1) NULL DEFAULT NULL,
	`gender_check` CHAR(1) NULL DEFAULT NULL,
	`no_order_gender` CHAR(1) NULL DEFAULT NULL,
	`max_qty` INT(11) NULL DEFAULT NULL,
	`prefer_opd_usage_code` CHAR(1) NULL DEFAULT NULL,
	`capacity_qty` DOUBLE(15,3) NULL DEFAULT NULL,
	`need_order_reason` CHAR(1) NULL DEFAULT NULL,
	`drugitems_due_type_id` INT(11) NULL DEFAULT NULL,
	`drugeval_head_id` INT(11) NULL DEFAULT NULL,
	`light_protect` CHAR(1) NULL DEFAULT NULL,
	`tpu_code_list` VARCHAR(200) NULL DEFAULT NULL,
	`inv_map_update` CHAR(1) NULL DEFAULT NULL,
	`special_advice_text` TEXT NULL DEFAULT NULL,
	`precaution_advice_text` TEXT NULL DEFAULT NULL,
	`contra_advice_text` TEXT NULL DEFAULT NULL,
	`storage_advice_text` TEXT NULL DEFAULT NULL,
	`qr_code_url` VARCHAR(200) NULL DEFAULT NULL,
	`vat_percent` DOUBLE(15,3) NULL DEFAULT NULL,
	`acc_regist` CHAR(1) NULL DEFAULT NULL,
	`use_paidst` CHAR(1) NULL DEFAULT NULL,
	`thai_name` VARCHAR(200) NULL DEFAULT NULL,
	`fwf_item_id` INT(11) NULL DEFAULT NULL,
	`drugitems_em1_id` INT(11) NULL DEFAULT NULL,
	`drugitems_em2_id` INT(11) NULL DEFAULT NULL,
	`drugitems_em3_id` INT(11) NULL DEFAULT NULL,
	`drugitems_em4_id` INT(11) NULL DEFAULT NULL,
	`tmt_tp_code` VARCHAR(10) NULL DEFAULT NULL,
	`tmt_gp_code` VARCHAR(10) NULL DEFAULT NULL,
	`limit_pttype` CHAR(1) NULL DEFAULT NULL,
	`noshow_narcotic` CHAR(1) NULL DEFAULT NULL,
	`medication_machine_flag` CHAR(1) NULL DEFAULT NULL,
	`sks_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`print_sticker_by_frequency` CHAR(1) NULL DEFAULT NULL,
	`print_sticker_pq_ipd` CHAR(1) NULL DEFAULT NULL,
	`sub_income` VARCHAR(3) NULL DEFAULT NULL,
	`prefer_ipd_usage_code` CHAR(1) NULL DEFAULT NULL,
	`default_qty_ipd` INT(11) NULL DEFAULT NULL,
	`max_qty_ipd` INT(11) NULL DEFAULT NULL,
	`drugusage_ipd` VARCHAR(30) NULL DEFAULT NULL,
	`no_popup_ipd_reason` CHAR(1) NULL DEFAULT NULL,
	`specprep` VARCHAR(10) NULL DEFAULT NULL,
	`med_dose_calc_type_id` INT(11) NULL DEFAULT NULL,
	`send_line_notify` CHAR(1) NULL DEFAULT NULL,
	`show_qrcode_trade` CHAR(1) NULL DEFAULT NULL,
	`warn_g6pd` CHAR(1) NULL DEFAULT NULL,
	`ipd_rx_freq_day` INT(11) NULL DEFAULT NULL,
	`displaycolor_focus` INT(11) NULL DEFAULT NULL,
	`last_update` DATETIME NULL DEFAULT NULL,
	`no_remed` CHAR(1) NULL DEFAULT NULL,
	`force_round_qty` CHAR(1) NULL DEFAULT NULL,
	`atc_code` VARCHAR(10) NULL DEFAULT NULL,
	`state_item_id` INT(11) NULL DEFAULT NULL,
	`multiply_charge_service` CHAR(1) NULL DEFAULT NULL,
	`csmbs_claim_cat` VARCHAR(1) NULL DEFAULT NULL,
	`simb_2005` VARCHAR(10) NULL DEFAULT NULL,
	`sks_rev_date` DATE NULL DEFAULT NULL,
	`sct_unit_code` VARCHAR(20) NULL DEFAULT NULL,
	`print_label` CHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`icode`),
	INDEX `dosageform` (`dosageform`),
	INDEX `drugaccount` (`drugaccount`),
	INDEX `drugcategory` (`drugcategory`),
	INDEX `drugnote` (`drugnote`),
	INDEX `hintcode` (`hintcode`),
	INDEX `istatus` (`istatus`),
	INDEX `name` (`name`),
	INDEX `packqty` (`packqty`),
	INDEX `strength` (`strength`),
	INDEX `therapeutic` (`therapeutic`),
	INDEX `therapeuticgroup` (`therapeuticgroup`),
	INDEX `units` (`units`),
	INDEX `ix_ix_oldcode` (`oldcode`),
	INDEX `ix_ix_ix_income` (`income`),
	INDEX `ix_no_discount` (`no_discount`),
	INDEX `ix_generic_name` (`generic_name`),
	INDEX `ix_show_child_notify` (`show_child_notify`),
	INDEX `ix_icode_guid` (`icode_guid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`),
	INDEX `ix_cdh` (`check_druginteraction_history`),
	INDEX `nhso_adp_code` (`nhso_adp_code`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;