CREATE TABLE `hos`.`er_image` (
	`vn` VARCHAR(13) NOT NULL DEFAULT '',
	`image1` LONGBLOB NULL DEFAULT NULL,
	`image2` LONGBLOB NULL DEFAULT NULL,
	`image3` LONGBLOB NULL DEFAULT NULL,
	`image4` LONGBLOB NULL DEFAULT NULL,
	`image5` LONGBLOB NULL DEFAULT NULL,
	`image1_note` TEXT NULL DEFAULT NULL,
	`image2_note` TEXT NULL DEFAULT NULL,
	`image3_note` TEXT NULL DEFAULT NULL,
	`image4_note` TEXT NULL DEFAULT NULL,
	`image5_note` TEXT NULL DEFAULT NULL,
	`hos_guid` CHAR(38) NULL DEFAULT NULL,
	PRIMARY KEY (`vn`),
	INDEX `ix_hos_guid` (`hos_guid`)
) COLLATE='tis620_thai_ci' ENGINE=MyISAM;
