CREATE TABLE `hos`.`er_regist` (
	`vn` VARCHAR(13) NOT NULL DEFAULT '',
	`vstdate` DATE NULL DEFAULT NULL,
	`er_period` INT(4) NULL DEFAULT NULL,
	`er_pt_type` INT(4) NULL DEFAULT NULL,
	`er_emergency_type` INT(4) NULL DEFAULT NULL,
	`er_dch_type` INT(4) NULL DEFAULT NULL,
	`er_doctor` VARCHAR(7) NULL DEFAULT NULL,
	`er_legal_action` CHAR(1) NULL DEFAULT NULL,
	`er_time_1` TIME NULL DEFAULT NULL,
	`er_time_2` TIME NULL DEFAULT NULL,
	`er_time_3` TIME NULL DEFAULT NULL,
	`dba` CHAR(1) NULL DEFAULT NULL,
	`er_list` VARCHAR(250) NULL DEFAULT NULL,
	`oper_note` VARCHAR(250) NULL DEFAULT NULL,
	`enter_er_time` DATETIME NULL DEFAULT NULL,
	`doctor_tx_time` DATETIME NULL DEFAULT NULL,
	`finish_time` DATETIME NULL DEFAULT NULL,
	`vn_guid` VARCHAR(38) NULL DEFAULT NULL,
	`observe` CHAR(1) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`ems_command_list_id` INT(11) NULL DEFAULT NULL,
	`er_screen` CHAR(1) NULL DEFAULT NULL,
	`er_emergency_level_id` INT(11) NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`update_staff` VARCHAR(50) NULL DEFAULT NULL,
	`er_depcode` VARCHAR(3) NULL DEFAULT NULL,
	`leave_datetime` DATETIME NULL DEFAULT NULL,
	`er_leave_status_id` INT(11) NULL DEFAULT NULL,
	`er_indication_type_id` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`vn`),
	INDEX `ix_vstdate` (`vstdate`),
	INDEX `ix_er_doctor` (`er_doctor`),
	INDEX `ix_er_period` (`er_period`),
	INDEX `ix_er_pt_type` (`er_pt_type`),
	INDEX `ix_vn_guid` (`vn_guid`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;