CREATE TABLE `hos`.`hospcode` (
	`amppart` CHAR(2) NULL DEFAULT NULL,
	`chwpart` CHAR(2) NULL DEFAULT NULL,
	`hospcode` VARCHAR(9) NOT NULL DEFAULT '',
	`hosptype` VARCHAR(50) NULL DEFAULT NULL,
	`name` VARCHAR(100) NULL DEFAULT NULL,
	`tmbpart` CHAR(2) NULL DEFAULT NULL,
	`moopart` VARCHAR(3) NULL DEFAULT NULL,
	`sss_code` VARCHAR(12) NULL DEFAULT NULL,
	`sss_code_sub` VARCHAR(12) NULL DEFAULT NULL,
	`hospcode506` VARCHAR(15) NULL DEFAULT NULL,
	`hospital_type_id` INT(11) NULL DEFAULT NULL,
	`bed_count` INT(11) NULL DEFAULT NULL,
	`po_code` VARCHAR(5) NULL DEFAULT NULL,
	`hospital_level_id` INT(11) NULL DEFAULT NULL,
	`hospital_phone` VARCHAR(50) NULL DEFAULT NULL,
	`hospital_fax` VARCHAR(50) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`province_name` VARCHAR(100) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`export` VARCHAR(1) NULL DEFAULT NULL,
	`bed_real` INT(11) NULL DEFAULT NULL,
	`addrpart` VARCHAR(150) NULL DEFAULT NULL,
	`area_code` VARCHAR(2) NULL DEFAULT NULL,
	`zone` VARCHAR(2) NULL DEFAULT NULL,
	PRIMARY KEY (`hospcode`),
	INDEX `amppart` (`amppart`),
	INDEX `chwpart` (`chwpart`),
	INDEX `hosptype` (`hosptype`),
	INDEX `name` (`name`),
	INDEX `tmbpart` (`tmbpart`),
	INDEX `tmbpart_amppart` (`tmbpart`, `amppart`, `chwpart`),
	INDEX `ix_sss_code` (`sss_code`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`),
	INDEX `ix_tmbpart_amppart` (`amppart`, `chwpart`, `tmbpart`),
	INDEX `ix_tmbpart_amppart_index` (`amppart`, `chwpart`, `tmbpart`)
) COLLATE='tis620_thai_ci' ENGINE=MyISAM;