CREATE TABLE `hos`.`icd101` (
	`code` VARCHAR(7) NOT NULL DEFAULT '',
	`name` VARCHAR(200) NULL DEFAULT NULL,
	`spclty` CHAR(2) NULL DEFAULT NULL,
	`tname` VARCHAR(150) NULL DEFAULT NULL,
	`code3` CHAR(3) NULL DEFAULT NULL,
	`code4` CHAR(1) NULL DEFAULT NULL,
	`code5` CHAR(1) NULL DEFAULT NULL,
	`sex` INT(11) NULL DEFAULT NULL,
	`ipd_valid` CHAR(1) NULL DEFAULT NULL,
	`icd10compat` CHAR(1) NULL DEFAULT NULL,
	`icd10tmcompat` CHAR(1) NULL DEFAULT NULL,
	`active_status` VARCHAR(1) NULL DEFAULT NULL,
	`hos_guid` CHAR(38) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`codeset` VARCHAR(5) NULL DEFAULT NULL,
	PRIMARY KEY (`code`),
	INDEX `code3` (`code3`),
	INDEX `code4` (`code4`),
	INDEX `code5` (`code5`),
	INDEX `name` (`name`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;