CREATE TABLE `hos`.`ipt` (
	`an` VARCHAR(13) NOT NULL DEFAULT '',
	`admdoctor` VARCHAR(7) NULL DEFAULT NULL,
	`dchdate` DATE NULL DEFAULT NULL,
	`dchstts` CHAR(2) NULL DEFAULT NULL,
	`dchtime` TIME NULL DEFAULT NULL,
	`dchtype` CHAR(2) NULL DEFAULT NULL,
	`dthdiagdct` VARCHAR(7) NULL DEFAULT NULL,
	`hn` VARCHAR(9) NULL DEFAULT NULL,
	`ivstist` CHAR(2) NULL DEFAULT NULL,
	`ivstost` VARCHAR(4) NULL DEFAULT NULL,
	`lockdx` TINYINT(4) NULL DEFAULT NULL,
	`prediag` VARCHAR(250) NULL DEFAULT NULL,
	`pttype` CHAR(2) NULL DEFAULT NULL,
	`regdate` DATE NULL DEFAULT NULL,
	`regtime` TIME NULL DEFAULT NULL,
	`rfrics` CHAR(1) NULL DEFAULT NULL,
	`rfrilct` VARCHAR(5) NULL DEFAULT NULL,
	`rfrocs` CHAR(1) NULL DEFAULT NULL,
	`rfrolct` VARCHAR(5) NULL DEFAULT NULL,
	`spclty` CHAR(2) NULL DEFAULT NULL,
	`vn` VARCHAR(13) NULL DEFAULT NULL,
	`ward` VARCHAR(4) NULL DEFAULT NULL,
	`rcpt_disease` VARCHAR(100) NULL DEFAULT NULL,
	`dch_doctor` VARCHAR(7) NULL DEFAULT NULL,
	`ipt_type` TINYINT(4) NULL DEFAULT NULL,
	`iref_type` VARCHAR(4) NULL DEFAULT NULL,
	`ipacc` INT(11) NULL DEFAULT NULL,
	`act_money_limit` DOUBLE(15,3) NULL DEFAULT NULL,
	`drg` VARCHAR(5) NULL DEFAULT NULL,
	`mdc` CHAR(2) NULL DEFAULT NULL,
	`rw` DOUBLE(15,5) NULL DEFAULT NULL,
	`wtlos` DOUBLE(15,3) NULL DEFAULT NULL,
	`ot` INT(11) NULL DEFAULT NULL,
	`result` CHAR(1) NULL DEFAULT NULL,
	`gravidity` TINYINT(4) NULL DEFAULT NULL,
	`parity` TINYINT(4) NULL DEFAULT NULL,
	`living_children` TINYINT(4) NULL DEFAULT NULL,
	`rxdoctor` VARCHAR(7) NULL DEFAULT NULL,
	`staff` VARCHAR(25) NULL DEFAULT NULL,
	`bw` INT(11) NULL DEFAULT NULL,
	`first_ward` VARCHAR(4) NULL DEFAULT NULL,
	`refer_out_number` VARCHAR(15) NULL DEFAULT NULL,
	`incharge_doctor` VARCHAR(7) NULL DEFAULT NULL,
	`an_guid` VARCHAR(38) NULL DEFAULT NULL,
	`an_lock` CHAR(1) NULL DEFAULT NULL,
	`ergent` CHAR(1) NULL DEFAULT NULL,
	`chart_state` CHAR(1) NULL DEFAULT NULL,
	`receive_chart_date_time` DATETIME NULL DEFAULT NULL,
	`receive_chart_staff` VARCHAR(25) NULL DEFAULT NULL,
	`receive_chart_note` VARCHAR(100) NULL DEFAULT NULL,
	`adjrw` DOUBLE(15,5) NULL DEFAULT NULL,
	`ipt_spclty` CHAR(2) NULL DEFAULT NULL,
	`finance_lock` CHAR(1) NULL DEFAULT NULL,
	`last_check_autoincome` DATETIME NULL DEFAULT NULL,
	`admit_fee_guid` VARCHAR(38) NULL DEFAULT NULL,
	`leave_home_day` INT(11) NULL DEFAULT NULL,
	`operation_status` CHAR(1) NULL DEFAULT NULL,
	`finance_summary_date` DATE NULL DEFAULT NULL,
	`estimate_discharge_date` DATE NULL DEFAULT NULL,
	`old_cause_revisit` CHAR(1) NULL DEFAULT NULL,
	`finance_transfer` CHAR(1) NULL DEFAULT NULL,
	`provision_dx` VARCHAR(200) NULL DEFAULT NULL,
	`dw_hhc_list_id` INT(11) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`body_height` INT(11) NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`cur_dep_code` CHAR(3) NULL DEFAULT NULL,
	`finance_status_flag` INT(11) NULL DEFAULT NULL,
	`ipt_admit_type_id` INT(11) NULL DEFAULT NULL,
	`no_visit` CHAR(1) NULL DEFAULT NULL,
	`no_food` CHAR(1) NULL DEFAULT NULL,
	`confirm_discharge` CHAR(1) NULL DEFAULT NULL,
	`lab_status` CHAR(1) NULL DEFAULT NULL,
	`xray_status` CHAR(1) NULL DEFAULT NULL,
	`grouper_version` VARCHAR(15) NULL DEFAULT NULL,
	`grouper_err` INT(11) NULL DEFAULT NULL,
	`grouper_warn` INT(11) NULL DEFAULT NULL,
	`grouper_actlos` INT(11) NULL DEFAULT NULL,
	`auto_charge_amount` DOUBLE(15,3) NULL DEFAULT NULL,
	`provision_dx_icd` VARCHAR(9) NULL DEFAULT NULL,
	`ipt_cause_type_id` INT(11) NULL DEFAULT NULL,
	`ipt_severe_type_id` INT(11) NULL DEFAULT NULL,
	`ipt_cause_type_note` VARCHAR(150) NULL DEFAULT NULL,
	`followup` CHAR(1) NULL DEFAULT NULL,
	`dch_severe_type_id` INT(11) NULL DEFAULT NULL,
	`opd_finance_wait_tr` DOUBLE(15,3) NULL DEFAULT NULL,
	`home_leave_status` CHAR(1) NULL DEFAULT NULL,
	`grouper_adjrw_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`reimburse_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`err` INT(2) NULL DEFAULT NULL,
	`warn` INT(4) NULL DEFAULT NULL,
	`oldcode` VARCHAR(20) NULL DEFAULT NULL,
	`data_ok` CHAR(1) NULL DEFAULT NULL,
	`data_exp_date` DATE NULL DEFAULT NULL,
	`ipt_summary_status_id` INT(11) NULL DEFAULT NULL,
	`no_charge_room` CHAR(1) NULL DEFAULT NULL,
	`rx_home_med` CHAR(1) NULL DEFAULT NULL,
	`hhc_hospcode` VARCHAR(5) NULL DEFAULT NULL,
	`cur_bedno` VARCHAR(6) NULL DEFAULT NULL,
	`operation_status_id` INT(11) NULL DEFAULT NULL,
	`ipd_nurse_eval_range_code` CHAR(2) NULL DEFAULT NULL,
	`icd10` VARCHAR(100) NULL DEFAULT NULL,
	`pass` VARCHAR(1) NULL DEFAULT 'n',
	`ODS` VARCHAR(3) NULL DEFAULT NULL,
	PRIMARY KEY (`an`),
	INDEX `admdoctor` (`admdoctor`),
	INDEX `dchdate` (`dchdate`),
	INDEX `dchstts` (`dchstts`),
	INDEX `dchstts_ward` (`dchstts`, `ward`),
	INDEX `hn` (`hn`),
	INDEX `hn_dchdate_dchstts` (`hn`, `dchdate`, `dchstts`),
	INDEX `ipt_type` (`ipt_type`),
	INDEX `pttype` (`pttype`),
	INDEX `regdate` (`regdate`),
	INDEX `regtime` (`regtime`),
	INDEX `spclty` (`spclty`),
	INDEX `vn` (`vn`),
	INDEX `ward` (`ward`),
	INDEX `ix_an_guid` (`an_guid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`),
	INDEX `ix_confirm_discharge` (`confirm_discharge`),
	INDEX `ix_hn_dchdate_dchstts` (`dchdate`, `dchstts`, `hn`),
	INDEX `ix_an_hn` (`an`, `hn`),
	INDEX `ix_data_ok_date` (`data_ok`, `data_exp_date`),
	INDEX `ix_data_ok_dchdate` (`data_ok`, `dchdate`),
	INDEX `ix_data_ok_date_index` (`data_exp_date`, `data_ok`),
	INDEX `ix_dchstts_ward` (`ward`, `dchstts`),
	INDEX `ix_an_hn_index` (`an`, `hn`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;