CREATE TABLE `hos`.`ipt_order_no` (
	`ipt_order_id` INT(11) NOT NULL DEFAULT 0,
	`an` VARCHAR(13) NULL DEFAULT NULL,
	`rxdate` DATE NULL DEFAULT NULL,
	`order_no` INT(11) NULL DEFAULT NULL,
	`order_type` CHAR(3) NULL DEFAULT NULL,
	`entry_staff` VARCHAR(25) NULL DEFAULT NULL,
	`ward` VARCHAR(4) NULL DEFAULT NULL,
	`rxtime` TIME NULL DEFAULT NULL,
	`order_locked` CHAR(1) NULL DEFAULT NULL,
	`item_count` INT(11) NULL DEFAULT NULL,
	`amount` DOUBLE(15,3) NULL DEFAULT NULL,
	`confirm_prepare` CHAR(1) NULL DEFAULT NULL,
	`confirm_pay` CHAR(1) NULL DEFAULT NULL,
	`day_queue` VARCHAR(100) NULL DEFAULT NULL,
	`confirm_staff` VARCHAR(50) NULL DEFAULT NULL,
	`confirm_datetime` DATETIME NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`depcode` VARCHAR(3) NULL DEFAULT NULL,
	`day_queue_number` INT(11) NULL DEFAULT NULL,
	`order_type_key_id` INT(11) NULL DEFAULT NULL,
	`prepare_staff` VARCHAR(25) NULL DEFAULT NULL,
	`pay_staff` VARCHAR(25) NULL DEFAULT NULL,
	`prepare_doctor_code` VARCHAR(15) NULL DEFAULT NULL,
	`pay_doctor_code` VARCHAR(15) NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`pay_datetime` DATETIME NULL DEFAULT NULL,
	`doctor_code` VARCHAR(15) NULL DEFAULT NULL,
	`pay_depcode` CHAR(3) NULL DEFAULT NULL,
	`medication_count` INT(11) NULL DEFAULT NULL,
	`med_supply_count` INT(11) NULL DEFAULT NULL,
	`req_stock_department_id` INT(11) NULL DEFAULT NULL,
	`med_item_md14_count` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`ipt_order_id`),
	INDEX `ix_ix_an` (`an`),
	INDEX `ix_ix_order_no` (`order_no`),
	INDEX `ix_ix_rxdate` (`rxdate`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_day_queue_index` (`rxdate`, `day_queue_number`),
	INDEX `ix_day_queue_index_index` (`day_queue_number`, `rxdate`),
	INDEX `ix_an_date_type` (`an`, `rxdate`, `order_type`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;