CREATE TABLE `hos`.`ipt_newborn` (
	`an` VARCHAR(13) NOT NULL DEFAULT '',
	`birth_weight` INT(11) NULL DEFAULT NULL,
	`dead` CHAR(1) NULL DEFAULT NULL,
	`preg_no` TINYINT(4) NULL DEFAULT NULL,
	`doctor` VARCHAR(15) NULL DEFAULT NULL,
	`born_date` DATE NULL DEFAULT NULL,
	`born_time` TIME NULL DEFAULT NULL,
	`note` TEXT NULL DEFAULT NULL,
	`apgar1` TINYINT(4) NULL DEFAULT NULL,
	`apgar2` TINYINT(4) NULL DEFAULT NULL,
	`birthcondition1` TINYINT(4) NULL DEFAULT NULL,
	`birthcondition2` TINYINT(4) NULL DEFAULT NULL,
	`anc_complete` CHAR(1) NULL DEFAULT NULL,
	`mother_an` VARCHAR(9) NULL DEFAULT NULL,
	`father_an` VARCHAR(9) NULL DEFAULT NULL,
	`newborn_death_cause_id` INT(11) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`has_asphyxia` CHAR(1) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	PRIMARY KEY (`an`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;