CREATE TABLE `hos`.`iptadm` (
	`an` VARCHAR(13) NOT NULL DEFAULT '',
	`admday` INT(11) NULL DEFAULT NULL,
	`bedno` VARCHAR(6) NULL DEFAULT NULL,
	`bedtype` CHAR(2) NULL DEFAULT NULL,
	`indate` DATE NULL DEFAULT NULL,
	`intime` TIME NULL DEFAULT NULL,
	`outdate` DATE NULL DEFAULT NULL,
	`outtime` TIME NULL DEFAULT NULL,
	`rate` DOUBLE(22,3) NULL DEFAULT NULL,
	`roomno` VARCHAR(4) NULL DEFAULT NULL,
	`move_in_ward_datetime` DATETIME NULL DEFAULT NULL,
	`move_in_bed_datetime` DATETIME NULL DEFAULT NULL,
	`trx_order_checksum` VARCHAR(150) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`no_rx_machine` CHAR(1) NULL DEFAULT NULL,
	`active_med_profile_count` INT(11) NULL DEFAULT NULL,
	`rx_transaction_id` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`an`),
	INDEX `bedno` (`bedno`),
	INDEX `bedtype` (`bedtype`),
	INDEX `indate` (`indate`),
	INDEX `intime` (`intime`),
	INDEX `outdate` (`outdate`),
	INDEX `outtime` (`outtime`),
	INDEX `roomno` (`roomno`),
	INDEX `roomno_an` (`roomno`, `an`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`),
	INDEX `ix_roomno_an` (`an`, `roomno`),
	INDEX `ix_roomno_an_index` (`an`, `roomno`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;
