CREATE TABLE `hos`.`iptoprt` (
	`iptoprt_id` INT(11) NOT NULL DEFAULT 0,
	`an` VARCHAR(9) NULL DEFAULT NULL,
	`doctor` VARCHAR(6) NULL DEFAULT NULL,
	`enddate` DATE NULL DEFAULT NULL,
	`endtime` TIME NULL DEFAULT NULL,
	`icd9` VARCHAR(9) NULL DEFAULT NULL,
	`icode` VARCHAR(7) NULL DEFAULT NULL,
	`iprice` DOUBLE(22,3) NULL DEFAULT NULL,
	`iqty` INT(11) NULL DEFAULT NULL,
	`opdate` DATE NULL DEFAULT NULL,
	`optime` TIME NULL DEFAULT NULL,
	`priority` TINYINT(4) NULL DEFAULT NULL,
	`ext_code` CHAR(2) NULL DEFAULT NULL,
	`oper_type` INT(11) NULL DEFAULT NULL,
	`ovst_oper_type` INT(11) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`entry_datetime` DATETIME NULL DEFAULT NULL,
	`modify_datetime` DATETIME NULL DEFAULT NULL,
	`staff` VARCHAR(50) NULL DEFAULT NULL,
	`link_table` VARCHAR(100) NULL DEFAULT NULL,
	`link_id` INT(11) NULL DEFAULT NULL,
	`oper_note_text` TEXT NULL DEFAULT NULL,
	`diag_ext_type_id` INT(11) NULL DEFAULT NULL,
	`dx_guid` VARCHAR(38) NULL DEFAULT NULL,
	PRIMARY KEY (`iptoprt_id`),
	INDEX `ix_an` (`an`),
	INDEX `ix_endtime_enddate` (`endtime`, `enddate`, `optime`, `icd9`, `opdate`, `an`, `doctor`),
	INDEX `ix_icd9` (`icd9`),
	INDEX `ix_icd9_an` (`icd9`, `an`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`),
	INDEX `ix_opdate` (`opdate`),
	INDEX `ix_optime` (`optime`),
	INDEX `ix_link_name` (`link_table`, `link_id`),
	INDEX `ix_dx_guid` (`dx_guid`),
	INDEX `ix_endtime_enddate_index` (`an`, `doctor`, `enddate`, `endtime`, `icd9`, `opdate`, `optime`),
	INDEX `ix_icd9_an_index` (`an`, `icd9`),
	INDEX `ix_link_name_index` (`link_id`, `link_table`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;
