CREATE TABLE `hos`.`lab_order` (
	`lab_order_number` INT(11) NOT NULL DEFAULT 0,
	`lab_items_code` INT(11) NOT NULL DEFAULT 0,
	`lab_order_result` VARCHAR(250) NULL DEFAULT NULL,
	`lab_order_remark` VARCHAR(250) NULL DEFAULT NULL,
	`staff` VARCHAR(50) NULL DEFAULT NULL,
	`confirm` CHAR(1) NULL DEFAULT NULL,
	`lab_items_name_ref` VARCHAR(250) NULL DEFAULT NULL,
	`lab_items_normal_value_ref` VARCHAR(150) NULL DEFAULT NULL,
	`specimen_code` INT(11) NULL DEFAULT NULL,
	`lab_items_sub_group_code` INT(11) NULL DEFAULT NULL,
	`order_type` CHAR(1) NULL DEFAULT NULL,
	`item_cost` DOUBLE(15,3) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`staff_lock_result` CHAR(1) NULL DEFAULT NULL,
	`laborder_date` DATE NULL DEFAULT NULL,
	`abnormal_result` CHAR(1) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`check_key` VARCHAR(50) NULL DEFAULT NULL,
	`lab_result_status` INT(11) NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`lab_hist_compare_type_id` INT(11) NULL DEFAULT NULL,
	`printed` CHAR(1) NULL DEFAULT NULL,
	`printed_datetime` DATETIME NULL DEFAULT NULL,
	`critical_result` CHAR(1) NULL DEFAULT NULL,
	`check_key_a` VARCHAR(50) NULL DEFAULT NULL,
	`send_notify` CHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`lab_order_number`, `lab_items_code`),
	INDEX `lab_order_number` (`lab_order_number`),
	INDEX `ix_lab_items_code` (`lab_items_code`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_laborder_date` (`laborder_date`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;