CREATE TABLE `hos`.`lab_order_service` (
	`lab_order_service_id` INT(11) NOT NULL DEFAULT 0,
	`lab_order_number` INT(11) NULL DEFAULT NULL,
	`lab_order_type` VARCHAR(15) NULL DEFAULT NULL,
	`lab_code` INT(11) NULL DEFAULT NULL,
	`lab_name` VARCHAR(250) NULL DEFAULT NULL,
	`price` DOUBLE(15,3) NULL DEFAULT NULL,
	`opi_guid` VARCHAR(38) NULL DEFAULT NULL,
	`icode` VARCHAR(7) NULL DEFAULT NULL,
	`vn` VARCHAR(13) NULL DEFAULT NULL,
	`department` CHAR(3) NULL DEFAULT NULL,
	`lab_order_service_guid` VARCHAR(38) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`ref_order_number` INT(11) NULL DEFAULT NULL,
	`specimen_code` INT(11) NULL DEFAULT NULL,
	`est_wait_minute` INT(11) NULL DEFAULT NULL,
	`update_flag` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`lab_order_service_id`),
	INDEX `ix_lab_order_number` (`lab_order_number`),
	INDEX `ix_opi_guid` (`opi_guid`),
	INDEX `ix_vn` (`vn`),
	INDEX `ix_lab_order_service_guid` (`lab_order_service_guid`),
	INDEX `ix_ref_no` (`ref_order_number`),
	INDEX `ix_order_type_code` (`lab_order_number`, `lab_order_type`, `lab_code`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;