CREATE TABLE `hos`.`lab_form` (
	`form_name` VARCHAR(250) NOT NULL DEFAULT '',
	`lab_items_code` INT(11) NULL DEFAULT NULL,
	`form_position_left` INT(11) NULL DEFAULT NULL,
	`form_position_top` INT(11) NULL DEFAULT NULL,
	`tab_order` TINYINT(4) NULL DEFAULT NULL,
	`form_position_width` INT(11) NULL DEFAULT NULL,
	`component_name` VARCHAR(200) NOT NULL DEFAULT '',
	`parent_name` VARCHAR(200) NULL DEFAULT NULL,
	`component_type` VARCHAR(25) NULL DEFAULT NULL,
	`component_caption` VARCHAR(250) NULL DEFAULT NULL,
	`checked` CHAR(1) NULL DEFAULT NULL,
	`form_position_height` INT(11) NULL DEFAULT NULL,
	`font_name` VARCHAR(50) NULL DEFAULT NULL,
	`font_size` INT(11) NULL DEFAULT NULL,
	`font_color` INT(11) NULL DEFAULT NULL,
	`specimen_code` INT(11) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	PRIMARY KEY (`form_name`, `component_name`),
	INDEX `form_name` (`form_name`),
	INDEX `form_name_lab_items_code` (`form_name`, `lab_items_code`),
	INDEX `lab_items_code` (`lab_items_code`),
	INDEX `ix_hos_guid` (`hos_guid`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;