CREATE TABLE `hos`.`lab_head` (
	`lab_order_number` INT(11) NOT NULL DEFAULT 0,
	`doctor_code` VARCHAR(7) NULL DEFAULT NULL,
	`lab_items_group_code` INT(11) NULL DEFAULT NULL,
	`vn` VARCHAR(13) NULL DEFAULT NULL,
	`lab_head_remark` VARCHAR(250) NULL DEFAULT NULL,
	`hn` VARCHAR(9) NULL DEFAULT NULL,
	`order_date` DATE NULL DEFAULT NULL,
	`report_date` DATE NULL DEFAULT NULL,
	`reporter_name` VARCHAR(100) NULL DEFAULT NULL,
	`report_time` TIME NULL DEFAULT NULL,
	`confirm_specimen` CHAR(1) NULL DEFAULT NULL,
	`confirm_report` CHAR(1) NULL DEFAULT NULL,
	`department` VARCHAR(5) NULL DEFAULT NULL,
	`form_name` VARCHAR(200) NULL DEFAULT NULL,
	`sub_group_list` VARCHAR(200) NULL DEFAULT NULL,
	`order_time` TIME NULL DEFAULT NULL,
	`receive_date` DATE NULL DEFAULT NULL,
	`receive_time` TIME NULL DEFAULT NULL,
	`ward` CHAR(2) NULL DEFAULT NULL,
	`result_note` TEXT NULL DEFAULT NULL,
	`lock_result` CHAR(1) NULL DEFAULT NULL,
	`result_rtf` LONGTEXT NULL DEFAULT NULL,
	`order_note` TEXT NULL DEFAULT NULL,
	`lab_receive_number` INT(11) NULL DEFAULT NULL,
	`approve_staff` VARCHAR(25) NULL DEFAULT NULL,
	`anonymous` CHAR(1) NULL DEFAULT NULL,
	`appointment` CHAR(1) NULL DEFAULT NULL,
	`appointment_date` DATE NULL DEFAULT NULL,
	`appointment_time` TIME NULL DEFAULT NULL,
	`lis_order_no` VARCHAR(25) NULL DEFAULT NULL,
	`confirm_charge_money` CHAR(1) NULL DEFAULT NULL,
	`finance_lab_confirm` CHAR(1) NULL DEFAULT NULL,
	`lab_order_number_guid` VARCHAR(38) NULL DEFAULT NULL,
	`anonymous_request` CHAR(1) NULL DEFAULT NULL,
	`clinic` CHAR(3) NULL DEFAULT NULL,
	`send_to_cashier` CHAR(1) NULL DEFAULT NULL,
	`receive_computer` VARCHAR(25) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`order_department` CHAR(3) NULL DEFAULT NULL,
	`lab_perform_status_id` INT(11) NULL DEFAULT NULL,
	`lab_room_id` INT(11) NULL DEFAULT NULL,
	`notify_depcode` VARCHAR(3) NULL DEFAULT NULL,
	`lab_priority_id` INT(11) NULL DEFAULT NULL,
	`spclty` CHAR(2) NULL DEFAULT NULL,
	`finance_lock` CHAR(1) NULL DEFAULT NULL,
	`report_lock` CHAR(1) NULL DEFAULT NULL,
	`report_lock_datetime` DATETIME NULL DEFAULT NULL,
	`report_lock_computer` VARCHAR(50) NULL DEFAULT NULL,
	`batch_number` INT(11) NULL DEFAULT NULL,
	`abnormal_result` CHAR(1) NULL DEFAULT NULL,
	`lis_tube_machine` CHAR(1) NULL DEFAULT NULL,
	`order_computer_name` VARCHAR(50) NULL DEFAULT NULL,
	`lis_calc_finance` CHAR(1) NULL DEFAULT NULL,
	`hospital_department_id` INT(11) NULL DEFAULT NULL,
	`send_mobile_msg` CHAR(1) NULL DEFAULT NULL,
	`order_staff` VARCHAR(25) NULL DEFAULT NULL,
	`has_manual_item` CHAR(1) NULL DEFAULT NULL,
	`link_lab_order_number` INT(11) NULL DEFAULT NULL,
	`specimen_code` INT(11) NULL DEFAULT NULL,
	`lab_receive` CHAR(1) NULL DEFAULT NULL,
	`finance_lab_clear` CHAR(1) NULL DEFAULT NULL,
	`receive_staff` VARCHAR(25) NULL DEFAULT NULL,
	`follow_up_vn` VARCHAR(12) NULL DEFAULT NULL,
	`lab_head_reject_type_id` INT(11) NULL DEFAULT NULL,
	`master_form_name` VARCHAR(200) NULL DEFAULT NULL,
	`doctor_ack_datetime` DATETIME NULL DEFAULT NULL,
	`entry_datetime` DATETIME NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`item_count` INT(11) NULL DEFAULT NULL,
	`lab_request_type_id` INT(11) NULL DEFAULT NULL,
	`image_count` INT(11) NULL DEFAULT NULL,
	`form_id` INT(11) NULL DEFAULT NULL,
	`master_form_id` INT(11) NULL DEFAULT NULL,
	`opd_qs_slot_id` INT(11) NULL DEFAULT NULL,
	`ref_order_code` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`lab_order_number`),
	INDEX `confirm_specimen` (`confirm_specimen`),
	INDEX `hn` (`hn`),
	INDEX `vn` (`vn`),
	INDEX `ix_order_date` (`order_date`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_lab_order_number_guid` (`lab_order_number_guid`),
	INDEX `ix_link_lab_order_number` (`link_lab_order_number`),
	INDEX `ix_follow_up_vn` (`follow_up_vn`),
	INDEX `ix_hn_order_date` (`hn`, `order_date`),
	INDEX `ix_link_order_form` (`link_lab_order_number`, `lab_order_number`, `form_name`),
	INDEX `ix_ref_order_code` (`ref_order_code`),
	INDEX `ix_lon_l` (`lab_order_number`, `link_lab_order_number`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;