CREATE TABLE `hos`.`lab_form_head` (
	`form_name` VARCHAR(250) NOT NULL DEFAULT '',
	`owner` VARCHAR(25) NULL DEFAULT NULL,
	`anonymous` CHAR(1) NULL DEFAULT NULL,
	`bethesda_cytologic` CHAR(1) NULL DEFAULT NULL,
	`confirm_charge_money` CHAR(1) NULL DEFAULT NULL,
	`finance_lab_confirm` CHAR(1) NULL DEFAULT NULL,
	`lab_room_id` INT(11) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`out_lab` CHAR(1) NULL DEFAULT NULL,
	`allow_online_report` CHAR(1) NULL DEFAULT NULL,
	`report_online_only` CHAR(1) NULL DEFAULT NULL,
	`active_status` CHAR(1) NULL DEFAULT NULL,
	`design_dfm` LONGTEXT NULL DEFAULT NULL,
	`design_pas` LONGTEXT NULL DEFAULT NULL,
	`use_design` CHAR(1) NULL DEFAULT NULL,
	`enable_script` CHAR(1) NULL DEFAULT NULL,
	`lab_form_group_type_id` INT(11) NULL DEFAULT NULL,
	`view_result_text` CHAR(1) NULL DEFAULT NULL,
	`allow_manual_item` CHAR(1) NULL DEFAULT NULL,
	`immediate_report` CHAR(1) NULL DEFAULT NULL,
	`form_id` INT(11) NULL DEFAULT NULL,
	`use_display_order` CHAR(1) NULL DEFAULT NULL,
	`has_external_form` CHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`form_name`),
	INDEX `ix_owner` (`owner`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_form_id` (`form_id`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;