CREATE TABLE `hos`.`lab_items` (
	`lab_items_code` INT(11) NOT NULL DEFAULT 0,
	`lab_items_name` VARCHAR(250) NULL DEFAULT NULL,
	`lab_type_code` TINYINT(4) NULL DEFAULT NULL,
	`lab_items_unit` VARCHAR(150) NULL DEFAULT NULL,
	`lab_items_normal_value` VARCHAR(150) NULL DEFAULT NULL,
	`lab_items_hint` VARCHAR(250) NULL DEFAULT NULL,
	`lab_items_default_value` VARCHAR(250) NULL DEFAULT NULL,
	`lab_items_group` INT(11) NULL DEFAULT NULL,
	`service_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`possible_value` TEXT NULL DEFAULT NULL,
	`lab_routine` CHAR(1) NULL DEFAULT NULL,
	`icode` VARCHAR(7) NULL DEFAULT NULL,
	`lab_items_sub_group_code` INT(11) NULL DEFAULT NULL,
	`require_specimen` CHAR(1) NULL DEFAULT NULL,
	`specimen_code` INT(11) NULL DEFAULT NULL,
	`wait_hour` INT(11) NULL DEFAULT NULL,
	`critical_value` VARCHAR(100) NULL DEFAULT NULL,
	`display_order` INT(11) NULL DEFAULT NULL,
	`ecode` VARCHAR(10) NULL DEFAULT NULL,
	`service_price2` DOUBLE(15,3) NULL DEFAULT NULL,
	`service_price3` DOUBLE(15,3) NULL DEFAULT NULL,
	`service_price_ipd` DOUBLE(15,3) NULL DEFAULT NULL,
	`service_price_ipd2` DOUBLE(15,3) NULL DEFAULT NULL,
	`service_price_ipd3` DOUBLE(15,3) NULL DEFAULT NULL,
	`check_user` CHAR(1) NULL DEFAULT NULL,
	`sub_group_list` VARCHAR(250) NULL DEFAULT NULL,
	`range_check` CHAR(1) NULL DEFAULT NULL,
	`range_check_min` DOUBLE(15,3) NULL DEFAULT NULL,
	`range_check_max` DOUBLE(15,3) NULL DEFAULT NULL,
	`result_type` INT(11) NULL DEFAULT NULL,
	`range_check_min_female` DOUBLE(15,3) NULL DEFAULT NULL,
	`range_check_max_female` DOUBLE(15,3) NULL DEFAULT NULL,
	`lab_items_code_guid` VARCHAR(38) NULL DEFAULT NULL,
	`service_cost` DOUBLE(15,3) NULL DEFAULT NULL,
	`oldcode` VARCHAR(150) NULL DEFAULT NULL,
	`items_is_outlab` CHAR(1) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`report_edit_style` VARCHAR(25) NULL DEFAULT NULL,
	`memo_line_count` INT(11) NULL DEFAULT NULL,
	`alert_critical_value` CHAR(1) NULL DEFAULT NULL,
	`critical_range_min_male` DOUBLE(15,3) NULL DEFAULT NULL,
	`critical_range_min_female` DOUBLE(15,3) NULL DEFAULT NULL,
	`critical_range_max_male` DOUBLE(15,3) NULL DEFAULT NULL,
	`critical_range_max_female` DOUBLE(15,3) NULL DEFAULT NULL,
	`confirm_order_text` VARCHAR(250) NULL DEFAULT NULL,
	`loinc_code` VARCHAR(15) NULL DEFAULT NULL,
	`check_result_by_age` CHAR(1) NULL DEFAULT NULL,
	`check_history` CHAR(1) NULL DEFAULT NULL,
	`check_history_day` INT(11) NULL DEFAULT NULL,
	`lab_items_display_name` VARCHAR(200) NULL DEFAULT NULL,
	`hint_text` TEXT NULL DEFAULT NULL,
	`lab_critical_alert_type_id` INT(11) NULL DEFAULT NULL,
	`active_status` VARCHAR(1) NULL DEFAULT NULL,
	`protect_result_by_user` CHAR(1) NULL DEFAULT NULL,
	`protect_result_by_group` CHAR(1) NULL DEFAULT NULL,
	`explicit_show_hist_abn_value` CHAR(1) NULL DEFAULT NULL,
	`provis_labcode` VARCHAR(7) NULL DEFAULT NULL,
	`labtest` VARCHAR(2) NULL DEFAULT NULL,
	`alert_critical_value2` CHAR(2) NULL DEFAULT NULL,
	`critical_range_min_male2` DOUBLE(15,3) NULL DEFAULT NULL,
	`critical_range_min_female2` DOUBLE(15,3) NULL DEFAULT NULL,
	`critical_range_max_male2` DOUBLE(15,3) NULL DEFAULT NULL,
	`critical_range_max_female2` DOUBLE(15,3) NULL DEFAULT NULL,
	`gen_order_no` CHAR(1) NULL DEFAULT NULL,
	`gen_order_prefix` VARCHAR(5) NULL DEFAULT NULL,
	`est_wait_minute` INT(11) NULL DEFAULT NULL,
	`report_next_day` CHAR(1) NULL DEFAULT NULL,
	`show_refer_doc` CHAR(1) NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`cloud_update_datetime` DATETIME NULL DEFAULT NULL,
	`tmlt_code` VARCHAR(10) NULL DEFAULT NULL,
	`line_notify_token` VARCHAR(100) NULL DEFAULT NULL,
	`need_npo` CHAR(1) NULL DEFAULT NULL,
	`npo_days_ahead` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`lab_items_code`),
	INDEX `lab_items_name` (`lab_items_name`),
	INDEX `ix_ix_oldcode` (`oldcode`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_lab_items_code_guid` (`lab_items_code_guid`),
	INDEX `ix_loinc_code` (`loinc_code`),
	INDEX `ix_gen_order_no` (`gen_order_no`),
	INDEX `ix_code_tmlt` (`lab_items_code`, `tmlt_code`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;