CREATE TABLE `hos`.`medplan_ipd` (
	`med_plan_number` INT(11) NOT NULL DEFAULT 0,
	`an` VARCHAR(13) NULL DEFAULT NULL,
	`doctor` VARCHAR(7) NULL DEFAULT NULL,
	`icode` VARCHAR(7) NULL DEFAULT NULL,
	`qty` INT(11) NULL DEFAULT NULL,
	`offdate` DATETIME NULL DEFAULT NULL,
	`orderdate` DATETIME NULL DEFAULT NULL,
	`orderstatus` CHAR(1) NULL DEFAULT NULL,
	`drugusage` VARCHAR(7) NULL DEFAULT NULL,
	`sp_use` VARCHAR(7) NULL DEFAULT NULL,
	`frequency` TINYINT(4) NULL DEFAULT NULL,
	`first_dose_date_time` DATETIME NULL DEFAULT NULL,
	`icode_type` CHAR(1) NULL DEFAULT NULL,
	`med_interval_type_id` INT(11) NULL DEFAULT NULL,
	`off_staff` VARCHAR(25) NULL DEFAULT NULL,
	`first_qty` INT(11) NULL DEFAULT NULL,
	`qty_2` INT(11) NULL DEFAULT NULL,
	`frequency_2` INT(11) NULL DEFAULT NULL,
	`usage_code` VARCHAR(10) NULL DEFAULT NULL,
	`dose` DOUBLE(15,3) NULL DEFAULT NULL,
	`unit_name` VARCHAR(25) NULL DEFAULT NULL,
	`frequency_code` VARCHAR(10) NULL DEFAULT NULL,
	`time_code` VARCHAR(10) NULL DEFAULT NULL,
	`usage_unit_code` VARCHAR(10) NULL DEFAULT NULL,
	`usage_lock` CHAR(1) NULL DEFAULT NULL,
	`usage_line1` VARCHAR(150) NULL DEFAULT NULL,
	`usage_line2` VARCHAR(150) NULL DEFAULT NULL,
	`usage_line3` VARCHAR(150) NULL DEFAULT NULL,
	`usage_line4` VARCHAR(150) NULL DEFAULT NULL,
	`usage_shortlist` VARCHAR(150) NULL DEFAULT NULL,
	`drug_hint_text` VARCHAR(150) NULL DEFAULT NULL,
	`price` DOUBLE(15,3) NULL DEFAULT NULL,
	`use_rx_pattern` CHAR(1) NULL DEFAULT NULL,
	`rx_pattern_first_date` DATE NULL DEFAULT NULL,
	`firstdate` DATE NULL DEFAULT NULL,
	`firstdate_check` CHAR(1) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`last_update` DATETIME NULL DEFAULT NULL,
	`first_update` DATETIME NULL DEFAULT NULL,
	`note` VARCHAR(200) NULL DEFAULT NULL,
	`week_day_check` CHAR(1) NULL DEFAULT NULL,
	`opi_acpc_id` INT(11) NULL DEFAULT NULL,
	`shortlist` VARCHAR(200) NULL DEFAULT NULL,
	`lang` CHAR(2) NULL DEFAULT NULL,
	`week_day_list` VARCHAR(200) NULL DEFAULT NULL,
	`is_refill` CHAR(1) NULL DEFAULT NULL,
	`need_refill` CHAR(1) NULL DEFAULT NULL,
	`auto_calc_first_dose` CHAR(1) NULL DEFAULT NULL,
	`auto_first_dose_time` TIME NULL DEFAULT NULL,
	`first_dose_cover` VARCHAR(200) NULL DEFAULT NULL,
	`off_time` TIME NULL DEFAULT NULL,
	`staff` VARCHAR(25) NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`is_mode3` CHAR(1) NULL DEFAULT NULL,
	`ipd_doctor_order_detail_id` INT(11) NULL DEFAULT NULL,
	`is_stat` CHAR(1) NULL DEFAULT NULL,
	`doctor_note` VARCHAR(200) NULL DEFAULT NULL,
	PRIMARY KEY (`med_plan_number`),
	INDEX `an` (`an`),
	INDEX `orderdate` (`orderdate`),
	INDEX `icode` (`icode`),
	INDEX `drugusage` (`drugusage`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_ipd_doctor_order_detail_id` (`ipd_doctor_order_detail_id`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;