CREATE TABLE `hos`.`medpay_ipd` (
	`med_order_number` INT(11) NOT NULL DEFAULT 0,
	`med_plan_number` INT(11) NULL DEFAULT NULL,
	`med_rx_number` INT(11) NULL DEFAULT NULL,
	`med_order_qty` INT(11) NULL DEFAULT NULL,
	`med_pay_qty` INT(11) NULL DEFAULT NULL,
	`pay_flag` CHAR(1) NULL DEFAULT NULL,
	`order_flag` CHAR(1) NULL DEFAULT NULL,
	`order_date` DATE NULL DEFAULT NULL,
	`order_date_time` DATETIME NULL DEFAULT NULL,
	`pay_date_time` DATETIME NULL DEFAULT NULL,
	`unitprice` DOUBLE(15,3) NULL DEFAULT NULL,
	`an` VARCHAR(13) NULL DEFAULT NULL,
	`med_type` CHAR(1) NULL DEFAULT NULL,
	`ipt_medication_type` INT(11) NULL DEFAULT NULL,
	`icode` VARCHAR(7) NULL DEFAULT NULL,
	`med_interval_type_id` INT(11) NULL DEFAULT NULL,
	`drugusage` VARCHAR(9) NULL DEFAULT NULL,
	`sp_use` VARCHAR(9) NULL DEFAULT NULL,
	`med_real_pay_qty` INT(11) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`orderstatus` CHAR(1) NULL DEFAULT NULL,
	`ipd_rx_pattern_id` INT(11) NULL DEFAULT NULL,
	`day_number` INT(11) NULL DEFAULT NULL,
	`use_rx_pattern` CHAR(1) NULL DEFAULT NULL,
	`pay_number` INT(11) NULL DEFAULT NULL,
	`opi_guid` VARCHAR(38) NULL DEFAULT NULL,
	`sticker_count` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`med_order_number`),
	UNIQUE INDEX `ix_unique` (`hos_guid`),
	INDEX `med_rx_number` (`med_rx_number`),
	INDEX `an` (`an`),
	INDEX `order_date` (`order_date`),
	INDEX `ix_an_med_rx_number` (`an`, `med_rx_number`),
	INDEX `ix_medplan_number` (`med_plan_number`),
	INDEX `ix_opi_guid` (`opi_guid`),
	INDEX `ix_an_med_rx_number_index` (`an`, `med_rx_number`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;