CREATE TABLE `hos`.`nondrugitems` (
	`icode` VARCHAR(7) NOT NULL DEFAULT '',
	`name` VARCHAR(200) NULL DEFAULT NULL,
	`price` DOUBLE(22,3) NULL DEFAULT NULL,
	`income` VARCHAR(2) NULL DEFAULT NULL,
	`xrayfilm` VARCHAR(150) NULL DEFAULT NULL,
	`icd9cm` VARCHAR(7) NULL DEFAULT NULL,
	`iflag` VARCHAR(50) NULL DEFAULT NULL,
	`vorder` INT(11) NULL DEFAULT NULL,
	`note` VARCHAR(50) NULL DEFAULT NULL,
	`use_right` CHAR(1) NULL DEFAULT NULL,
	`i_type` CHAR(1) NULL DEFAULT NULL,
	`must_paid` CHAR(1) NULL DEFAULT NULL,
	`paidst` CHAR(2) NULL DEFAULT NULL,
	`ipd_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`unitcost` DOUBLE(15,3) NULL DEFAULT NULL,
	`organ_code` VARCHAR(10) NULL DEFAULT NULL,
	`displaycolor` INT(11) NULL DEFAULT NULL,
	`istatus` CHAR(1) NULL DEFAULT NULL,
	`price3` DOUBLE(15,3) NULL DEFAULT NULL,
	`price2` DOUBLE(15,3) NULL DEFAULT NULL,
	`ipd_price2` DOUBLE(15,3) NULL DEFAULT NULL,
	`ipd_price3` DOUBLE(15,3) NULL DEFAULT NULL,
	`price_lock` CHAR(1) NULL DEFAULT NULL,
	`unit` VARCHAR(100) NULL DEFAULT NULL,
	`icode_guid` VARCHAR(38) NULL DEFAULT NULL,
	`billcode` VARCHAR(10) NULL DEFAULT NULL,
	`billnumber` VARCHAR(15) NULL DEFAULT NULL,
	`detail` VARCHAR(250) NULL DEFAULT NULL,
	`oldcode` VARCHAR(15) NULL DEFAULT NULL,
	`ext_icode` VARCHAR(7) NULL DEFAULT NULL,
	`charge_paidst` CHAR(2) NULL DEFAULT NULL,
	`lockprint` CHAR(1) NULL DEFAULT NULL,
	`rx_unique` CHAR(1) NULL DEFAULT NULL,
	`item_is_df` CHAR(1) NULL DEFAULT NULL,
	`df_type_id` INT(11) NULL DEFAULT NULL,
	`item_subtype_id` INT(11) NULL DEFAULT NULL,
	`ename` VARCHAR(150) NULL DEFAULT NULL,
	`no_remed` CHAR(1) NULL DEFAULT NULL,
	`remove_when_admit` CHAR(1) NULL DEFAULT NULL,
	`df_percent` DOUBLE(15,3) NULL DEFAULT NULL,
	`max_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`drugusage` VARCHAR(10) NULL DEFAULT NULL,
	`no_ipd_transfer` CHAR(1) NULL DEFAULT NULL,
	`no_discount` CHAR(1) NULL DEFAULT NULL,
	`df_search_code` VARCHAR(10) NULL DEFAULT NULL,
	`print_sticker_header` CHAR(1) NULL DEFAULT NULL,
	`no_substock` CHAR(1) NULL DEFAULT NULL,
	`ipd_default_pay` INT(11) NULL DEFAULT NULL,
	`hospital_highcost_code` VARCHAR(15) NULL DEFAULT NULL,
	`lockprint_ipd` CHAR(1) NULL DEFAULT NULL,
	`enable_sks_opd` CHAR(1) NULL DEFAULT NULL,
	`enable_sks_ipd` CHAR(1) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`show_notify` CHAR(1) NULL DEFAULT NULL,
	`show_notify_text` TEXT NULL DEFAULT NULL,
	`sks_coverage_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`sks_product_category_id` INT(11) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`nhso_adp_type_id` INT(11) NULL DEFAULT NULL,
	`nhso_adp_code` VARCHAR(15) NULL DEFAULT NULL,
	`extra_unitcost` DOUBLE(15,3) NULL DEFAULT NULL,
	`property_text` TEXT NULL DEFAULT NULL,
	`objctive_text` TEXT NULL DEFAULT NULL,
	`vat_percent` DOUBLE(15,3) NULL DEFAULT NULL,
	`use_paidst` CHAR(1) NULL DEFAULT NULL,
	`inv_map_update` CHAR(1) NULL DEFAULT NULL,
	`fwf_item_id` INT(11) NULL DEFAULT NULL,
	`limit_pttype` CHAR(1) NULL DEFAULT NULL,
	`sub_income` VARCHAR(3) NULL DEFAULT NULL,
	`nondrugitems_type_id` INT(11) NULL DEFAULT NULL,
	`highcost` VARCHAR(1) NULL DEFAULT 'N',
	`ucef_code` VARCHAR(20) NULL DEFAULT NULL,
	`lockprice` CHAR(1) NULL DEFAULT NULL,
	`is_accm` CHAR(1) NULL DEFAULT NULL,
	`is_food` CHAR(1) NULL DEFAULT NULL,
	`displaycolor_focus` INT(11) NULL DEFAULT NULL,
	`last_update` DATETIME NULL DEFAULT NULL,
	`charge_service_opd` CHAR(1) NULL DEFAULT NULL,
	`charge_service_ipd` CHAR(1) NULL DEFAULT NULL,
	`tpu_code_list` VARCHAR(200) NULL DEFAULT NULL,
	`state_item_id` INT(11) NULL DEFAULT NULL,
	`lock_pttype` CHAR(1) NULL DEFAULT NULL,
	`lock_pttype_code` CHAR(2) NULL DEFAULT NULL,
	`multiply_charge_service` CHAR(1) NULL DEFAULT NULL,
	`sks_drug_code` VARCHAR(25) NULL DEFAULT NULL,
	`csmbs_claim_cat` VARCHAR(1) NULL DEFAULT NULL,
	`simb_2005` VARCHAR(10) NULL DEFAULT NULL,
	`default_qty` INT(11) NULL DEFAULT NULL,
	`max_qty` INT(11) NULL DEFAULT NULL,
	`sks_rev_date` DATE NULL DEFAULT NULL,
	`default_qty_ipd` INT(11) NULL DEFAULT NULL,
	`max_qty_ipd` INT(11) NULL DEFAULT NULL,
	`tmlt_code` VARCHAR(10) NULL DEFAULT NULL,
	`sks_claim_category_type_id` INT(11) NULL DEFAULT NULL,
	`drg_chrgitem_id` VARCHAR(2) NULL DEFAULT NULL,
	PRIMARY KEY (`icode`),
	INDEX `iflag` (`iflag`),
	INDEX `name` (`name`),
	INDEX `note` (`note`),
	INDEX `ix_ix_oldcode` (`oldcode`),
	INDEX `ix_no_discount` (`no_discount`),
	INDEX `ix_no_ipd_transfer` (`no_ipd_transfer`),
	INDEX `ix_icode_guid` (`icode_guid`),
	INDEX `ix_billcode` (`billcode`),
	INDEX `ix_enable_sks_ipd` (`enable_sks_ipd`),
	INDEX `ix_enable_sks_opd` (`enable_sks_opd`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`),
	INDEX `ix_enable_sks_opd_income` (`enable_sks_opd`, `income`),
	INDEX `nhso_adp_code` (`nhso_adp_code`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;