CREATE TABLE `hos`.`oapp` (
	`oapp_id` INT(11) NOT NULL DEFAULT 0,
	`hn` VARCHAR(9) NULL DEFAULT NULL,
	`vn` VARCHAR(13) NULL DEFAULT NULL,
	`vstdate` DATE NULL DEFAULT NULL,
	`nextdate` DATE NULL DEFAULT NULL,
	`nexttime` TIME NULL DEFAULT NULL,
	`clinic` CHAR(3) NULL DEFAULT NULL,
	`depcode` CHAR(3) NULL DEFAULT NULL,
	`doctor` VARCHAR(15) NULL DEFAULT NULL,
	`note` VARCHAR(200) NULL DEFAULT NULL,
	`spclty` CHAR(2) NULL DEFAULT NULL,
	`app_user` VARCHAR(150) NULL DEFAULT NULL,
	`app_cause` VARCHAR(250) NULL DEFAULT NULL,
	`contact_point` VARCHAR(250) NULL DEFAULT NULL,
	`note1` TEXT NULL DEFAULT NULL,
	`note2` TEXT NULL DEFAULT NULL,
	`app_no` TINYINT(4) NULL DEFAULT NULL,
	`print_sticker` CHAR(1) NULL DEFAULT NULL,
	`enddate` DATE NULL DEFAULT NULL,
	`endtime` TIME NULL DEFAULT NULL,
	`label_color` INT(11) NULL DEFAULT NULL,
	`doctor_schedule_id` INT(11) NULL DEFAULT NULL,
	`ward` VARCHAR(4) NULL DEFAULT NULL,
	`patient_visit` CHAR(1) NULL DEFAULT NULL,
	`nexttime_end` TIME NULL DEFAULT NULL,
	`next_pttype` CHAR(2) NULL DEFAULT NULL,
	`visit_vn` VARCHAR(13) NULL DEFAULT NULL,
	`oapp_id_guid` VARCHAR(38) NULL DEFAULT NULL,
	`person_vaccine_id` INT(11) NULL DEFAULT NULL,
	`provis_aptype_code` VARCHAR(5) NULL DEFAULT NULL,
	`date_count` INT(11) NULL DEFAULT NULL,
	`an` CHAR(9) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`entry_date` DATE NULL DEFAULT NULL,
	`entry_time` TIME NULL DEFAULT NULL,
	`operation_appointment` CHAR(1) NULL DEFAULT NULL,
	`operation_patient_type` CHAR(3) NULL DEFAULT NULL,
	`operation_note` VARCHAR(200) NULL DEFAULT NULL,
	`operation_doctor_code` VARCHAR(25) NULL DEFAULT NULL,
	`operation_anes_type` VARCHAR(15) NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`oapp_status_id` INT(11) NULL DEFAULT NULL,
	`perform_text` TEXT NULL DEFAULT NULL,
	`lab_list_text` TEXT NULL DEFAULT NULL,
	`xray_list_text` TEXT NULL DEFAULT NULL,
	`clinic_visit_type_id` INT(11) NULL DEFAULT NULL,
	`visit_no` INT(11) NULL DEFAULT NULL,
	`opd_queue_slot_id` INT(11) NULL DEFAULT NULL,
	`opd_queue_schedule_id` INT(11) NULL DEFAULT NULL,
	`opd_qs_slot_id` INT(11) NULL DEFAULT NULL,
	`oapp_ref_id` INT(11) NULL DEFAULT NULL,
	`referin_vn` VARCHAR(12) NULL DEFAULT NULL,
	`oapp_week_range_limit_id` INT(11) NULL DEFAULT NULL,
	`ext_ref_id` INT(11) NULL DEFAULT NULL,
	`moph_ic_ref_id` INT(11) NULL DEFAULT NULL,
	`is_refill` CHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`oapp_id`),
	INDEX `ix_vn` (`vn`),
	INDEX `ix_hn` (`hn`),
	INDEX `ix_doctor` (`doctor`),
	INDEX `ix_nextdate` (`nextdate`),
	INDEX `ix_vstdate` (`vstdate`),
	INDEX `ix_vh` (`vstdate`, `hn`),
	INDEX `ix_doctor_schedule_id` (`doctor_schedule_id`),
	INDEX `ix_visit_vn` (`visit_vn`),
	INDEX `ix_oapp_id_guid` (`oapp_id_guid`),
	INDEX `ix_vh_index` (`hn`, `vstdate`),
	INDEX `ix_visit_vn_no` (`visit_vn`, `visit_no`),
	INDEX `ix_oapp_ref_id` (`oapp_ref_id`),
	INDEX `ix_qs_slot_id` (`opd_qs_slot_id`),
	INDEX `ix_visit_vn_no_index` (`visit_no`, `visit_vn`),
	INDEX `ix_vn_ext_ref_id` (`vn`, `ext_ref_id`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;