CREATE TABLE `hos`.`opd_allergy` (
	`hn` VARCHAR(9) NOT NULL DEFAULT '',
	`report_date` DATE NULL DEFAULT NULL,
	`agent` VARCHAR(250) NOT NULL DEFAULT '',
	`symptom` VARCHAR(250) NULL DEFAULT NULL,
	`reporter` VARCHAR(250) NULL DEFAULT NULL,
	`relation_level` VARCHAR(50) NULL DEFAULT NULL,
	`note` TEXT NULL DEFAULT NULL,
	`allergy_type` CHAR(1) NULL DEFAULT NULL,
	`display_order` INT(11) NULL DEFAULT NULL,
	`begin_date` DATE NULL DEFAULT NULL,
	`allergy_group_id` INT(11) NULL DEFAULT NULL,
	`seriousness_id` INT(11) NULL DEFAULT NULL,
	`allergy_result_id` INT(11) NULL DEFAULT NULL,
	`allergy_relation_id` INT(11) NULL DEFAULT NULL,
	`ward` VARCHAR(4) NULL DEFAULT NULL,
	`department` CHAR(3) NULL DEFAULT NULL,
	`spclty` CHAR(2) NULL DEFAULT NULL,
	`entry_datetime` DATETIME NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`depcode` CHAR(3) NULL DEFAULT NULL,
	`no_alert` CHAR(1) NULL DEFAULT NULL,
	`naranjo_result_id` INT(11) NULL DEFAULT NULL,
	`force_no_order` CHAR(1) NULL DEFAULT NULL,
	`opd_allergy_alert_type_id` INT(11) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`adr_preventable_score` INT(11) NULL DEFAULT NULL,
	`preventable` CHAR(1) NULL DEFAULT NULL,
	`patient_cid` VARCHAR(13) NULL DEFAULT NULL,
	`adr_consult_dialog_id` INT(11) NULL DEFAULT NULL,
	`opd_allergy_report_type_id` INT(11) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`agent_code24` VARCHAR(24) NULL DEFAULT NULL,
	`officer_confirm` CHAR(1) NULL DEFAULT NULL,
	`icode` CHAR(7) NULL DEFAULT NULL,
	`opd_allergy_symtom_type_id` INT(11) NULL DEFAULT NULL,
	`opd_allergy_id` INT(11) NULL DEFAULT NULL,
	`cross_group_check` CHAR(1) NULL DEFAULT NULL,
	`opd_allergy_source_id` INT(11) NULL DEFAULT NULL,
	`opd_allergy_type_id` INT(11) NULL DEFAULT NULL,
	`doctor_code` VARCHAR(15) NULL DEFAULT NULL,
	`dosage_text` TEXT NULL DEFAULT NULL,
	`usage_text` TEXT NULL DEFAULT NULL,
	`lab_text` TEXT NULL DEFAULT NULL,
	`sct_disorder_id` VARCHAR(18) NULL DEFAULT NULL,
	`sct_substance_id` VARCHAR(18) NULL DEFAULT NULL,
	PRIMARY KEY (`hn`, `agent`),
	INDEX `agent` (`agent`),
	INDEX `hn` (`hn`),
	INDEX `report_date` (`report_date`),
	INDEX `ix_patient_cid` (`patient_cid`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`),
	INDEX `ix_opd_allergy_id` (`opd_allergy_id`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;