CREATE TABLE `hos`.`opduser` (
	`loginname` VARCHAR(250) NOT NULL DEFAULT '',
	`name` VARCHAR(250) NULL DEFAULT NULL,
	`password` VARCHAR(250) NULL DEFAULT NULL,
	`passweb` VARCHAR(250) NULL DEFAULT NULL,
	`accessright` TEXT NULL DEFAULT NULL,
	`department` VARCHAR(250) NULL DEFAULT NULL,
	`departmentposition` VARCHAR(250) NULL DEFAULT NULL,
	`entryposition` VARCHAR(250) NULL DEFAULT NULL,
	`picture` LONGBLOB NULL DEFAULT NULL,
	`startfullscreen` CHAR(1) NULL DEFAULT NULL,
	`doctorcode` VARCHAR(7) NULL DEFAULT NULL,
	`drug_access_level` TINYINT(4) NULL DEFAULT NULL,
	`groupname` VARCHAR(250) NULL DEFAULT NULL,
	`visible_menu` TEXT NULL DEFAULT NULL,
	`viewallmenu` CHAR(1) NULL DEFAULT NULL,
	`lab_staff` CHAR(1) NULL DEFAULT NULL,
	`hospital_department_id` INT(11) NULL DEFAULT NULL,
	`nhso_user` VARCHAR(250) NULL DEFAULT NULL,
	`nhso_password` VARCHAR(250) NULL DEFAULT NULL,
	`max_station` INT(11) NULL DEFAULT NULL,
	`show_tip` CHAR(1) NULL DEFAULT NULL,
	`password_expire_date` DATE NULL DEFAULT NULL,
	`password_recheck_date` INT(11) NULL DEFAULT NULL,
	`new_password_date` DATE NULL DEFAULT NULL,
	`check_lab_password` CHAR(1) NULL DEFAULT NULL,
	`pcu_user` CHAR(1) NULL DEFAULT NULL,
	`account_disable` CHAR(1) NULL DEFAULT NULL,
	`restrict_ward_access` CHAR(1) NULL DEFAULT NULL,
	`real_staff` CHAR(1) NULL DEFAULT NULL,
	`restrict_clinic_access` CHAR(1) NULL DEFAULT NULL,
	`no_lab_result_display` CHAR(1) NULL DEFAULT NULL,
	`no_doctor_consult_display` CHAR(1) NULL DEFAULT NULL,
	`no_announce_display` CHAR(1) NULL DEFAULT NULL,
	`announce_read_count` INT(11) NULL DEFAULT NULL,
	`xray_staff` CHAR(1) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`lab_check_password` CHAR(1) NULL DEFAULT NULL,
	`cid` VARCHAR(13) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`auto_logout_minute` INT(11) NULL DEFAULT NULL,
	`userright` CHAR(1) NULL DEFAULT NULL,
	`iclaim_jwt` TEXT NULL DEFAULT NULL,
	`moph_acc_user` VARCHAR(50) NULL DEFAULT NULL,
	`moph_acc_password` VARCHAR(250) NULL DEFAULT NULL,
	PRIMARY KEY (`loginname`),
	INDEX `department` (`department`),
	INDEX `groupname` (`groupname`),
	INDEX `name` (`name`),
	INDEX `password` (`password`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_cid` (`cid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`),
	INDEX `ix_doctorcode` (`doctorcode`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;