CREATE TABLE `hos`.`operation_item` (
	`operation_item_id` INT(11) NOT NULL DEFAULT 0,
	`name` VARCHAR(100) NULL DEFAULT NULL,
	`icode` VARCHAR(7) NULL DEFAULT NULL,
	`price` DOUBLE(15,3) NULL DEFAULT NULL,
	`price2` DOUBLE(15,3) NULL DEFAULT NULL,
	`price3` DOUBLE(15,3) NULL DEFAULT NULL,
	`price_ipd` DOUBLE(15,3) NULL DEFAULT NULL,
	`price_ipd2` DOUBLE(15,3) NULL DEFAULT NULL,
	`price_ipd3` DOUBLE(15,3) NULL DEFAULT NULL,
	`icd9` VARCHAR(7) NULL DEFAULT NULL,
	`operation_group_id` INT(11) NULL DEFAULT NULL,
	`operation_item_type_id` INT(11) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`active_status` CHAR(1) NULL DEFAULT NULL,
	`keyword` VARCHAR(150) NULL DEFAULT NULL,
	PRIMARY KEY (`operation_item_id`),
	INDEX `ix_icode` (`icode`),
	INDEX `ix_name` (`name`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_name_active_status` (`name`, `active_status`),
	INDEX `ix_name_active_status_index` (`active_status`, `name`),
	INDEX `ix_keyword` (`keyword`),
	INDEX `ix_name_keyword` (`name`, `keyword`),
	INDEX `ix_name_keyword_index` (`keyword`, `name`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;