CREATE TABLE `hos`.`operation_detail` (
	`operation_detail_id` INT(11) NOT NULL DEFAULT 0,
	`operation_id` INT(11) NULL DEFAULT NULL,
	`operation_item_id` INT(11) NULL DEFAULT NULL,
	`doctor` VARCHAR(9) NULL DEFAULT NULL,
	`begin_datetime` DATETIME NULL DEFAULT NULL,
	`end_datetime` DATETIME NULL DEFAULT NULL,
	`price` DOUBLE(15,3) NULL DEFAULT NULL,
	`icdcode` VARCHAR(9) NULL DEFAULT NULL,
	`wait_save` CHAR(1) NULL DEFAULT NULL,
	`opitemrece_guid` VARCHAR(38) NULL DEFAULT NULL,
	`operation_wound_id` INT(11) NULL DEFAULT NULL,
	`operation_order_number` INT(11) NULL DEFAULT NULL,
	`operation_position` INT(11) NULL DEFAULT NULL,
	`wound_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`wound_qty` INT(11) NULL DEFAULT NULL,
	`wound_type` VARCHAR(100) NULL DEFAULT NULL,
	`patient_position` VARCHAR(50) NULL DEFAULT NULL,
	`icode` VARCHAR(7) NULL DEFAULT NULL,
	`operation_side` VARCHAR(50) NULL DEFAULT NULL,
	`extenstion_code` VARCHAR(10) NULL DEFAULT NULL,
	`electric_touch` CHAR(1) NULL DEFAULT NULL,
	`extension_code` VARCHAR(15) NULL DEFAULT NULL,
	`diagnosis_text` VARCHAR(250) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`oper_type` INT(11) NULL DEFAULT NULL,
	`ovst_oper_type` INT(11) NULL DEFAULT NULL,
	`biopsy` CHAR(1) NULL DEFAULT NULL,
	`operation_type_id` INT(11) NULL DEFAULT NULL,
	`operation_time_hour` INT(11) NULL DEFAULT NULL,
	`operation_time_minute` INT(11) NULL DEFAULT NULL,
	`cancel_operation_reason` VARCHAR(200) NULL DEFAULT NULL,
	`spclty` VARCHAR(2) NULL DEFAULT NULL,
	`room_id` INT(11) NULL DEFAULT NULL,
	`operation_detail_note` TEXT NULL DEFAULT NULL,
	`time_out_datetime` DATETIME NULL DEFAULT NULL,
	`incision_datetime` DATETIME NULL DEFAULT NULL,
	`closure_datetime` DATETIME NULL DEFAULT NULL,
	`doctor_fee_type_id` INT(11) NULL DEFAULT NULL,
	`diag_ext_type_id` INT(11) NULL DEFAULT NULL,
	`link_diag_id` INT(11) NULL DEFAULT NULL,
	`is_trauma` CHAR(1) NULL DEFAULT NULL,
	`discount_25_percent` CHAR(1) NULL DEFAULT NULL,
	`include_df_price` CHAR(1) NULL DEFAULT NULL,
	`df_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`total_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`operation_trauma_type_id` INT(11) NULL DEFAULT NULL,
	`operation_result_type_id` INT(11) NULL DEFAULT NULL,
	`charge_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`clinical_term` VARCHAR(200) NULL DEFAULT NULL,
	PRIMARY KEY (`operation_detail_id`),
	INDEX `ix_doctor` (`doctor`),
	INDEX `ix_operation_id` (`operation_id`),
	INDEX `ix_operation_item_id` (`operation_item_id`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_opitemrece_guid` (`opitemrece_guid`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;