CREATE TABLE `hos`.`operation_list` (
	`operation_id` INT(11) NOT NULL DEFAULT 0,
	`request_date` DATE NULL DEFAULT NULL,
	`request_time` TIME NULL DEFAULT NULL,
	`request_doctor` VARCHAR(6) NULL DEFAULT NULL,
	`operation_date` DATE NULL DEFAULT NULL,
	`operation_time` TIME NULL DEFAULT NULL,
	`note` TEXT NULL DEFAULT NULL,
	`finish` CHAR(1) NULL DEFAULT NULL,
	`department_id` INT(11) NULL DEFAULT NULL,
	`room_id` INT(11) NULL DEFAULT NULL,
	`hn` VARCHAR(9) NULL DEFAULT NULL,
	`vn` VARCHAR(13) NULL DEFAULT NULL,
	`an` VARCHAR(13) NULL DEFAULT NULL,
	`patient_department` CHAR(3) NULL DEFAULT NULL,
	`provision_diagnosis` VARCHAR(9) NULL DEFAULT NULL,
	`provision_diagnosis_text` VARCHAR(200) NULL DEFAULT NULL,
	`operation_name` VARCHAR(250) NULL DEFAULT NULL,
	`operation_position` VARCHAR(250) NULL DEFAULT NULL,
	`operation_side` VARCHAR(250) NULL DEFAULT NULL,
	`require_anes` CHAR(1) NULL DEFAULT NULL,
	`require_icu` CHAR(1) NULL DEFAULT NULL,
	`status_id` INT(11) NULL DEFAULT NULL,
	`emergency_id` INT(11) NULL DEFAULT NULL,
	`staff` VARCHAR(25) NULL DEFAULT NULL,
	`enter_date` DATE NULL DEFAULT NULL,
	`enter_time` TIME NULL DEFAULT NULL,
	`leave_date` DATE NULL DEFAULT NULL,
	`leave_time` TIME NULL DEFAULT NULL,
	`spclty` CHAR(2) NULL DEFAULT NULL,
	`age_text` VARCHAR(50) NULL DEFAULT NULL,
	`disease_text` VARCHAR(100) NULL DEFAULT NULL,
	`npo_date_time` DATETIME NULL DEFAULT NULL,
	`send_spclty` CHAR(2) NULL DEFAULT NULL,
	`operation_type_id` INT(11) NULL DEFAULT NULL,
	`operation_time_type_id` INT(11) NULL DEFAULT NULL,
	`request_operation_date` DATE NULL DEFAULT NULL,
	`request_operation_time` TIME NULL DEFAULT NULL,
	`confirm_receive` CHAR(1) NULL DEFAULT NULL,
	`confirm_complete` CHAR(1) NULL DEFAULT NULL,
	`anes_complete` CHAR(1) NULL DEFAULT NULL,
	`send_depcode` CHAR(3) NULL DEFAULT NULL,
	`chronic_disease` VARCHAR(250) NULL DEFAULT NULL,
	`operation_note` TEXT NULL DEFAULT NULL,
	`operation_anes_physical_status_id` INT(11) NULL DEFAULT NULL,
	`operation_consciousness_id` INT(11) NULL DEFAULT NULL,
	`operation_respiration_id` INT(11) NULL DEFAULT NULL,
	`coma_score_e` INT(11) NULL DEFAULT NULL,
	`coma_score_m` INT(11) NULL DEFAULT NULL,
	`coma_score_v` CHAR(1) NULL DEFAULT NULL,
	`operation_sum_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`operation_list_anes_type_id` INT(11) NULL DEFAULT NULL,
	`patient_type` CHAR(3) NULL DEFAULT NULL,
	`on_call` CHAR(1) NULL DEFAULT NULL,
	`post_diagnosis` VARCHAR(7) NULL DEFAULT NULL,
	`pre_diagnosis_text_list` TEXT NULL DEFAULT NULL,
	`post_diagnosis_text_list` TEXT NULL DEFAULT NULL,
	`pre_anes_operation_note` TEXT NULL DEFAULT NULL,
	`intra_anes_operation_note` TEXT NULL DEFAULT NULL,
	`post_anes_operation_note` TEXT NULL DEFAULT NULL,
	`operation_check_date` DATE NULL DEFAULT NULL,
	`operation_check_time` TIME NULL DEFAULT NULL,
	`arrive_date` DATE NULL DEFAULT NULL,
	`arrive_time` TIME NULL DEFAULT NULL,
	`doctor_incision_date` DATE NULL DEFAULT NULL,
	`doctor_incision_time` TIME NULL DEFAULT NULL,
	`doctor_closing_date` DATE NULL DEFAULT NULL,
	`doctor_closing_time` TIME NULL DEFAULT NULL,
	`operation_facility_id` INT(11) NULL DEFAULT NULL,
	`operation_set_id` INT(11) NULL DEFAULT NULL,
	`sub_spclty_id` INT(11) NULL DEFAULT NULL,
	`dx_note` TEXT NULL DEFAULT NULL,
	`send_operation_room_id` INT(11) NULL DEFAULT NULL,
	`re_operation` CHAR(1) NULL DEFAULT NULL,
	`asset_text` TEXT NULL DEFAULT NULL,
	`sp_med_text` TEXT NULL DEFAULT NULL,
	`prepare_text` TEXT NULL DEFAULT NULL,
	`blood_loss` DOUBLE(15,3) NULL DEFAULT NULL,
	`note_rtf` TEXT NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`operation_detail_name` VARCHAR(250) NULL DEFAULT NULL,
	PRIMARY KEY (`operation_id`),
	INDEX `ix_request_date` (`request_date`),
	INDEX `ix_request_doctor` (`request_doctor`),
	INDEX `ix_request_time` (`request_time`),
	INDEX `ix_status_id` (`status_id`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_operation_set_id` (`operation_set_id`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;