CREATE TABLE `hos`.`opitemrece` (
	`hos_guid` VARCHAR(38) NOT NULL DEFAULT '',
	`vn` VARCHAR(13) NULL DEFAULT NULL,
	`hn` VARCHAR(9) NULL DEFAULT NULL,
	`an` VARCHAR(13) NULL DEFAULT NULL,
	`icode` VARCHAR(7) NULL DEFAULT NULL,
	`qty` INT(11) NULL DEFAULT NULL,
	`drugusage` VARCHAR(7) NULL DEFAULT NULL,
	`idr` VARCHAR(30) NULL DEFAULT NULL,
	`iperday` INT(11) NULL DEFAULT NULL,
	`iperdose` DOUBLE(12,3) NULL DEFAULT NULL,
	`recetime` TIME NULL DEFAULT NULL,
	`unitprice` DOUBLE(12,3) NULL DEFAULT NULL,
	`vstdate` DATE NULL DEFAULT NULL,
	`vsttime` TIME NULL DEFAULT NULL,
	`doctor` VARCHAR(10) NULL DEFAULT NULL,
	`rxdate` DATE NULL DEFAULT NULL,
	`rxtime` TIME NULL DEFAULT NULL,
	`sp_use` VARCHAR(7) NULL DEFAULT NULL,
	`hcode` VARCHAR(5) NULL DEFAULT NULL,
	`print` CHAR(1) NULL DEFAULT NULL,
	`dep_code` CHAR(3) NULL DEFAULT NULL,
	`finance_number` VARCHAR(7) NULL DEFAULT NULL,
	`discount` DOUBLE(15,3) NULL DEFAULT NULL,
	`use_right` CHAR(1) NULL DEFAULT NULL,
	`node_id` CHAR(1) NULL DEFAULT NULL,
	`order_no` INT(11) NULL DEFAULT NULL,
	`sub_type` CHAR(1) NULL DEFAULT NULL,
	`pttype` CHAR(2) NULL DEFAULT NULL,
	`income` CHAR(2) NULL DEFAULT NULL,
	`remain` CHAR(1) NULL DEFAULT NULL,
	`item_type` CHAR(1) NULL DEFAULT NULL,
	`staff` VARCHAR(25) NULL DEFAULT NULL,
	`doctor_lock` CHAR(1) NULL DEFAULT NULL,
	`paidst` CHAR(2) NULL DEFAULT NULL,
	`item_no` TINYINT(4) NULL DEFAULT NULL,
	`last_modified` DATETIME NULL DEFAULT NULL,
	`sum_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`cost` DOUBLE(15,3) NULL DEFAULT NULL,
	`stock_department_id` INT(11) NULL DEFAULT NULL,
	`command_doctor` VARCHAR(10) NULL DEFAULT NULL,
	`opi_doctor_finance_type_id` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`hos_guid`),
	INDEX `ix_vn` (`vn`),
	INDEX `ix_hn` (`hn`),
	INDEX `ix_an` (`an`),
	INDEX `ix_icode` (`icode`),
	INDEX `ix_drugusage` (`drugusage`),
	INDEX `ix_vstdate` (`vstdate`),
	INDEX `ix_doctor` (`doctor`),
	INDEX `ix_rxdate` (`rxdate`),
	INDEX `ix_hcode` (`hcode`),
	INDEX `ix_finance_number` (`finance_number`),
	INDEX `ix_sub_type` (`sub_type`),
	INDEX `ix_pttype` (`pttype`),
	INDEX `ix_item_type` (`item_type`),
	INDEX `ix_staff` (`staff`),
	INDEX `ix_ix_ix_an_rxdate_icode` (`an`, `rxdate`, `icode`),
	INDEX `ix_an_rxdate_icode_index` (`an`, `icode`, `rxdate`),
	INDEX `ix_an_order_no` (`an`, `order_no`),
	INDEX `ix_an_rxdate_icode` (`rxdate`, `icode`, `an`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;