CREATE TABLE `hos`.`ovst` (
	`hos_guid` VARCHAR(38) NOT NULL DEFAULT '',
	`vn` VARCHAR(13) NULL DEFAULT NULL,
	`hn` VARCHAR(9) NULL DEFAULT NULL,
	`an` VARCHAR(13) NULL DEFAULT NULL,
	`vstdate` DATE NULL DEFAULT NULL,
	`vsttime` TIME NULL DEFAULT NULL,
	`doctor` VARCHAR(7) NULL DEFAULT NULL,
	`hospmain` VARCHAR(5) NULL DEFAULT NULL,
	`hospsub` VARCHAR(5) NULL DEFAULT NULL,
	`oqueue` INT(11) NULL DEFAULT NULL,
	`ovstist` CHAR(2) NULL DEFAULT NULL,
	`ovstost` VARCHAR(4) NULL DEFAULT NULL,
	`pttype` CHAR(2) NULL DEFAULT NULL,
	`pttypeno` VARCHAR(50) NULL DEFAULT NULL,
	`rfrics` CHAR(1) NULL DEFAULT NULL,
	`rfrilct` VARCHAR(5) NULL DEFAULT NULL,
	`rfrocs` CHAR(1) NULL DEFAULT NULL,
	`rfrolct` VARCHAR(5) NULL DEFAULT NULL,
	`spclty` CHAR(2) NULL DEFAULT NULL,
	`rcpt_disease` VARCHAR(100) NULL DEFAULT NULL,
	`hcode` VARCHAR(5) NULL DEFAULT NULL,
	`cur_dep` CHAR(3) NULL DEFAULT NULL,
	`cur_dep_busy` CHAR(1) NULL DEFAULT NULL,
	`last_dep` CHAR(3) NULL DEFAULT NULL,
	`cur_dep_time` TIME NULL DEFAULT NULL,
	`rx_queue` INT(11) NULL DEFAULT NULL,
	`diag_text` VARCHAR(250) NULL DEFAULT NULL,
	`pt_subtype` TINYINT(4) NULL DEFAULT NULL,
	`main_dep` CHAR(3) NULL DEFAULT NULL,
	`main_dep_queue` INT(11) NULL DEFAULT NULL,
	`finance_summary_date` DATE NULL DEFAULT NULL,
	`visit_type` CHAR(1) NULL DEFAULT NULL,
	`node_id` CHAR(1) NULL DEFAULT NULL,
	`contract_id` INT(11) NULL DEFAULT NULL,
	`waiting` CHAR(1) NULL DEFAULT NULL,
	`rfri_icd10` VARCHAR(6) NULL DEFAULT NULL,
	`o_refer_number` INT(11) NULL DEFAULT NULL,
	`has_insurance` CHAR(1) NULL DEFAULT NULL,
	`i_refer_number` VARCHAR(25) NULL DEFAULT NULL,
	`refer_type` CHAR(1) NULL DEFAULT NULL,
	`o_refer_dep` VARCHAR(5) NULL DEFAULT NULL,
	`staff` VARCHAR(25) NULL DEFAULT NULL,
	`command_doctor` VARCHAR(6) NULL DEFAULT NULL,
	`send_person` VARCHAR(150) NULL DEFAULT NULL,
	`pt_priority` INT(11) NULL DEFAULT NULL,
	`finance_lock` CHAR(1) NULL DEFAULT NULL,
	`oldcode` VARCHAR(20) NULL DEFAULT NULL,
	`sign_doctor` VARCHAR(10) NULL DEFAULT NULL,
	`anonymous_visit` CHAR(1) NULL DEFAULT NULL,
	`anonymous_vn` VARCHAR(12) NULL DEFAULT NULL,
	`pt_capability_type_id` INT(11) NULL DEFAULT NULL,
	`at_hospital` CHAR(1) NULL DEFAULT NULL,
	`ovst_key` VARCHAR(40) NULL DEFAULT NULL,
	PRIMARY KEY (`hos_guid`),
	UNIQUE INDEX `ix_vn` (`vn`),
	INDEX `ix_hn` (`hn`),
	INDEX `ix_an` (`an`),
	INDEX `ix_vstdate` (`vstdate`),
	INDEX `ix_doctor` (`doctor`),
	INDEX `ix_pttype` (`pttype`),
	INDEX `ix_spclty` (`spclty`),
	INDEX `ix_hcode` (`hcode`),
	INDEX `ix_o_refer_number` (`o_refer_number`),
	INDEX `ix_staff` (`staff`),
	INDEX `ix_ix_ix_hn_vstdate` (`hn`, `vstdate`),
	INDEX `ix_i_refer_number` (`i_refer_number`),
	INDEX `ix_anonymous_vn` (`anonymous_vn`),
	INDEX `ix_vn_anonymous_vs_vn` (`vn`, `anonymous_visit`, `anonymous_vn`),
	INDEX `ix_vn_date` (`vn`, `vstdate`),
	INDEX `ix_vstdate_curdep` (`vstdate`, `cur_dep`),
	INDEX `ix_vn_anonymous_vs_vn_index` (`anonymous_visit`, `anonymous_vn`, `vn`),
	INDEX `ix_vstdate_curdep_index` (`cur_dep`, `vstdate`),
	INDEX `ix_vn_date_index` (`vn`, `vstdate`),
	INDEX `ix_hn_vstdate` (`hn`, `vstdate`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;