CREATE TABLE `hos`.`ovstdiag` (
	`ovst_diag_id` INT(11) NOT NULL DEFAULT 0,
	`vn` VARCHAR(13) NULL DEFAULT NULL,
	`icd10` VARCHAR(9) NULL DEFAULT NULL,
	`hn` VARCHAR(9) NULL DEFAULT NULL,
	`vstdate` DATE NULL DEFAULT NULL,
	`vsttime` TIME NULL DEFAULT NULL,
	`diagtype` CHAR(2) NULL DEFAULT NULL,
	`icd103` CHAR(3) NULL DEFAULT NULL,
	`hcode` VARCHAR(5) NULL DEFAULT NULL,
	`doctor` VARCHAR(6) NULL DEFAULT NULL,
	`episode` TINYINT(4) NULL DEFAULT NULL,
	`ext_code` CHAR(2) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`dep_flag` CHAR(2) NULL DEFAULT NULL,
	`ovst_oper_type` INT(11) NULL DEFAULT NULL,
	`staff` VARCHAR(25) NULL DEFAULT NULL,
	`dx_guid` VARCHAR(38) NULL DEFAULT NULL,
	`lock_dx` CHAR(1) NULL DEFAULT NULL,
	`dx_code_note` VARCHAR(100) NULL DEFAULT NULL,
	`ovstdiag_severe_type_id` INT(11) NULL DEFAULT NULL,
	`diag_no` INT(11) NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`confirm` CHAR(1) NULL DEFAULT NULL,
	`confirm_staff` VARCHAR(25) NULL DEFAULT NULL,
	`opi_guid` VARCHAR(38) NULL DEFAULT NULL,
	`sct_id` VARCHAR(18) NULL DEFAULT NULL,
	PRIMARY KEY (`ovst_diag_id`),
	UNIQUE INDEX `ix_unique` (`vn`, `icd10`),
	UNIQUE INDEX `ix_vn_icd_unique` (`icd10`, `vn`),
	INDEX `ix_vn` (`vn`),
	INDEX `ix_hn` (`hn`),
	INDEX `ix_doctor` (`doctor`),
	INDEX `ix_vstdate` (`vstdate`),
	INDEX `ix_icd10` (`icd10`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_sti` (`ovstdiag_severe_type_id`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;