CREATE TABLE `hos`.`patient` (
	`hos_guid` VARCHAR(38) NOT NULL DEFAULT '',
	`hn` VARCHAR(9) NULL DEFAULT NULL,
	`pname` VARCHAR(25) NULL DEFAULT NULL,
	`fname` VARCHAR(30) NULL DEFAULT NULL,
	`lname` VARCHAR(30) NULL DEFAULT NULL,
	`occupation` VARCHAR(4) NULL DEFAULT NULL,
	`citizenship` CHAR(3) NULL DEFAULT NULL,
	`birthday` DATE NULL DEFAULT NULL,
	`addrpart` VARCHAR(50) NULL DEFAULT NULL,
	`moopart` CHAR(3) NULL DEFAULT NULL,
	`tmbpart` CHAR(2) NULL DEFAULT NULL,
	`amppart` CHAR(2) NULL DEFAULT NULL,
	`chwpart` CHAR(2) NULL DEFAULT NULL,
	`bloodgrp` VARCHAR(20) NULL DEFAULT NULL,
	`clinic` VARCHAR(100) NULL DEFAULT NULL,
	`deathday` DATE NULL DEFAULT NULL,
	`drugallergy` VARCHAR(250) NULL DEFAULT NULL,
	`familyno` INT(11) NULL DEFAULT NULL,
	`fathername` VARCHAR(50) NULL DEFAULT NULL,
	`firstday` DATE NULL DEFAULT NULL,
	`hometel` VARCHAR(20) NULL DEFAULT NULL,
	`informaddr` VARCHAR(200) NULL DEFAULT NULL,
	`informname` VARCHAR(50) NULL DEFAULT NULL,
	`informrelation` VARCHAR(50) NULL DEFAULT NULL,
	`informtel` VARCHAR(20) NULL DEFAULT NULL,
	`marrystatus` CHAR(1) NULL DEFAULT NULL,
	`mathername` VARCHAR(50) NULL DEFAULT NULL,
	`hn_int` INT(11) NULL DEFAULT NULL,
	`nationality` CHAR(3) NULL DEFAULT NULL,
	`opdlocation` VARCHAR(50) NULL DEFAULT NULL,
	`pttype` CHAR(2) NULL DEFAULT NULL,
	`religion` CHAR(2) NULL DEFAULT NULL,
	`sex` CHAR(1) NULL DEFAULT NULL,
	`spsname` VARCHAR(50) NULL DEFAULT NULL,
	`truebirthday` CHAR(1) NULL DEFAULT NULL,
	`workaddr` VARCHAR(50) NULL DEFAULT NULL,
	`worktel` VARCHAR(20) NULL DEFAULT NULL,
	`hcode` VARCHAR(5) NULL DEFAULT NULL,
	`cid` VARCHAR(13) NULL DEFAULT NULL,
	`hid` INT(11) NULL DEFAULT NULL,
	`educate` CHAR(1) NULL DEFAULT NULL,
	`family_status` CHAR(1) NULL DEFAULT NULL,
	`labor_type` CHAR(1) NULL DEFAULT NULL,
	`last_update` DATETIME NULL DEFAULT NULL,
	`type_area` CHAR(1) NULL DEFAULT NULL,
	`road` VARCHAR(50) NULL DEFAULT NULL,
	`father_cid` VARCHAR(13) NULL DEFAULT NULL,
	`mother_cid` VARCHAR(13) NULL DEFAULT NULL,
	`couple_cid` VARCHAR(13) NULL DEFAULT NULL,
	`person_type` CHAR(2) NULL DEFAULT NULL,
	`private_doctor_name` VARCHAR(75) NULL DEFAULT NULL,
	`legal_action` CHAR(1) NULL DEFAULT NULL,
	`death_code504` CHAR(2) NULL DEFAULT NULL,
	`death_diag` VARCHAR(6) NULL DEFAULT NULL,
	`node_id` CHAR(1) NULL DEFAULT NULL,
	`admit` CHAR(1) NULL DEFAULT NULL,
	`midname` VARCHAR(25) NULL DEFAULT NULL,
	`po_code` VARCHAR(5) NULL DEFAULT NULL,
	`fatherlname` VARCHAR(30) NULL DEFAULT NULL,
	`motherlname` VARCHAR(30) NULL DEFAULT NULL,
	`spslname` VARCHAR(30) NULL DEFAULT NULL,
	`country` CHAR(2) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`birthtime` TIME NULL DEFAULT NULL,
	`mother_hn` VARCHAR(9) NULL DEFAULT NULL,
	`last_visit` DATE NULL DEFAULT NULL,
	`death` CHAR(1) NULL DEFAULT NULL,
	`height` INT(11) NULL DEFAULT NULL,
	`inregion` CHAR(1) NULL DEFAULT NULL,
	`reg_time` TIME NULL DEFAULT NULL,
	`oldcode` VARCHAR(50) NULL DEFAULT NULL,
	`lang` CHAR(2) NULL DEFAULT NULL,
	`gov_chronic_id` VARCHAR(10) NULL DEFAULT NULL,
	`in_cups` CHAR(1) NULL DEFAULT NULL,
	`patient_type_id` TINYINT(4) NULL DEFAULT NULL,
	`addr_soi` VARCHAR(100) NULL DEFAULT NULL,
	`work_addr` VARCHAR(230) NULL DEFAULT NULL,
	`father_hn` VARCHAR(9) NULL DEFAULT NULL,
	`alias_name` VARCHAR(100) NULL DEFAULT NULL,
	`destroyed` CHAR(1) NULL DEFAULT NULL,
	`old_addr` VARCHAR(250) NULL DEFAULT NULL,
	`fname_soundex` VARCHAR(50) NULL DEFAULT NULL,
	`lname_soundex` VARCHAR(50) NULL DEFAULT NULL,
	`bloodgroup_rh` VARCHAR(5) NULL DEFAULT NULL,
	`passport_no` VARCHAR(25) NULL DEFAULT NULL,
	`addressid` VARCHAR(6) NULL DEFAULT NULL,
	`mobile_phone_number` VARCHAR(20) NULL DEFAULT NULL,
	`anonymous_person` CHAR(1) NULL DEFAULT NULL,
	`hospital_department_id` INT(11) NULL DEFAULT NULL,
	`membercard_no` VARCHAR(15) NULL DEFAULT NULL,
	`ec_fname` VARCHAR(50) NULL DEFAULT NULL,
	`ec_lname` VARCHAR(50) NULL DEFAULT NULL,
	`ec_relation_type_id` INT(11) NULL DEFAULT NULL,
	`patient_color_id` INT(11) NULL DEFAULT NULL,
	`number_of_relatives` INT(11) NULL DEFAULT NULL,
	`birth_order` INT(11) NULL DEFAULT NULL,
	`person_labor_type_id` INT(11) NULL DEFAULT NULL,
	`vid` VARCHAR(8) NULL DEFAULT NULL,
	`is_card_destroy` CHAR(1) NULL DEFAULT NULL,
	`card_destroy_date` DATE NULL DEFAULT NULL,
	`g6pd` CHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`hos_guid`),
	UNIQUE INDEX `ix_hn` (`hn`),
	INDEX `ix_pname` (`pname`),
	INDEX `ix_fname` (`fname`),
	INDEX `ix_lname` (`lname`),
	INDEX `ix_fname_lname` (`fname`, `lname`),
	INDEX `ix_chwpart` (`chwpart`),
	INDEX `ix_address` (`chwpart`, `amppart`, `tmbpart`),
	INDEX `ix_clinic` (`clinic`),
	INDEX `ix_pttype` (`pttype`),
	INDEX `ix_hcode` (`hcode`),
	INDEX `ix_cid` (`cid`),
	INDEX `ix_ix_deathday` (`deathday`),
	INDEX `ix_fname_soundex` (`fname_soundex`),
	INDEX `ix_lname_soundex` (`lname_soundex`),
	INDEX `ix_oldcode` (`oldcode`),
	INDEX `ix_lastvisit` (`last_visit`),
	INDEX `ix_firstday` (`firstday`),
	INDEX `ix_membercard_no` (`membercard_no`),
	INDEX `ix_passport_no` (`passport_no`),
	INDEX `ix_address_index` (`amppart`, `chwpart`, `tmbpart`),
	INDEX `ix_last_update` (`last_update`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;