CREATE TABLE `hos`.`ptnote` (
	`ptnote_id` INT(11) NOT NULL DEFAULT 0,
	`hn` VARCHAR(9) NULL DEFAULT NULL,
	`noteflag` VARCHAR(250) NULL DEFAULT NULL,
	`ptnote` TEXT NULL DEFAULT NULL,
	`vstdate` DATE NULL DEFAULT NULL,
	`vsttime` TIME NULL DEFAULT NULL,
	`groupname` VARCHAR(250) NULL DEFAULT NULL,
	`plain_text` TEXT NULL DEFAULT NULL,
	`prsc_note_text` VARCHAR(250) NULL DEFAULT NULL,
	`note_datetime` DATETIME NULL DEFAULT NULL,
	`note_staff` VARCHAR(25) NULL DEFAULT NULL,
	`username_list` TEXT NULL DEFAULT NULL,
	`has_expired` CHAR(1) NULL DEFAULT NULL,
	`expire_date` DATE NULL DEFAULT NULL,
	`public_note` CHAR(1) NULL DEFAULT NULL,
	`encrypt_note` CHAR(1) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`show_all_dep` CHAR(1) NULL DEFAULT NULL,
	`check_group` CHAR(1) NULL DEFAULT NULL,
	`ptnote_html` TEXT NULL DEFAULT NULL,
	PRIMARY KEY (`ptnote_id`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_hn` (`hn`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;