CREATE TABLE `hos`.`pttype` (
	`pttype` CHAR(2) NOT NULL DEFAULT '',
	`name` VARCHAR(250) NULL DEFAULT NULL,
	`editmask` VARCHAR(100) NULL DEFAULT NULL,
	`isuse` CHAR(1) NULL DEFAULT NULL,
	`pcode` CHAR(2) NULL DEFAULT NULL,
	`requirecode` CHAR(1) NULL DEFAULT NULL,
	`doctor_fee` CHAR(1) NULL DEFAULT NULL,
	`fee_code` VARCHAR(7) NULL DEFAULT NULL,
	`discount` INT(11) NULL DEFAULT NULL,
	`contract` CHAR(1) NULL DEFAULT NULL,
	`paidst` CHAR(2) NULL DEFAULT NULL,
	`in_region` CHAR(1) NULL DEFAULT NULL,
	`uc` CHAR(1) NULL DEFAULT NULL,
	`require_hcode` CHAR(1) NULL DEFAULT NULL,
	`oldcode` VARCHAR(5) NULL DEFAULT NULL,
	`fee_code2` VARCHAR(7) NULL DEFAULT NULL,
	`price_type` INT(11) NULL DEFAULT NULL,
	`debtor` CHAR(1) NULL DEFAULT NULL,
	`noexpire` CHAR(1) NULL DEFAULT NULL,
	`hipdata_code` VARCHAR(6) NULL DEFAULT NULL,
	`min_age` INT(11) NULL DEFAULT NULL,
	`max_age` INT(11) NULL DEFAULT NULL,
	`bill_sss` CHAR(1) NULL DEFAULT NULL,
	`bill_type` INT(11) NULL DEFAULT NULL,
	`hipdata_pttype` CHAR(3) NULL DEFAULT NULL,
	`use_contract_id` CHAR(1) NULL DEFAULT NULL,
	`yearly_charge` CHAR(1) NULL DEFAULT NULL,
	`yearly_charge_icode1` VARCHAR(7) NULL DEFAULT NULL,
	`yearly_charge_icode2` VARCHAR(7) NULL DEFAULT NULL,
	`region_type` INT(11) NULL DEFAULT NULL,
	`pttype_group1` CHAR(3) NULL DEFAULT NULL,
	`pttype_group2` CHAR(3) NULL DEFAULT NULL,
	`pttype_guid` VARCHAR(38) NULL DEFAULT NULL,
	`max_debt_money` DOUBLE(15,3) NULL DEFAULT NULL,
	`allow_finance_edit` CHAR(1) NULL DEFAULT NULL,
	`print_csmb_statement` CHAR(1) NULL DEFAULT NULL,
	`pttype_information` LONGTEXT NULL DEFAULT NULL,
	`fee_code_paidst` CHAR(2) NULL DEFAULT NULL,
	`fee_code2_paidst` CHAR(2) NULL DEFAULT NULL,
	`debt_due_day` INT(11) NULL DEFAULT NULL,
	`rx_pay_debit_tr` CHAR(1) NULL DEFAULT NULL,
	`separate_rcpno` CHAR(1) NULL DEFAULT NULL,
	`rcp_bookno` INT(11) NULL DEFAULT NULL,
	`separate_debt_id` CHAR(1) NULL DEFAULT NULL,
	`admit_fee_code` VARCHAR(7) NULL DEFAULT NULL,
	`use_package` CHAR(1) NULL DEFAULT NULL,
	`charge_df_perday` CHAR(1) NULL DEFAULT NULL,
	`nhso_code` CHAR(2) NULL DEFAULT NULL,
	`ipd_hour_cut` INT(11) NULL DEFAULT NULL,
	`pttype_spp_id` INT(11) NULL DEFAULT NULL,
	`print_presc_ned` CHAR(1) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`sks_benefit_plan_type_id` INT(11) NULL DEFAULT NULL,
	`pttype_std_code` CHAR(4) NULL DEFAULT NULL,
	`export_eclaim` CHAR(1) NULL DEFAULT NULL,
	`round_money` VARCHAR(1) NULL DEFAULT NULL,
	`pttype_price_policy_type_id` INT(11) NULL DEFAULT NULL,
	`emp_privilege` CHAR(1) NULL DEFAULT NULL,
	`is_pttype_plan` CHAR(1) NULL DEFAULT NULL,
	`finance_round_money` VARCHAR(1) NULL DEFAULT NULL,
	`emp_financial` CHAR(1) NULL DEFAULT NULL,
	`pttype_price_group_id` INT(11) NULL DEFAULT NULL,
	`calc_discount` CHAR(1) NULL DEFAULT NULL,
	`debt_finance_limit` DOUBLE(15,3) NULL DEFAULT NULL,
	`debt_finance_pttype` CHAR(2) NULL DEFAULT NULL,
	`pttype_eclaim_id` VARCHAR(2) NULL DEFAULT NULL,
	`opbkk_type_code` VARCHAR(2) NULL DEFAULT NULL,
	`ipd_bedcharge_24` CHAR(1) NULL DEFAULT NULL,
	`nhso_subinscl` VARCHAR(3) NULL DEFAULT NULL,
	`grouper_version` INT(11) NULL DEFAULT NULL,
	`SubInscl` VARCHAR(40) NULL DEFAULT NULL,
	`rx_queue_group_id` INT(11) NULL DEFAULT NULL,
	`inc_round_money` VARCHAR(1) NULL DEFAULT NULL,
	`hospmain_list` VARCHAR(100) NULL DEFAULT NULL,
	`grouper_release` VARCHAR(5) NULL DEFAULT NULL,
	`check_nhso_auth` CHAR(1) NULL DEFAULT NULL,
	`pttype_upp_type_id` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`pttype`),
	INDEX `name` (`name`),
	INDEX `ix_ix_hipdata_code` (`hipdata_code`),
	INDEX `ix_pcode` (`pcode`),
	INDEX `ix_pttype_spp_id` (`pttype_spp_id`),
	INDEX `ix_pttype_guid` (`pttype_guid`),
	INDEX `ix_nhso_code` (`nhso_code`),
	INDEX `ix_isuse` (`isuse`),
	INDEX `ix_nhso_subinscl` (`nhso_subinscl`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;