CREATE TABLE `hos`.`referout` (
	`referout_id` INT(11) NOT NULL DEFAULT '0',
	`vn` VARCHAR(13) COLLATE 'tis620_thai_ci' NOT NULL,
	`rfrcs` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_date` DATE NULL DEFAULT NULL,
	`hospcode` VARCHAR(9) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_type` TINYINT(4) NULL DEFAULT NULL,
	`refer_cause` TINYINT(4) NULL DEFAULT NULL,
	`refer_number` VARCHAR(10) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`doctor` VARCHAR(7) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`clinic` CHAR(3) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_point` VARCHAR(10) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refercheck1` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refercheck2` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refercheck3` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refercheck4` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refercheck2_date` DATE NULL DEFAULT NULL,
	`refercheck3_text` VARCHAR(150) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refercheck4_text` VARCHAR(150) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`department` CHAR(3) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_time` TIME NULL DEFAULT NULL,
	`hn` VARCHAR(9) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pttype` CHAR(2) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pre_diagnosis` VARCHAR(200) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pmh` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`hpi` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`lab_text` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`treatment_text` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`other_text` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pdx` VARCHAR(7) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`docno` VARCHAR(25) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`depcode` CHAR(3) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`confirm_date` DATE NULL DEFAULT NULL,
	`confirm_text` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`confirm_diagnosis` VARCHAR(7) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`dest_hospital_department` VARCHAR(250) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`spclty` CHAR(2) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`with_nurse` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`with_ambulance` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`due_date` DATE NULL DEFAULT NULL,
	`referout_status_id` INT(11) NULL DEFAULT NULL,
	`referout_transfer_hospcode` VARCHAR(9) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_begin_time` DATETIME NULL DEFAULT NULL,
	`refer_end_time` DATETIME NULL DEFAULT NULL,
	`refer_process_time_hour` INT(11) NULL DEFAULT NULL,
	`refer_process_time_minute` INT(11) NULL DEFAULT NULL,
	`refer_response_type_id` INT(11) NULL DEFAULT NULL,
	`senttonet` VARCHAR(5) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`rfo_sent` VARCHAR(30) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_hospcode` VARCHAR(9) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`expire_date` DATE NULL DEFAULT NULL,
	`dest_hospcode_instruction_text` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_write_staff` VARCHAR(25) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_in_province` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_in_region` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_response_text` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`vstdate` DATE NULL DEFAULT NULL,
	`i_refer_number` VARCHAR(25) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`diagnosis_text` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`cloud_refer_number` VARCHAR(25) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`ptstatus_text` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`referout_type_id` INT(11) NULL DEFAULT NULL,
	`referout_emergency_type_id` INT(11) NULL DEFAULT NULL,
	`referout_sp_type_id` INT(11) NULL DEFAULT NULL,
	`request_text` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`car_registration_no` VARCHAR(15) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`refer_acuity_type_id` INT(11) NULL DEFAULT NULL,
	`update_datetime` DATETIME NULL DEFAULT NULL,
	`accept_point` VARCHAR(10) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`with_doctor` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`issue_digital_certificate` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`service_request_sct_code` VARCHAR(15) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`service_request_sct_name` VARCHAR(100) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`update_moph_phr` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`doctor_cert_id` INT(11) NULL DEFAULT NULL,
	`issued_digital_cert` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`moph_refer_expire_type_id` INT(11) NULL DEFAULT NULL,
	`issued_moph_refer` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	PRIMARY KEY (`referout_id`) USING BTREE,
	INDEX `ix_hos_guid` (`hos_guid`) USING BTREE,
	INDEX `ix_hospcode` (`hospcode`) USING BTREE,
	INDEX `ix_refer_date` (`refer_date`) USING BTREE,
	INDEX `ix_vn` (`vn`) USING BTREE,
	INDEX `ix_refer_hospcode` (`refer_hospcode`) USING BTREE,
	INDEX `ix_cloud_refer_number` (`cloud_refer_number`) USING BTREE,
	INDEX `ix_hn` (`hn`) USING BTREE,
	INDEX `ix_update_moph_phr` (`update_moph_phr`) USING BTREE
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;
