CREATE TABLE `hos`.`refer_vital_sign` (
	`refer_vital_sign_id` INT(11) NOT NULL DEFAULT '0',
	`cc` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pe` TEXT COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`bps` INT(11) NULL DEFAULT NULL,
	`bpd` INT(11) NULL DEFAULT NULL,
	`body_weight_kg` DOUBLE(15,3) NULL DEFAULT NULL,
	`height_cm` DOUBLE(15,3) NULL DEFAULT NULL,
	`temperature` DOUBLE(15,3) NULL DEFAULT NULL,
	`rr` INT(11) NULL DEFAULT NULL,
	`hr` INT(11) NULL DEFAULT NULL,
	`refer_queue_id` INT(11) NULL DEFAULT NULL,
	`fbs` DOUBLE(15,3) NULL DEFAULT NULL,
	`pre_diagnosis` VARCHAR(100) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`hospcode` VARCHAR(9) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`coma_score_e` INT(11) NULL DEFAULT NULL,
	`coma_score_v` INT(11) NULL DEFAULT NULL,
	`coma_score_m` INT(11) NULL DEFAULT NULL,
	`pupil_size` DOUBLE(15,3) NULL DEFAULT NULL,
	`consciousness` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`death_by_transfer` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pulse` INT(11) NULL DEFAULT NULL,
	`coma_score_e_text` VARCHAR(50) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`coma_score_v_text` VARCHAR(50) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`coma_score_m_text` VARCHAR(50) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pe_ga` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pe_heent` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pe_heart` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pe_lung` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pe_neuro` CHAR(1) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pupil_size_r` DOUBLE(15,3) NULL DEFAULT NULL,
	`pupil_size_text` VARCHAR(10) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pupil_size_r_text` VARCHAR(10) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`consciousness_text` VARCHAR(200) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pe_ga_text` VARCHAR(150) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pe_heent_text` VARCHAR(150) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pe_heart_text` VARCHAR(150) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pe_lung_text` VARCHAR(150) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`pe_neuro_text` VARCHAR(150) COLLATE 'tis620_thai_ci' NULL DEFAULT NULL,
	`referout_id` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`refer_vital_sign_id`) USING BTREE,
	INDEX `ix_queue_id` (`refer_queue_id`) USING BTREE,
	INDEX `ix_referout_id` (`referout_id`) USING BTREE
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;
