CREATE TABLE `hos`.`s_drugitems` (
	`icode` VARCHAR(7) NOT NULL DEFAULT '',
	`name` VARCHAR(100) NULL DEFAULT NULL,
	`strength` VARCHAR(50) NULL DEFAULT NULL,
	`units` VARCHAR(50) NULL DEFAULT NULL,
	`dosageform` VARCHAR(100) NULL DEFAULT NULL,
	`drugnote` VARCHAR(150) NULL DEFAULT NULL,
	`use_right` CHAR(1) NULL DEFAULT NULL,
	`must_paid` CHAR(1) NULL DEFAULT NULL,
	`istatus` VARCHAR(1) NULL DEFAULT 'Y',
	`access_level` INT(11) NULL DEFAULT NULL,
	`paidst` CHAR(2) NULL DEFAULT NULL,
	`displaycolor` INT(11) NULL DEFAULT NULL,
	`price_lock` CHAR(1) NULL DEFAULT NULL,
	`icode_guid` VARCHAR(38) NULL DEFAULT NULL,
	`ename` VARCHAR(150) NULL DEFAULT NULL,
	`cost` DOUBLE(15,3) NULL DEFAULT NULL,
	`income` VARCHAR(2) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	`is_medication` CHAR(1) NULL DEFAULT NULL,
	`use_paidst` CHAR(1) NULL DEFAULT NULL,
	`is_medsupply` CHAR(1) NULL DEFAULT NULL,
	`sub_income` VARCHAR(3) NULL DEFAULT NULL,
	`highcost` VARCHAR(1) NULL DEFAULT 'N',
	`oldcode` VARCHAR(15) NULL DEFAULT NULL,
	`billcode` VARCHAR(10) NULL DEFAULT NULL,
	`billnumber` VARCHAR(15) NULL DEFAULT NULL,
	`nhso_adp_type_id` INT(11) NULL DEFAULT NULL,
	`nhso_adp_code` VARCHAR(15) NULL DEFAULT NULL,
	`unitprice` DOUBLE(15,3) NULL DEFAULT NULL,
	`tpu_code_list` VARCHAR(200) NULL DEFAULT NULL,
	`displaycolor_focus` INT(11) NULL DEFAULT NULL,
	`drugaccount` VARCHAR(2) NULL DEFAULT NULL,
	`sks_product_category_id` INT(11) NULL DEFAULT NULL,
	`sks_drug_code` VARCHAR(25) NULL DEFAULT NULL,
	`sks_dfs_code` VARCHAR(50) NULL DEFAULT NULL,
	`drugcategory` VARCHAR(150) NULL DEFAULT NULL,
	`icd9cm` VARCHAR(7) NULL DEFAULT NULL,
	`csmbs_claim_cat` VARCHAR(1) NULL DEFAULT NULL,
	`export_opd` VARCHAR(1) NULL DEFAULT NULL,
	`export_ipd` VARCHAR(1) NULL DEFAULT NULL,
	`ipd_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`max_qty` INT(11) NULL DEFAULT NULL,
	`max_qty_ipd` INT(11) NULL DEFAULT NULL,
	`drg_chrgitem_id` VARCHAR(2) NULL DEFAULT NULL,
	PRIMARY KEY (`icode`),
	INDEX `ix_name` (`name`),
	INDEX `ix_access` (`access_level`),
	INDEX `ix_status` (`istatus`),
	INDEX `ix_nsu` (`name`, `strength`, `units`),
	INDEX `ix_icode_guid` (`icode_guid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`),
	INDEX `ix_search1` (`is_medication`, `istatus`, `name`, `icode`),
	INDEX `ix_search1_index` (`icode`, `is_medication`, `istatus`, `name`),
	INDEX `ix_nsu_index` (`name`, `units`, `strength`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;