CREATE TABLE `hos`.`spclty` (
	`spclty` CHAR(2) NOT NULL DEFAULT '',
	`name` VARCHAR(150) NULL DEFAULT NULL,
	`depcode` CHAR(3) NULL DEFAULT NULL,
	`ovstostlink` CHAR(2) NULL DEFAULT NULL,
	`spname` VARCHAR(150) NULL DEFAULT NULL,
	`shortname` VARCHAR(10) NULL DEFAULT NULL,
	`ill_visit` CHAR(1) NULL DEFAULT NULL,
	`spclty_guid` VARCHAR(38) NULL DEFAULT NULL,
	`no_service_charge` CHAR(1) NULL DEFAULT NULL,
	`no_service_charge_doctor` CHAR(1) NULL DEFAULT NULL,
	`oldcode` VARCHAR(20) NULL DEFAULT NULL,
	`nhso_code` VARCHAR(5) NULL DEFAULT NULL,
	`operation` CHAR(1) NULL DEFAULT NULL,
	`provis_code` VARCHAR(10) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`no_export_43` CHAR(1) NULL DEFAULT NULL,
	`display_order` INT(11) NULL DEFAULT NULL,
	`allow_online_appointment` CHAR(1) NULL DEFAULT NULL,
	`active_status` CHAR(1) NULL DEFAULT NULL,
	PRIMARY KEY (`spclty`),
	INDEX `name` (`name`),
	INDEX `ix_spname` (`spname`),
	INDEX `ix_oldcode` (`oldcode`),
	INDEX `ix_spclty_guid` (`spclty_guid`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;