CREATE TABLE `hos`.`thaiaddress` (
	`addressid` VARCHAR(6) NOT NULL DEFAULT '',
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`engname` VARCHAR(100) NULL DEFAULT NULL,
	`chwpart` CHAR(2) NULL DEFAULT NULL,
	`amppart` CHAR(2) NULL DEFAULT NULL,
	`tmbpart` CHAR(2) NULL DEFAULT NULL,
	`codetype` CHAR(1) NULL DEFAULT NULL,
	`pocode` VARCHAR(5) NULL DEFAULT NULL,
	`full_name` VARCHAR(250) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`hos_guid_ext` VARCHAR(64) NULL DEFAULT NULL,
	PRIMARY KEY (`addressid`),
	INDEX `amppart` (`amppart`),
	INDEX `chwpart` (`chwpart`),
	INDEX `codetype` (`codetype`),
	INDEX `name` (`name`),
	INDEX `tmbpart` (`tmbpart`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_hos_guid_ext` (`hos_guid_ext`),
	INDEX `ix_chwpart_amp_codetype` (`chwpart`, `amppart`, `codetype`),
	INDEX `ix_chwpart_amp_tmb_codetype` (`chwpart`, `amppart`, `tmbpart`, `codetype`),
	INDEX `ix_chwpart_codetype` (`chwpart`, `codetype`),
	INDEX `ix_chwpart_amp_codetype_index` (`amppart`, `chwpart`, `codetype`),
	INDEX `ix_chwpart_amp_tmb_codetype_index` (`amppart`, `chwpart`, `codetype`, `tmbpart`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;