CREATE TABLE `hos`.`xray_items` (
	`xray_items_code` INT(11) NOT NULL DEFAULT 0,
	`xray_items_name` VARCHAR(250) NULL DEFAULT NULL,
	`xray_type_code` TINYINT(4) NULL DEFAULT NULL,
	`service_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`icode` VARCHAR(7) NULL DEFAULT NULL,
	`group_order` CHAR(1) NULL DEFAULT NULL,
	`ultrasound_item` CHAR(1) NULL DEFAULT NULL,
	`service_price2` DOUBLE(15,3) NULL DEFAULT NULL,
	`service_price3` DOUBLE(15,3) NULL DEFAULT NULL,
	`service_price_ipd` DOUBLE(15,3) NULL DEFAULT NULL,
	`service_price_ipd2` DOUBLE(15,3) NULL DEFAULT NULL,
	`service_price_ipd3` DOUBLE(15,3) NULL DEFAULT NULL,
	`dental_item` CHAR(1) NULL DEFAULT NULL,
	`fixed_price` CHAR(1) NULL DEFAULT NULL,
	`xray_items_group` INT(11) NULL DEFAULT NULL,
	`doctor_fee` DOUBLE(15,3) NULL DEFAULT NULL,
	`active_status` CHAR(1) NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`icd9` VARCHAR(10) NULL DEFAULT NULL,
	`loinc_code` VARCHAR(15) NULL DEFAULT NULL,
	`oldcode` VARCHAR(150) NULL DEFAULT NULL,
	`xray_items_service_type_id` INT(11) NULL DEFAULT NULL,
	`charge_when_order` CHAR(1) NULL DEFAULT NULL,
	`use_film_price` CHAR(1) NULL DEFAULT NULL,
	`charge_when_visit` CHAR(1) NULL DEFAULT NULL,
	`charge_when_xray` CHAR(1) NULL DEFAULT NULL,
	`search_keyword` VARCHAR(200) NULL DEFAULT NULL,
	`xray_ai_type_id` INT(11) NULL DEFAULT NULL,
	`exposure_qty` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`xray_items_code`),
	INDEX `xray_items_name` (`xray_items_name`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_keyword` (`search_keyword`),
	INDEX `ix_code_ai_type` (`xray_ai_type_id`, `xray_items_code`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;