CREATE TABLE `hos`.`xray_report` (
	`xn` INT(11) NOT NULL DEFAULT 0,
	`hn` VARCHAR(9) NULL DEFAULT NULL,
	`report_date` DATE NULL DEFAULT NULL,
	`report_time` TIME NULL DEFAULT NULL,
	`report_rtf` LONGBLOB NULL DEFAULT NULL,
	`report_text` LONGTEXT NULL DEFAULT NULL,
	`doctor` VARCHAR(6) NULL DEFAULT NULL,
	`vn` VARCHAR(13) NULL DEFAULT NULL,
	`examined_date` DATE NULL DEFAULT NULL,
	`examined_time` TIME NULL DEFAULT NULL,
	`xray_room_id` INT(11) NULL DEFAULT NULL,
	`xray_pt_status` INT(11) NULL DEFAULT NULL,
	`xray_type` INT(11) NULL DEFAULT NULL,
	`request_doctor` VARCHAR(6) NULL DEFAULT NULL,
	`request_date` DATE NULL DEFAULT NULL,
	`request_time` TIME NULL DEFAULT NULL,
	`confirm` CHAR(1) NULL DEFAULT NULL,
	`clinical_information` TEXT NULL DEFAULT NULL,
	`request_note` TEXT NULL DEFAULT NULL,
	`xray_items_code` INT(11) NULL DEFAULT NULL,
	`request_staff` VARCHAR(25) NULL DEFAULT NULL,
	`an` VARCHAR(13) NULL DEFAULT NULL,
	`normal` CHAR(1) NULL DEFAULT NULL,
	`xray_side` INT(11) NULL DEFAULT NULL,
	`staff` VARCHAR(25) NULL DEFAULT NULL,
	`confirm_read_film` CHAR(1) NULL DEFAULT NULL,
	`report_doctor` VARCHAR(10) NULL DEFAULT NULL,
	`doctor_fee` DOUBLE(15,3) NULL DEFAULT NULL,
	`xray_icd10` VARCHAR(7) NULL DEFAULT NULL,
	`opitemrece_guid` VARCHAR(38) NULL DEFAULT NULL,
	`xray_note` TEXT NULL DEFAULT NULL,
	`request_depcode` VARCHAR(3) NULL DEFAULT NULL,
	`xray_priority_id` INT(11) NULL DEFAULT NULL,
	`visit_time_type_id` INT(11) NULL DEFAULT NULL,
	`xray_keeper_id` INT(11) NULL DEFAULT NULL,
	`request_count_in_year` INT(11) NULL DEFAULT NULL,
	`xray_status_id` INT(11) NULL DEFAULT NULL,
	`xray_time_type_id` INT(11) NULL DEFAULT NULL,
	`xray_try_count` INT(11) NULL DEFAULT NULL,
	`pt_xn` INT(11) NULL DEFAULT NULL,
	`pt_class_xn` INT(11) NULL DEFAULT NULL,
	`clinical_diagnosis` TEXT NULL DEFAULT NULL,
	`hos_guid` VARCHAR(38) NULL DEFAULT NULL,
	`finance_lock` CHAR(1) NULL DEFAULT NULL,
	`xray_items_group_count_in_year` INT(11) NULL DEFAULT NULL,
	`xray_items_count_in_year` INT(11) NULL DEFAULT NULL,
	`xray_icd10_2` VARCHAR(7) NULL DEFAULT NULL,
	`pack_status` VARCHAR(1) NULL DEFAULT NULL,
	`xray_icd10_3` VARCHAR(10) NULL DEFAULT NULL,
	`xray_icd10_4` VARCHAR(10) NULL DEFAULT NULL,
	`pac_request` CHAR(1) NULL DEFAULT NULL,
	`pac_request_datetime` DATETIME NULL DEFAULT NULL,
	`pac_request_message` VARCHAR(150) NULL DEFAULT NULL,
	`pac_emergency_code` INT(11) NULL DEFAULT NULL,
	`walk_id` INT(11) NULL DEFAULT NULL,
	`xray_items_service_type_id` INT(11) NULL DEFAULT NULL,
	`accept_date` DATE NULL DEFAULT NULL,
	`accept_time` TIME NULL DEFAULT NULL,
	`confirm_read_date` DATE NULL DEFAULT NULL,
	`confirm_read_time` TIME NULL DEFAULT NULL,
	`confirm_radiology` CHAR(1) NULL DEFAULT NULL,
	`confirm_radiology_date` DATE NULL DEFAULT NULL,
	`confirm_radiology_time` TIME NULL DEFAULT NULL,
	`xray_report_status_id` INT(11) NULL DEFAULT NULL,
	`service_price` DOUBLE(15,3) NULL DEFAULT NULL,
	`xray_form_order_id` INT(11) NULL DEFAULT NULL,
	`write_data` CHAR(1) NULL DEFAULT NULL,
	`no_radiologist` CHAR(1) NULL DEFAULT NULL,
	`finance_xray_clear` CHAR(1) NULL DEFAULT NULL,
	`pregnant` CHAR(1) NULL DEFAULT NULL,
	`order_datetime` DATETIME NULL DEFAULT NULL,
	`xray_items_group_type_id` INT(11) NULL DEFAULT NULL,
	`final_read_film` CHAR(1) NULL DEFAULT NULL,
	`pacs_flag` CHAR(1) NULL DEFAULT NULL,
	`ai_available` CHAR(1) NULL DEFAULT NULL,
	`radiologist_report_result` CHAR(1) NULL DEFAULT NULL,
	`ai_report_type_id` INT(11) NULL DEFAULT NULL,
	`consult_flag` CHAR(1) NULL DEFAULT NULL,
	`consult_text` TEXT NULL DEFAULT NULL,
	`ref_order_code` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`xn`),
	INDEX `ix_ix_an` (`an`),
	INDEX `ix_ix_hn` (`hn`),
	INDEX `ix_ix_report_date` (`report_date`),
	INDEX `ix_ix_request_date` (`request_date`),
	INDEX `ix_ix_vn` (`vn`),
	INDEX `ix_opiguid` (`opitemrece_guid`),
	INDEX `ix_hos_guid` (`hos_guid`),
	INDEX `ix_form_order_id` (`xray_form_order_id`),
	INDEX `ix_xn_xray_items_code` (`xn`, `xray_items_code`),
	INDEX `ix_rf` (`pacs_flag`, `request_date`, `confirm_radiology`),
	INDEX `ix_rp` (`report_date`, `pacs_flag`),
	INDEX `ix_ref_order_code` (`ref_order_code`)
) COLLATE='tis620_thai_ci' ENGINE=InnoDB;