#import "scores.typ"
#let parse_vs(vs, birthday) = [
  #let ews_s = scores.score_vs("ews",vs,birthday)
  #let qsofa_s = scores.score_vs("qsofa",vs,birthday)
  #let sirs_s = scores.score_vs("sirs",vs,birthday)
  #if vs.bt != none [#strong[T:] #vs.bt \u{00b0}C]
  #if vs.pr != none [#strong[P:] #vs.pr \/min]
  #if vs.rr != none [#strong[R:] #vs.rr \/min]
  #if vs.sbp != none or vs.dbp != none [#strong[BP:] #vs.sbp\/#vs.dbp mmHg]
  #if vs.map != none [#strong[MAP:] #vs.map mmHg]
  #if vs.sat != none [#strong[O\u{2082}sat:] #vs.sat %]
  #if vs.pain != none [#strong[Pain:] #vs.pain\/10]
  #if vs.dtx != none [#strong[DTX:] #vs.dtx mg%]
  #if vs.hct != none [#strong[HCT:] #vs.hct %]
  #if vs.crt != none [#strong[CRT:] #vs.crt sec]
  #if vs.conscious_name != none [#vs.conscious_name]
  #if vs.eye != none or vs.verbal != none or vs.movement != none [#strong[GCS:] E#vs.eye\V#vs.verbal\M#vs.movement]
  #if vs.right_pupil != none or vs.right_cha_name != none or vs.left_pupil != none or vs.left_cha_name != none {
    if vs.right_pupil == vs.left_pupil and vs.right_cha_name == vs.left_cha_name [#strong[Pupils:] #vs.right_pupil mm both #vs.right_cha_name]
    else [#strong[Pupils:] Rt #vs.right_pupil mm #vs.right_cha_name Lt #vs.left_pupil mm #vs.left_cha_name]
  }
  #if vs.lt_arm_name != none or vs.lt_leg_name != none or vs.rt_arm_name != none or vs.rt_leg_name != none {
    if vs.lt_arm_name == vs.lt_leg_name and vs.rt_arm_name == vs.rt_leg_name and vs.lt_arm_name == vs.rt_arm_name [#strong[Motor power:] grade #vs.rt_arm_name all]
    else [#strong[Motor power:] Rt-arm #vs.rt_arm_name, Lt-arm #vs.lt_arm_name, Rt-leg #vs.rt_leg_name, Lt-leg #vs.lt_leg_name]
  }
  #if ews_s.score != none [#strong[#ews_s.label:] #ews_s.score]
  #if qsofa_s.score != none [#strong[#qsofa_s.label:] #qsofa_s.score]
  #if sirs_s.score != none [#strong[#sirs_s.label:] #sirs_s.score]
  #if vs.braden != none [#strong[Braden:] #vs.braden.split().first()]
  #if vs.va_name != none [#strong[VA:] #vs.va_name]
  #if vs.mass_name != none [#strong[MAAS:] #vs.mass_name]
  #if vs.severity != none [#strong[Severity:] #vs.severity]
  #if vs.barthel_index != none [#strong[Barthel ADL:] #vs.barthel_index.split().first()]
  #if vs.o2_name != none [#strong[O\u{2082}:] #vs.o2_name #if vs.o2_flow != none [#vs.o2_flow L\/min]]
  #if vs.tube_name != none [#strong[On ] #vs.tube_name #if vs.tube_no != none [No. #vs.tube_no] #if vs.tube_mark != none [depth #vs.tube_mark]]
  #if vs.ventilator_name != none [#strong[Ventilator:] #vs.ventilator_name
    #if vs.mode != none [in #vs.mode mode]
    #if vs.tv != none [#strong[TV:] #vs.tv mL]
    #if vs.pip != none [#strong[PIP:] #vs.pip cmH\u{2082}O]
    #if vs.r_rate != none [#strong[RR:] #vs.r_rate \/min]
    #if vs.i_rate != none and vs.e_rate != none [#strong[I:E ] #vs.i_rate\:#vs.e_rate]
    #if vs.ti != none [#strong[Ti:] #vs.ti sec]
    #if vs.ps != none [#strong[PS:] #vs.ps cmH\u{2082}O]
    #if vs.fio2 != none [#strong[FiO\u{2082}:] #vs.fio2]
    #if vs.peep != none [#strong[PEEP:] #vs.peep cmH\u{2082}O]
    #if vs.ft != none [#strong[FT:] #vs.ft L\/min]
    #if vs.delta_p != none [#strong[\u{2206}P:] #vs.delta_p cmH\u{2082}O]
    #if vs.o2_map != none [#strong[MAP:] #vs.o2_map cmH\u{2082}O]
  ]
  #if vs.line_name != none [#strong[Line:] #vs.line_name]
  #if vs.line_no != none [#strong[Line No:] #vs.line_no]
  #if vs.line_mark != none [#strong[Line Mark:] #vs.line_mark]
  #if vs.cvp != none [#strong[CVP:] #vs.cvp mmHg]
  #if vs.end_co2 != none [#strong[EtCO\u{2082}:] #vs.end_co2 mmHg]
  #if vs.t_inc != none [#strong[Incubator T:] #vs.t_inc \u{00b0}C]
  #if vs.lr_int != none [#strong[I:] #vs.lr_int min]
  #if vs.lr_dur != none [#strong[D:] #vs.lr_dur sec]
  #if vs.lr_fsh != none [#strong[FHS:] #vs.lr_fsh \/min]
  #if vs.lr_sev != none [#strong[S:] #vs.lr_sev]
  #if vs.lr_cer != none [#strong[Cx:] #vs.lr_cer cm]
  #if vs.lr_eff != none [#strong[Eff:] #vs.lr_eff %]
  #if vs.lr_sta != none [#strong[St:] #vs.lr_sta]
  #if vs.lr_mem_name != none [#strong[Mem:] #vs.lr_mem_name]
  #if vs.lr_af != none [#strong[AF:] #vs.lr_af]
  #if vs.amphetamine_awq != none {
    let split = vs.amphetamine_awq.split(",");
    [#strong[AWQv2:] #split.first() (H: #split.at(1,default:none), A: #split.at(2,default:none), R: #split.at(3,default:none))]}
  #if vs.aggression_oas != none [#strong[OAS:] #vs.aggression_oas.split(",").first()]
  #if vs.motivation_scale != none [#strong[Motivation scale:] #vs.motivation_scale]
  #if vs.craving_scale != none [#strong[Craving scale:] #vs.craving_scale]
  #if vs.stage_of_change_name != none [#strong[Stage of change:] #vs.stage_of_change_name]
  #if vs.alcohol_ciwa != none [#strong[CIWA-Ar:] #vs.alcohol_ciwa.split(",").first()]
  #if vs.alcohol_aws != none [#strong[AWS:] #vs.alcohol_aws.split(",").first()]
  #if vs.had_name != none [#strong[HAD:] #vs.had_name #if vs.had_drop != none [rate #vs.had_drop]]
  #if vs.bl != none [#strong[Lactate:] #vs.bl]
  #if vs.mcb != none [#strong[MCB:] #vs.mcb]
  #if vs.suction != none [#strong[Suction:] done]
  #if vs.nb != none [#strong[NB:] done]
  #if vs.bw != none [#strong[BW:] #if decimal(vs.bw) > decimal(5) {calc.round(decimal(vs.bw),digits:1)} else {vs.bw} kg]
  #if vs.height != none [#strong[HT:] #vs.height cm]
  #if vs.urine != none [#strong[Urine:] #vs.urine ครั้ง\/12hr]
  #if vs.feces != none [#strong[Feces:] #vs.feces ครั้ง\/12hr]
  #if vs.head != none [#strong[HC:] #vs.head cm]
  #if vs.other != none [#strong[Other:] #vs.other]
]
